// Copyright (c) 2026 Adam Ousmer. All rights reserved.
// Proprietary. No license granted. See LICENSE.md.

package scope

import (
	"context"
	"flag"
	"os"
	"path/filepath"
	"testing"

	"ItsBagelBot/pkg/codec"
	"ItsBagelBot/pkg/tmpl"
)

// writeGolden regenerates testdata/pure.golden.json instead of asserting
// against it:
//
//	go test ./app/twitch/sesame/engine/scope/... -run TestPureGolden -scope.write-golden
//
// Regeneration is a flag and never a side effect of running the suite, per the
// repo's golden-output convention: a fixture the suite can rewrite documents
// whatever the code currently does, which is the opposite of the point.
//
// This file is a CROSS-LANGUAGE contract, like pkg/tmpl's lexer golden beside
// it. console/shared/lib/pure.test.ts asserts the TypeScript port of these
// utilities against the same rows, because the dashboard rehearsal and the
// marketing site's command builder compute {math:…}, {queryescape:…},
// {pathescape:…} and {repeat:…} FOR REAL rather than showing a stand-in — a
// preview that computes a different answer than chat is worse than no preview.
var writeGolden = flag.Bool("scope.write-golden", false, "rewrite testdata/pure.golden.json from pureGoldenRows()")

var pureGoldenPath = filepath.Join("testdata", "pure.golden.json")

// pureGoldenRow is one utility contract case: expanding Tmpl through a chain
// carrying only scope.Pure must produce Want, byte for byte, in every language
// that implements these utilities.
//
// The rows deliberately carry no clock and no dice: {random}, {choice},
// {countdown} and {countup} are not functions of their span alone (they draw,
// or they read the time), so they are pinned by the Go and TypeScript suites
// separately with an injected clock rather than by a shared fixture that would
// have to freeze one.
type pureGoldenRow struct {
	Name string `json:"name"`
	Tmpl string `json:"tmpl"`
	Want string `json:"want"`
}

type pureGoldenFile struct {
	Note string          `json:"note"`
	Rows []pureGoldenRow `json:"rows"`
}

const pureGoldenNote = "Generated by app/twitch/sesame/engine/scope: go test ./app/twitch/sesame/engine/scope/... " +
	"-run TestPureGolden -scope.write-golden. Shared by the Go pure scope (engine/scope/pure.go, math.go) and the " +
	"TypeScript port (console/shared/lib/pure.ts). Deterministic utilities only: no dice, no clock."

// pureGoldenRows builds the corpus in code (never by hand), so widening
// coverage is adding a case here and rerunning the flag.
func pureGoldenRows() []pureGoldenRow {
	rows := append(mathGoldenRows(), escapeGoldenRows()...)
	return append(rows, repeatGoldenRows()...)
}

// mathGoldenRows pin the arithmetic grammar: precedence, parens, unary minus,
// truncating division, and every shape that resolves to "" instead.
func mathGoldenRows() []pureGoldenRow {
	return []pureGoldenRow{
		{"addition", "{math:1+2}", "3"},
		{"precedence: times binds tighter than plus", "{math:1+2*3}", "7"},
		{"precedence: divide binds tighter than minus", "{math:10-6/2}", "7"},
		{"parens override precedence", "{math:(1+2)*3}", "9"},
		{"nested parens", "{math:((2+3)*(4-1))/5}", "3"},
		{"left associative minus", "{math:10-3-2}", "5"},
		{"left associative divide", "{math:100/5/2}", "10"},
		{"integer division truncates toward zero", "{math:7/2}", "3"},
		{"negative division truncates toward zero", "{math:0-7/2}", "-3"},
		{"unary minus", "{math:-4+10}", "6"},
		{"unary minus on a paren", "{math:-(3*3)}", "-9"},
		{"double unary minus", "{math:5--3}", "8"},
		{"spaces are ignored", "{math: 2 * ( 3 + 4 ) }", "14"},
		{"a lone number is an expression", "{math:42}", "42"},
		{"leading zeros are still digits", "{math:007+1}", "8"},
		{"division by zero renders nothing", "{math:1/0}", ""},
		{"division by a zero sub-expression renders nothing", "{math:1/(2-2)}", ""},
		{"junk renders nothing", "{math:hello}", ""},
		{"a letter inside an expression renders nothing", "{math:2+x}", ""},
		{"a trailing operator renders nothing", "{math:2+}", ""},
		{"an unbalanced paren renders nothing", "{math:(1+2}", ""},
		{"a stray close paren renders nothing", "{math:1+2)}", ""},
		{"two numbers with no operator render nothing", "{math:1 2}", ""},
		{"a unary plus is not part of the grammar", "{math:+2}", ""},
		{"a modulo is not part of the grammar", "{math:7%2}", ""},
		{"an empty expression renders nothing", "{math:}", ""},
		{"overflow renders nothing", "{math:9223372036854775807+1}", ""},
		{"a number too large to hold renders nothing", "{math:99999999999999999999}", ""},
		{"multiplication overflow renders nothing", "{math:4611686018427387904*4}", ""},
		{"an expression over the byte cap renders nothing", "{math:1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1}", ""},
		{"a long expression under the byte cap still evaluates", "{math:1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1}", "32"},
		{"a bare name is not the token", "{math}", "{math}"},
		{"a failed expression renders its fallback", "{math:1/0|no idea}", "no idea"},
	}
}

// escapeGoldenRows pin the two encoders byte for byte, including the one
// difference between them (a space) and the reserved characters where they
// disagree.
func escapeGoldenRows() []pureGoldenRow {
	return []pureGoldenRow{
		{"query escape turns a space into a plus", "{queryescape:hello world}", "hello+world"},
		{"path escape turns a space into a percent escape", "{pathescape:hello world}", "hello%20world"},
		{"query escape percent-encodes reserved characters", "{queryescape:a&b=c?d}", "a%26b%3Dc%3Fd"},
		{"path escape keeps the sub-delimiters a path segment allows", "{pathescape:a&b=c?d}", "a&b=c%3Fd"},
		{"path escape escapes the segment separators", "{pathescape:a/b;c,d}", "a%2Fb%3Bc%2Cd"},
		{"query escape leaves the unreserved set alone", "{queryescape:aZ0-_.~}", "aZ0-_.~"},
		{"path escape leaves the unreserved set alone", "{pathescape:aZ0-_.~}", "aZ0-_.~"},
		{"query escape encodes a plus", "{queryescape:a+b}", "a%2Bb"},
		{"path escape keeps a plus", "{pathescape:a+b}", "a+b"},
		{"query escape encodes non-ASCII as UTF-8 bytes", "{queryescape:café}", "caf%C3%A9"},
		{"path escape encodes non-ASCII as UTF-8 bytes", "{pathescape:café}", "caf%C3%A9"},
		{"query escape encodes an emoji as four bytes", "{queryescape:🥯}", "%F0%9F%A5%AF"},
		{"query escape encodes a quote and a hash", "{queryescape:a\"b#c}", "a%22b%23c"},
		{"an empty payload escapes to nothing", "{queryescape:}", ""},
		{"an empty payload renders its fallback", "{queryescape:|nothing}", "nothing"},
		{"a bare queryescape is not the token", "{queryescape}", "{queryescape}"},
		{"a bare pathescape is not the token", "{pathescape}", "{pathescape}"},
	}
}

// repeatGoldenRows pin the repeat grammar and both of its caps.
func repeatGoldenRows() []pureGoldenRow {
	return []pureGoldenRow{
		{"repeat joins with single spaces", "{repeat:3:hi}", "hi hi hi"},
		{"repeat once is the phrase itself", "{repeat:1:hi}", "hi"},
		{"a phrase may contain spaces", "{repeat:2:oh no}", "oh no oh no"},
		{"a phrase may contain colons", "{repeat:2:a:b}", "a:b a:b"},
		{"the count cap is inclusive", "{repeat:20:x}", "x x x x x x x x x x x x x x x x x x x x"},
		{"a count over the cap renders nothing", "{repeat:21:x}", ""},
		{"a zero count renders nothing", "{repeat:0:hi}", ""},
		{"a negative count renders nothing", "{repeat:-2:hi}", ""},
		{"a signed count renders nothing", "{repeat:+2:hi}", ""},
		{"a non-numeric count renders nothing", "{repeat:two:hi}", ""},
		{"an empty phrase renders nothing", "{repeat:3:}", ""},
		{"a payload with no colon renders nothing", "{repeat:3}", ""},
		{"a bare repeat is not the token", "{repeat}", "{repeat}"},
		{"a refused repeat renders its fallback", "{repeat:0:hi|nope}", "nope"},
	}
}

// TestPureGolden asserts every row against the committed fixture and, with
// -scope.write-golden, rewrites it instead.
func TestPureGolden(t *testing.T) {
	rows := pureGoldenRows()
	chain := Chain{Pure{}}
	for _, row := range rows {
		toks := tmpl.Lex(row.Tmpl)
		values := chain.Plan(context.Background(), toks, nil)
		if got := string(chain.Render(nil, toks, values)); got != row.Want {
			t.Errorf("%s: %q rendered %q, want %q", row.Name, row.Tmpl, got, row.Want)
		}
	}
	if *writeGolden {
		writePureGolden(t, rows)
		return
	}
	assertPureGolden(t, rows)
}

func writePureGolden(t *testing.T, rows []pureGoldenRow) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(pureGoldenPath), 0o755); err != nil {
		t.Fatalf("mkdir testdata: %v", err)
	}
	if err := os.WriteFile(pureGoldenPath, marshalPureGolden(t, rows), 0o644); err != nil {
		t.Fatalf("write %s: %v", pureGoldenPath, err)
	}
	t.Logf("rewrote %s with %d rows", pureGoldenPath, len(rows))
}

func assertPureGolden(t *testing.T, rows []pureGoldenRow) {
	t.Helper()
	have, err := os.ReadFile(pureGoldenPath)
	if err != nil {
		t.Fatalf("read %s (regenerate with -scope.write-golden): %v", pureGoldenPath, err)
	}
	if want := marshalPureGolden(t, rows); string(have) != string(want) {
		t.Errorf("%s is stale. Every consumer of these utilities (Go and TypeScript) "+
			"just changed output; if that was intended, rerun with -scope.write-golden.", pureGoldenPath)
	}
}

func marshalPureGolden(t *testing.T, rows []pureGoldenRow) []byte {
	t.Helper()
	// codec, not encoding/json: pkg/codec is the fleet's one JSON
	// implementation (a guard test enforces it).
	out, err := codec.MarshalIndent(pureGoldenFile{Note: pureGoldenNote, Rows: rows}, "", "  ")
	if err != nil {
		t.Fatalf("marshal golden: %v", err)
	}
	return append(out, '\n')
}
