// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"ItsBagelBot/app/commands/ent/commands"
	"ItsBagelBot/app/commands/ent/fetchdefinition"
	"ItsBagelBot/app/commands/ent/fetchkey"
	"ItsBagelBot/app/commands/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commandsHooks := schema.Commands{}.Hooks()
	commands.Hooks[0] = commandsHooks[0]
	commandsFields := schema.Commands{}.Fields()
	_ = commandsFields
	// commandsDescName is the schema descriptor for name field.
	commandsDescName := commandsFields[1].Descriptor()
	// commands.NameValidator is a validator for the "name" field. It is called by the builders before save.
	commands.NameValidator = commandsDescName.Validators[0].(func(string) error)
	// commandsDescResponse is the schema descriptor for response field.
	commandsDescResponse := commandsFields[3].Descriptor()
	// commands.ResponseValidator is a validator for the "response" field. It is called by the builders before save.
	commands.ResponseValidator = func() func(string) error {
		validators := commandsDescResponse.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(response string) error {
			for _, fn := range fns {
				if err := fn(response); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// commandsDescIsActive is the schema descriptor for is_active field.
	commandsDescIsActive := commandsFields[4].Descriptor()
	// commands.DefaultIsActive holds the default value on creation for the is_active field.
	commands.DefaultIsActive = commandsDescIsActive.Default.(bool)
	// commandsDescStreamOnlineOnly is the schema descriptor for stream_online_only field.
	commandsDescStreamOnlineOnly := commandsFields[5].Descriptor()
	// commands.DefaultStreamOnlineOnly holds the default value on creation for the stream_online_only field.
	commands.DefaultStreamOnlineOnly = commandsDescStreamOnlineOnly.Default.(bool)
	// commandsDescPerm is the schema descriptor for perm field.
	commandsDescPerm := commandsFields[6].Descriptor()
	// commands.DefaultPerm holds the default value on creation for the perm field.
	commands.DefaultPerm = commandsDescPerm.Default.(string)
	// commandsDescCooldown is the schema descriptor for cooldown field.
	commandsDescCooldown := commandsFields[7].Descriptor()
	// commands.DefaultCooldown holds the default value on creation for the cooldown field.
	commands.DefaultCooldown = commandsDescCooldown.Default.(uint)
	// commandsDescAllowedUserID is the schema descriptor for allowed_user_id field.
	commandsDescAllowedUserID := commandsFields[8].Descriptor()
	// commands.DefaultAllowedUserID holds the default value on creation for the allowed_user_id field.
	commands.DefaultAllowedUserID = commandsDescAllowedUserID.Default.(uint64)
	// commandsDescUses is the schema descriptor for uses field.
	commandsDescUses := commandsFields[9].Descriptor()
	// commands.DefaultUses holds the default value on creation for the uses field.
	commands.DefaultUses = commandsDescUses.Default.(uint64)
	// commandsDescCreatedAt is the schema descriptor for created_at field.
	commandsDescCreatedAt := commandsFields[10].Descriptor()
	// commands.DefaultCreatedAt holds the default value on creation for the created_at field.
	commands.DefaultCreatedAt = commandsDescCreatedAt.Default.(func() time.Time)
	// commandsDescUpdatedAt is the schema descriptor for updated_at field.
	commandsDescUpdatedAt := commandsFields[11].Descriptor()
	// commands.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	commands.DefaultUpdatedAt = commandsDescUpdatedAt.Default.(func() time.Time)
	// commands.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	commands.UpdateDefaultUpdatedAt = commandsDescUpdatedAt.UpdateDefault.(func() time.Time)
	fetchdefinitionHooks := schema.FetchDefinition{}.Hooks()
	fetchdefinition.Hooks[0] = fetchdefinitionHooks[0]
	fetchdefinitionFields := schema.FetchDefinition{}.Fields()
	_ = fetchdefinitionFields
	// fetchdefinitionDescName is the schema descriptor for name field.
	fetchdefinitionDescName := fetchdefinitionFields[1].Descriptor()
	// fetchdefinition.NameValidator is a validator for the "name" field. It is called by the builders before save.
	fetchdefinition.NameValidator = func() func(string) error {
		validators := fetchdefinitionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// fetchdefinitionDescURL is the schema descriptor for url field.
	fetchdefinitionDescURL := fetchdefinitionFields[2].Descriptor()
	// fetchdefinition.URLValidator is a validator for the "url" field. It is called by the builders before save.
	fetchdefinition.URLValidator = fetchdefinitionDescURL.Validators[0].(func(string) error)
	// fetchdefinitionDescKeyLabel is the schema descriptor for key_label field.
	fetchdefinitionDescKeyLabel := fetchdefinitionFields[4].Descriptor()
	// fetchdefinition.KeyLabelValidator is a validator for the "key_label" field. It is called by the builders before save.
	fetchdefinition.KeyLabelValidator = fetchdefinitionDescKeyLabel.Validators[0].(func(string) error)
	// fetchdefinitionDescIsActive is the schema descriptor for is_active field.
	fetchdefinitionDescIsActive := fetchdefinitionFields[5].Descriptor()
	// fetchdefinition.DefaultIsActive holds the default value on creation for the is_active field.
	fetchdefinition.DefaultIsActive = fetchdefinitionDescIsActive.Default.(bool)
	// fetchdefinitionDescCreatedAt is the schema descriptor for created_at field.
	fetchdefinitionDescCreatedAt := fetchdefinitionFields[6].Descriptor()
	// fetchdefinition.DefaultCreatedAt holds the default value on creation for the created_at field.
	fetchdefinition.DefaultCreatedAt = fetchdefinitionDescCreatedAt.Default.(func() time.Time)
	// fetchdefinitionDescUpdatedAt is the schema descriptor for updated_at field.
	fetchdefinitionDescUpdatedAt := fetchdefinitionFields[7].Descriptor()
	// fetchdefinition.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	fetchdefinition.DefaultUpdatedAt = fetchdefinitionDescUpdatedAt.Default.(func() time.Time)
	// fetchdefinition.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	fetchdefinition.UpdateDefaultUpdatedAt = fetchdefinitionDescUpdatedAt.UpdateDefault.(func() time.Time)
	fetchkeyFields := schema.FetchKey{}.Fields()
	_ = fetchkeyFields
	// fetchkeyDescLabel is the schema descriptor for label field.
	fetchkeyDescLabel := fetchkeyFields[1].Descriptor()
	// fetchkey.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	fetchkey.LabelValidator = func() func(string) error {
		validators := fetchkeyDescLabel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(label string) error {
			for _, fn := range fns {
				if err := fn(label); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// fetchkeyDescLast4 is the schema descriptor for last4 field.
	fetchkeyDescLast4 := fetchkeyFields[3].Descriptor()
	// fetchkey.Last4Validator is a validator for the "last4" field. It is called by the builders before save.
	fetchkey.Last4Validator = fetchkeyDescLast4.Validators[0].(func(string) error)
	// fetchkeyDescCreatedAt is the schema descriptor for created_at field.
	fetchkeyDescCreatedAt := fetchkeyFields[4].Descriptor()
	// fetchkey.DefaultCreatedAt holds the default value on creation for the created_at field.
	fetchkey.DefaultCreatedAt = fetchkeyDescCreatedAt.Default.(func() time.Time)
	// fetchkeyDescUpdatedAt is the schema descriptor for updated_at field.
	fetchkeyDescUpdatedAt := fetchkeyFields[5].Descriptor()
	// fetchkey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	fetchkey.DefaultUpdatedAt = fetchkeyDescUpdatedAt.Default.(func() time.Time)
	// fetchkey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	fetchkey.UpdateDefaultUpdatedAt = fetchkeyDescUpdatedAt.UpdateDefault.(func() time.Time)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
