# Copyright (c) 2026 Adam Ousmer. All rights reserved.
# Proprietary. No license granted. See LICENSE.md.

operator: OAIVPW5REPRLMCTD5ATABGZZ5D4HYEGYQ7QBPPDUYHYXYF4USELST26H
accounts:
    ADMIN_RPC: ADAMI2JOMDMTTNKZINQIQJX46TYDLER6X5NQ3XE64LPKSVDVJUZ537WM
    BUS: ACIYGG26BMT5F25HWF456SM5NNKFDE5X7OBQVCCPQIKQVKY5GXWPNLSD
    COMMANDS_RPC: ACZPFBWYR7GLJGHFYC743VANRQVV3I3FDZV5QAJ2RTJKC6RSRFXTODZC
    DASHBOARD_RPC: ABEQZ2F6L3UOQ7DJK6KBAWATGZNUPBHILQ7MCKJU2XECCTX6NK7YGF4L
    DEPLOYER_RPC: ACKY3VZW4LML3GWJ2ELE66OWNQBMB7KWTWVOYXZUEJ3N26OYVEQML6SH
    DISCORD_DATA_RPC: ACTUBOKJXAREO3ZXH7TLVPCEYO5R7GLSXRPTACU4Q2AWKAB426CPZBWR
    DISCORD_ENGINE_RPC: ADF2HGOJKEBPOBFA22HEIITLLEQF6XCJW6PD2QCROKPDFSQJVY2A5OTZ
    DISCORD_INGRESS_RPC: AAPQRKBBHG2XV5OIGWTZC3KPVOUP2OYYK5LCZYDTFKH2GZCCRJ5JYVVT
    DISCORD_OUTGRESS_RPC: ACEVG65AEAUTINRHO56HUAVQIYKOAI3CM2S74UI5SWTIS43LJ7DYIQZB
    GOSSIP_RPC: ACTX3EQFTSNC3UWMT4KRUZ2WDYGPPBNPJDR64RADQLZC4ZD4I5B23GPY
    LOYALTY_RPC: ABL72F565PXNIZNAMES2UU5MCVG3IE3BVK27SEU2OBZKNS2QG2PRCRET
    MODULES_RPC: ADBOROMCXKYPPZG6IVYOR76EK2EYACGNWHQXXIWYNPOTMUSC24U67OJW
    NOTIFICATIONS_RPC: ABH2LHW4WMBKJT5H5RUJLT3JRKNEFGH6IUAJ2NYQSCCVLFHZ2JCRJGVH
    OUTGRESS_RPC: ACEKIG3FSZSFSMSB4QP6WMLRCEFJDN5B63GNXER5TNOQMQFZDYOXXPRM
    PROJECTOR_RPC: ACTNS57R7C2XPAZMAD2PR3U4EV4EVZZIDDAQUBIA3QMB2YUA3ONMKQKI
    SYS: AC5SIJGZFZMV4WYWUNG7OET6X3IOFUWZVYELM57QLLA25LCHPGVTK7ZR
    TRANSACTIONS_RPC: ADQQWQZTPDGCWKPECR6ENL5MAGZ57QCF7APHUGNRFS6TBPS2URG7AFM5
    TWITCH_INGRESS_RPC: ACQOGML7IZ4NE5ONFP4O6USM5DC7UA3QANQXUNH7QA5EQEQEVWS3ZGU7
    USERS_RPC: ADFSXHC3MIUTLJW6EKTQP7LI2RNL7YYQKDMPBSTMBR6FYHZCLQ3SZCJV
    WORKER_RPC: ACJCBY3YVYVJZS3O4WKPAWZJBB3HP4RVUPGPQESO3X76CJ55DF2VPE77
roles:
    ADMIN_RPC:
        admin_rpc: ACJ7IMFN5V3OZZG445RRTV5KRR2LAAH3XOX625FG52IIUDPJHRCLW2CD
    BUS:
        admin_bus: AAWSGIZ4J7DMWGY4QIKXN5Z3W4OJODSUHTJ6PTNXDYAPXX7IAAXR6Y26
        commands_bus: ABR47G7ASFIONKQXK5U7G7O667KNCHIULF73LKBU3W6R6GMLFTGYIXJ6
        dashboard_bus: AB5GB3SBR4RL324HBVOFM5QABQWVYRBXHU2COC4WIZVL4DQOOT6GGBHL
        deployer_bus: ABERNXB36ZACZPJVG4GPM6KEAPM4D7ATXN3EPN7LPLYYTLCMN2RCUCXG
        discord_engine_bus: AC5Q3677LFWILN2BCKYGAUZ56XXCJAAXGOEJTSAPBJGYSURCYPMMEUIT
        discord_ingress_bus: ACN2HQP4O5LBCFA3GXZG2YHSCMWMHFR4QZAKN4Q3BCVJMRYLVUKAHSVE
        discord_outgress_bus: AAEPDFH67J2OGXLXW2MVP7UVRFDCVD7DJ3OFNCU7S27TOWRO7JWLMRG7
        loyalty_bus: ABHRAVS6UP3IWFOEVIVEUE3ZVGS7W5WB3ZISEIWO2D5KNQTY7LCAQXTH
        modules_bus: ADI56GJJVGQUSI6GONLPN2P63ZT6WBSE22QDTQQKAMESKDEVVVCJ7N7N
        outgress_bus: AA7U5L6NYJAOVIYTAWGQA6AIQXGCNXVKXPWSAEWKTJQS4FFXZCQERSGG
        projector_bus: ADWA7IDXCR6ZWPIRH2TKINBU4SPT2MCCI7LBCW63XCYQYAXQR7GXW3WK
        twitch_ingress_bus: AA6ZFDJB4SKKXR74P6GOO7KGCK64VBZLEVX67IRFWFNAX5PAXSEOQWUR
        users_bus: ADPJH6YZHNJE3PCYFLBTMCPCTBS3SPHDULBJEXYRG7AYCUYHN26OUTIH
        worker_bus: AADFL226T7X3NU2TDVUJLII66LQIRLYDE7OSUZT4NQRFP27H6T5RKHRO
    COMMANDS_RPC:
        commands_rpc: ACVWNDF6VCBQA5NPWHOR2TQMSFLSRBQLA2PBE7HZI2TAYP7P75O6XOET
    DASHBOARD_RPC:
        dashboard_rpc: AAW6NMOQLJN6UTGQYXTSCB52EFYYP4CZ3ECYEEGLQRCWGKZOWRW6ERE3
    DEPLOYER_RPC:
        deployer_rpc: ABBIXIWLKU6RJKICAFLP26YQSBJVHF2IT5W3I5E7UZ2W77MVKAMWEIN2
    DISCORD_DATA_RPC:
        discord_data_rpc: ACIWNTKSAGYEQCSJ3O7GGDSHBM72P7644VD6CJ54Q37J2F4Y6TDXF3UL
    DISCORD_ENGINE_RPC:
        discord_engine_rpc: AA7M2GBFGYLX33EYRJMWGD7BONXZUL773I6V4WK6ZK7PSNA5XS6X3LRA
    DISCORD_INGRESS_RPC:
        discord_ingress_rpc: ACHNFUZURPYOA6I7MRNM7XXHS5F7PFUDS5AV3GBMAMIXRONJ55ERAT4W
    DISCORD_OUTGRESS_RPC:
        discord_outgress_rpc: ACPK2AJQ224L4MGUVPPAXSP7X4BQGAFOIRQJNIC6TTNOO4AFM5753AJS
    GOSSIP_RPC:
        gossip_rpc: AA6TML4PK4CBAA7VCMR54QOZ4A4TXATIH3OB2FTFRBNWTPTJT2TIZS4X
    LOYALTY_RPC:
        loyalty_rpc: AAFZFCE4DNSLB7MSRIEPLY4STXKVCBWVVFXTV3YCTDZ3BJZYWLWDRLKA
    MODULES_RPC:
        modules_rpc: ACTNHY7LKJNFLBSYISE436LFOWHXQUJPVVFDLO6H5EWCZ5MRJXXHYAXB
    NOTIFICATIONS_RPC:
        notifications_rpc: AD64YNXQMSQ3KHTJKFCWFDXBGKTCVYIXL4T5EADSIEPFTLDWT7YX6KWO
    OUTGRESS_RPC:
        outgress_rpc: ADNB7S4545F4BGHFGAVLNLAITCHF7OSSGTWK3IQ24FNULKKDFHE2WT4Y
    PROJECTOR_RPC:
        projector_rpc: AABJSHFJYNRO4K26RCWYPCMNK7H2CDHW6B4T67HN7UOWW6J4ESWBQ255
    SYS:
        sys: AAWI3UJHFMBPVLKIM7ZAE3WVHDVSUHWWNBLZFL3B2H2S5KCICI4PILSO
    TRANSACTIONS_RPC:
        transactions_rpc: AAN53GR5L4UHGX3LGOVHX7G53NS2Y2CVIIR6B4E3JMGF7WGZ5LSMZIFN
    TWITCH_INGRESS_RPC:
        twitch_ingress_rpc: AC2VFLEPJC6TDUJ3WEYUTSKQRI4TXLPHMMSUCAFCTEJEHPBV3RBVMOJW
    USERS_RPC:
        users_rpc: ABTFRZPF33GJRKCLDJSAIKULTCDQXC2AG5P3CUMTHGCK4Z44ASLZY6EH
    WORKER_RPC:
        worker_rpc: AD4MM27IZOXL72NJJE5RRWC3ADVUHSIQG5XKRRCJ22K54Z2EG4OH6TZW
activations:
    ADMIN_RPC:
        - from: DEPLOYER_RPC
          subject: bagel.rpc.admin.deploy.>
          token: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJPM1dMSzRUSE9RWUZGVU9OU1k3S0dFNENHTk9QQUFJRVA3SEJBMkJJSjdRTksyTktKRDVRIiwiaWF0IjoxNzkwMjc5ODE0LCJpc3MiOiJBQ0tZM1ZaVzRMTUwzR1dKMkVMRTY2T1dOUUJNQjdLV1RXVk9ZWFpVRUozTjI2T1lWRVFNTDZTSCIsInN1YiI6IkFEQU1JMkpPTURNVFROS1pJTlFJUUpYNDZUWURMRVI2WDVOUTNYRTY0TFBLU1ZEVkpVWjUzN1dNIiwibmF0cyI6eyJzdWJqZWN0IjoiYmFnZWwucnBjLmFkbWluLmRlcGxveS5cdTAwM2UiLCJraW5kIjoic2VydmljZSIsInR5cGUiOiJhY3RpdmF0aW9uIiwidmVyc2lvbiI6Mn19.8RlEzuzM05TI77wOHg7f-OZdboXqkcYYx5uXKELUQW-7-pps9VC1o6Z1ie90Mx4iCO5m-QqjqL-025_39Z87Bg
        - from: DEPLOYER_RPC
          subject: bagel.deploy.events.>
          token: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJPM1dMSzRUSE9RWUZGVU9OU1k3S0dFNENHTk9QQUFJRVA3SEJBMkJJSjdRTksyTktKRDVRIiwiaWF0IjoxNzkwMjc5ODE0LCJpc3MiOiJBQ0tZM1ZaVzRMTUwzR1dKMkVMRTY2T1dOUUJNQjdLV1RXVk9ZWFpVRUozTjI2T1lWRVFNTDZTSCIsInN1YiI6IkFEQU1JMkpPTURNVFROS1pJTlFJUUpYNDZUWURMRVI2WDVOUTNYRTY0TFBLU1ZEVkpVWjUzN1dNIiwibmF0cyI6eyJzdWJqZWN0IjoiYmFnZWwuZGVwbG95LmV2ZW50cy5cdTAwM2UiLCJraW5kIjoic3RyZWFtIiwidHlwZSI6ImFjdGl2YXRpb24iLCJ2ZXJzaW9uIjoyfX0.cxYdTsqIvq83mG3ERsBd-lOgZOodv4M7VPPubBAL-Y2CWHPj-60R5EaT7kpyfnju9_lOK7mk4GJLTDDIxqaGCg
