# Copyright (c) 2026 Adam Ousmer. All rights reserved.
# Proprietary. No license granted. See LICENSE.md.

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-hub-tls
  namespace: messaging
spec:
  secretName: nats-hub-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - nats
    - nats.messaging
    - nats.messaging.svc
    - nats.messaging.svc.cluster.local
    - nats-headless
    - nats-headless.messaging.svc.cluster.local
    - nats-0.nats-headless.messaging.svc.cluster.local
    - nats-1.nats-headless.messaging.svc.cluster.local
    - nats-2.nats-headless.messaging.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-leaf-tls
  namespace: messaging
spec:
  secretName: nats-leaf-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - nats-leaf
    - nats-leaf.messaging
    - nats-leaf.messaging.svc
    - nats-leaf.messaging.svc.cluster.local
    - nats-leaf-local
    - nats-leaf-local.messaging
    - nats-leaf-local.messaging.svc
    - nats-leaf-local.messaging.svc.cluster.local
    - nats-leaf-peers
    - nats-leaf-peers.messaging
    - nats-leaf-peers.messaging.svc
    - nats-leaf-peers.messaging.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
