# Copyright (c) 2026 Adam Ousmer. All rights reserved.
# Proprietary. No license granted. See LICENSE.md.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: messaging
resources:
  - certificates.yaml
  - nats.yaml
  - nats-leaf.yaml
  - nats-auth-dopplersecret.yaml
configMapGenerator:
  - name: nats-config
    files:
      - nats.conf=nats-server.conf
      - auth.conf=nats-operator.conf
      - operator.jwt
      - accounts.conf=nats-accounts.conf
  - name: nats-leaf-config
    files:
      - nats.conf=nats-leaf-server.conf
      - auth.conf=nats-operator.conf
      - operator.jwt
      - accounts.conf=nats-accounts.conf
generatorOptions:
  disableNameSuffixHash: true
