# Copyright (c) 2026 Adam Ousmer. All rights reserved.
# Proprietary. No license granted. See LICENSE.md.

apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: nats-auth-env
  namespace: messaging
spec:
  host: https://api.doppler.com
  tokenSecret:
    name: nats-doppler-token
  managedSecret:
    name: nats-auth-env
    namespace: messaging
    type: Opaque
  resyncSeconds: 60
