# Copyright (c) 2026 Adam Ousmer. All rights reserved.
# Proprietary and unlicensed. See LICENSE.md.

---
- name: Restart tailscaled
  ansible.builtin.shell: sleep 2 && systemctl restart tailscaled
  async: 1
  poll: 0
  ignore_errors: true
