// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"ItsBagelBot/app/db/loyalty/ent/balance"
	"ItsBagelBot/app/db/loyalty/ent/counter"
	"ItsBagelBot/app/db/loyalty/ent/counterbatch"
	"ItsBagelBot/app/db/loyalty/ent/counterentry"
	"ItsBagelBot/app/db/loyalty/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	balanceFields := schema.Balance{}.Fields()
	_ = balanceFields
	// balanceDescViewerLogin is the schema descriptor for viewer_login field.
	balanceDescViewerLogin := balanceFields[2].Descriptor()
	// balance.ViewerLoginValidator is a validator for the "viewer_login" field. It is called by the builders before save.
	balance.ViewerLoginValidator = balanceDescViewerLogin.Validators[0].(func(string) error)
	// balanceDescViewerName is the schema descriptor for viewer_name field.
	balanceDescViewerName := balanceFields[3].Descriptor()
	// balance.ViewerNameValidator is a validator for the "viewer_name" field. It is called by the builders before save.
	balance.ViewerNameValidator = balanceDescViewerName.Validators[0].(func(string) error)
	// balanceDescPoints is the schema descriptor for points field.
	balanceDescPoints := balanceFields[4].Descriptor()
	// balance.DefaultPoints holds the default value on creation for the points field.
	balance.DefaultPoints = balanceDescPoints.Default.(int64)
	// balanceDescWatchSeconds is the schema descriptor for watch_seconds field.
	balanceDescWatchSeconds := balanceFields[5].Descriptor()
	// balance.DefaultWatchSeconds holds the default value on creation for the watch_seconds field.
	balance.DefaultWatchSeconds = balanceDescWatchSeconds.Default.(uint64)
	// balanceDescCreatedAt is the schema descriptor for created_at field.
	balanceDescCreatedAt := balanceFields[6].Descriptor()
	// balance.DefaultCreatedAt holds the default value on creation for the created_at field.
	balance.DefaultCreatedAt = balanceDescCreatedAt.Default.(func() time.Time)
	// balanceDescUpdatedAt is the schema descriptor for updated_at field.
	balanceDescUpdatedAt := balanceFields[7].Descriptor()
	// balance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	balance.DefaultUpdatedAt = balanceDescUpdatedAt.Default.(func() time.Time)
	// balance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	balance.UpdateDefaultUpdatedAt = balanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	counterHooks := schema.Counter{}.Hooks()
	counter.Hooks[0] = counterHooks[0]
	counterFields := schema.Counter{}.Fields()
	_ = counterFields
	// counterDescName is the schema descriptor for name field.
	counterDescName := counterFields[1].Descriptor()
	// counter.NameValidator is a validator for the "name" field. It is called by the builders before save.
	counter.NameValidator = func() func(string) error {
		validators := counterDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// counterDescScope is the schema descriptor for scope field.
	counterDescScope := counterFields[2].Descriptor()
	// counter.DefaultScope holds the default value on creation for the scope field.
	counter.DefaultScope = counterDescScope.Default.(string)
	// counterDescValue is the schema descriptor for value field.
	counterDescValue := counterFields[3].Descriptor()
	// counter.DefaultValue holds the default value on creation for the value field.
	counter.DefaultValue = counterDescValue.Default.(int64)
	// counter.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	counter.ValueValidator = func() func(int64) error {
		validators := counterDescValue.Validators
		fns := [...]func(int64) error{
			validators[0].(func(int64) error),
			validators[1].(func(int64) error),
		}
		return func(value int64) error {
			for _, fn := range fns {
				if err := fn(value); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// counterDescCreatedAt is the schema descriptor for created_at field.
	counterDescCreatedAt := counterFields[4].Descriptor()
	// counter.DefaultCreatedAt holds the default value on creation for the created_at field.
	counter.DefaultCreatedAt = counterDescCreatedAt.Default.(func() time.Time)
	// counterDescUpdatedAt is the schema descriptor for updated_at field.
	counterDescUpdatedAt := counterFields[5].Descriptor()
	// counter.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	counter.DefaultUpdatedAt = counterDescUpdatedAt.Default.(func() time.Time)
	// counter.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	counter.UpdateDefaultUpdatedAt = counterDescUpdatedAt.UpdateDefault.(func() time.Time)
	counterbatchFields := schema.CounterBatch{}.Fields()
	_ = counterbatchFields
	// counterbatchDescCreatedAt is the schema descriptor for created_at field.
	counterbatchDescCreatedAt := counterbatchFields[1].Descriptor()
	// counterbatch.DefaultCreatedAt holds the default value on creation for the created_at field.
	counterbatch.DefaultCreatedAt = counterbatchDescCreatedAt.Default.(func() time.Time)
	// counterbatchDescID is the schema descriptor for id field.
	counterbatchDescID := counterbatchFields[0].Descriptor()
	// counterbatch.IDValidator is a validator for the "id" field. It is called by the builders before save.
	counterbatch.IDValidator = counterbatchDescID.Validators[0].(func(string) error)
	counterentryHooks := schema.CounterEntry{}.Hooks()
	counterentry.Hooks[0] = counterentryHooks[0]
	counterentryFields := schema.CounterEntry{}.Fields()
	_ = counterentryFields
	// counterentryDescName is the schema descriptor for name field.
	counterentryDescName := counterentryFields[1].Descriptor()
	// counterentry.NameValidator is a validator for the "name" field. It is called by the builders before save.
	counterentry.NameValidator = func() func(string) error {
		validators := counterentryDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// counterentryDescCommand is the schema descriptor for command field.
	counterentryDescCommand := counterentryFields[2].Descriptor()
	// counterentry.DefaultCommand holds the default value on creation for the command field.
	counterentry.DefaultCommand = counterentryDescCommand.Default.(string)
	// counterentry.CommandValidator is a validator for the "command" field. It is called by the builders before save.
	counterentry.CommandValidator = counterentryDescCommand.Validators[0].(func(string) error)
	// counterentryDescViewerLogin is the schema descriptor for viewer_login field.
	counterentryDescViewerLogin := counterentryFields[4].Descriptor()
	// counterentry.ViewerLoginValidator is a validator for the "viewer_login" field. It is called by the builders before save.
	counterentry.ViewerLoginValidator = counterentryDescViewerLogin.Validators[0].(func(string) error)
	// counterentryDescViewerName is the schema descriptor for viewer_name field.
	counterentryDescViewerName := counterentryFields[5].Descriptor()
	// counterentry.ViewerNameValidator is a validator for the "viewer_name" field. It is called by the builders before save.
	counterentry.ViewerNameValidator = counterentryDescViewerName.Validators[0].(func(string) error)
	// counterentryDescValue is the schema descriptor for value field.
	counterentryDescValue := counterentryFields[6].Descriptor()
	// counterentry.DefaultValue holds the default value on creation for the value field.
	counterentry.DefaultValue = counterentryDescValue.Default.(int64)
	// counterentry.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	counterentry.ValueValidator = func() func(int64) error {
		validators := counterentryDescValue.Validators
		fns := [...]func(int64) error{
			validators[0].(func(int64) error),
			validators[1].(func(int64) error),
		}
		return func(value int64) error {
			for _, fn := range fns {
				if err := fn(value); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// counterentryDescUpdatedAt is the schema descriptor for updated_at field.
	counterentryDescUpdatedAt := counterentryFields[7].Descriptor()
	// counterentry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	counterentry.DefaultUpdatedAt = counterentryDescUpdatedAt.Default.(func() time.Time)
	// counterentry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	counterentry.UpdateDefaultUpdatedAt = counterentryDescUpdatedAt.UpdateDefault.(func() time.Time)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
