// Code generated by ent, DO NOT EDIT.

package giveawayaward

import (
	"ItsBagelBot/app/db/transactions/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContainsFold(FieldID, id))
}

// GiveawayID applies equality check predicate on the "giveaway_id" field. It's identical to GiveawayIDEQ.
func GiveawayID(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldGiveawayID, v))
}

// DrawID applies equality check predicate on the "draw_id" field. It's identical to DrawIDEQ.
func DrawID(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldDrawID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldUserID, v))
}

// Ordinal applies equality check predicate on the "ordinal" field. It's identical to OrdinalEQ.
func Ordinal(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldOrdinal, v))
}

// PrizeMonths applies equality check predicate on the "prize_months" field. It's identical to PrizeMonthsEQ.
func PrizeMonths(v int) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldPrizeMonths, v))
}

// IntervalRule applies equality check predicate on the "interval_rule" field. It's identical to IntervalRuleEQ.
func IntervalRule(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldIntervalRule, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldState, v))
}

// BillingState applies equality check predicate on the "billing_state" field. It's identical to BillingStateEQ.
func BillingState(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldBillingState, v))
}

// EmailState applies equality check predicate on the "email_state" field. It's identical to EmailStateEQ.
func EmailState(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldEmailState, v))
}

// PlannedStart applies equality check predicate on the "planned_start" field. It's identical to PlannedStartEQ.
func PlannedStart(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldPlannedStart, v))
}

// PlannedEnd applies equality check predicate on the "planned_end" field. It's identical to PlannedEndEQ.
func PlannedEnd(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldPlannedEnd, v))
}

// ConfirmedStart applies equality check predicate on the "confirmed_start" field. It's identical to ConfirmedStartEQ.
func ConfirmedStart(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldConfirmedStart, v))
}

// ConfirmedEnd applies equality check predicate on the "confirmed_end" field. It's identical to ConfirmedEndEQ.
func ConfirmedEnd(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldConfirmedEnd, v))
}

// GrantID applies equality check predicate on the "grant_id" field. It's identical to GrantIDEQ.
func GrantID(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldGrantID, v))
}

// BillingOperationID applies equality check predicate on the "billing_operation_id" field. It's identical to BillingOperationIDEQ.
func BillingOperationID(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldBillingOperationID, v))
}

// FailureReason applies equality check predicate on the "failure_reason" field. It's identical to FailureReasonEQ.
func FailureReason(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldFailureReason, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldRetryCount, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldVersion, v))
}

// SelectedAt applies equality check predicate on the "selected_at" field. It's identical to SelectedAtEQ.
func SelectedAt(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldSelectedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldUpdatedAt, v))
}

// GiveawayIDEQ applies the EQ predicate on the "giveaway_id" field.
func GiveawayIDEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldGiveawayID, v))
}

// GiveawayIDNEQ applies the NEQ predicate on the "giveaway_id" field.
func GiveawayIDNEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldGiveawayID, v))
}

// GiveawayIDIn applies the In predicate on the "giveaway_id" field.
func GiveawayIDIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldGiveawayID, vs...))
}

// GiveawayIDNotIn applies the NotIn predicate on the "giveaway_id" field.
func GiveawayIDNotIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldGiveawayID, vs...))
}

// GiveawayIDGT applies the GT predicate on the "giveaway_id" field.
func GiveawayIDGT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldGiveawayID, v))
}

// GiveawayIDGTE applies the GTE predicate on the "giveaway_id" field.
func GiveawayIDGTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldGiveawayID, v))
}

// GiveawayIDLT applies the LT predicate on the "giveaway_id" field.
func GiveawayIDLT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldGiveawayID, v))
}

// GiveawayIDLTE applies the LTE predicate on the "giveaway_id" field.
func GiveawayIDLTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldGiveawayID, v))
}

// GiveawayIDContains applies the Contains predicate on the "giveaway_id" field.
func GiveawayIDContains(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContains(FieldGiveawayID, v))
}

// GiveawayIDHasPrefix applies the HasPrefix predicate on the "giveaway_id" field.
func GiveawayIDHasPrefix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasPrefix(FieldGiveawayID, v))
}

// GiveawayIDHasSuffix applies the HasSuffix predicate on the "giveaway_id" field.
func GiveawayIDHasSuffix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasSuffix(FieldGiveawayID, v))
}

// GiveawayIDEqualFold applies the EqualFold predicate on the "giveaway_id" field.
func GiveawayIDEqualFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEqualFold(FieldGiveawayID, v))
}

// GiveawayIDContainsFold applies the ContainsFold predicate on the "giveaway_id" field.
func GiveawayIDContainsFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContainsFold(FieldGiveawayID, v))
}

// DrawIDEQ applies the EQ predicate on the "draw_id" field.
func DrawIDEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldDrawID, v))
}

// DrawIDNEQ applies the NEQ predicate on the "draw_id" field.
func DrawIDNEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldDrawID, v))
}

// DrawIDIn applies the In predicate on the "draw_id" field.
func DrawIDIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldDrawID, vs...))
}

// DrawIDNotIn applies the NotIn predicate on the "draw_id" field.
func DrawIDNotIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldDrawID, vs...))
}

// DrawIDGT applies the GT predicate on the "draw_id" field.
func DrawIDGT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldDrawID, v))
}

// DrawIDGTE applies the GTE predicate on the "draw_id" field.
func DrawIDGTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldDrawID, v))
}

// DrawIDLT applies the LT predicate on the "draw_id" field.
func DrawIDLT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldDrawID, v))
}

// DrawIDLTE applies the LTE predicate on the "draw_id" field.
func DrawIDLTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldDrawID, v))
}

// DrawIDContains applies the Contains predicate on the "draw_id" field.
func DrawIDContains(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContains(FieldDrawID, v))
}

// DrawIDHasPrefix applies the HasPrefix predicate on the "draw_id" field.
func DrawIDHasPrefix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasPrefix(FieldDrawID, v))
}

// DrawIDHasSuffix applies the HasSuffix predicate on the "draw_id" field.
func DrawIDHasSuffix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasSuffix(FieldDrawID, v))
}

// DrawIDEqualFold applies the EqualFold predicate on the "draw_id" field.
func DrawIDEqualFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEqualFold(FieldDrawID, v))
}

// DrawIDContainsFold applies the ContainsFold predicate on the "draw_id" field.
func DrawIDContainsFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContainsFold(FieldDrawID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldUserID, v))
}

// OrdinalEQ applies the EQ predicate on the "ordinal" field.
func OrdinalEQ(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldOrdinal, v))
}

// OrdinalNEQ applies the NEQ predicate on the "ordinal" field.
func OrdinalNEQ(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldOrdinal, v))
}

// OrdinalIn applies the In predicate on the "ordinal" field.
func OrdinalIn(vs ...uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldOrdinal, vs...))
}

// OrdinalNotIn applies the NotIn predicate on the "ordinal" field.
func OrdinalNotIn(vs ...uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldOrdinal, vs...))
}

// OrdinalGT applies the GT predicate on the "ordinal" field.
func OrdinalGT(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldOrdinal, v))
}

// OrdinalGTE applies the GTE predicate on the "ordinal" field.
func OrdinalGTE(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldOrdinal, v))
}

// OrdinalLT applies the LT predicate on the "ordinal" field.
func OrdinalLT(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldOrdinal, v))
}

// OrdinalLTE applies the LTE predicate on the "ordinal" field.
func OrdinalLTE(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldOrdinal, v))
}

// PrizeMonthsEQ applies the EQ predicate on the "prize_months" field.
func PrizeMonthsEQ(v int) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldPrizeMonths, v))
}

// PrizeMonthsNEQ applies the NEQ predicate on the "prize_months" field.
func PrizeMonthsNEQ(v int) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldPrizeMonths, v))
}

// PrizeMonthsIn applies the In predicate on the "prize_months" field.
func PrizeMonthsIn(vs ...int) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldPrizeMonths, vs...))
}

// PrizeMonthsNotIn applies the NotIn predicate on the "prize_months" field.
func PrizeMonthsNotIn(vs ...int) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldPrizeMonths, vs...))
}

// PrizeMonthsGT applies the GT predicate on the "prize_months" field.
func PrizeMonthsGT(v int) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldPrizeMonths, v))
}

// PrizeMonthsGTE applies the GTE predicate on the "prize_months" field.
func PrizeMonthsGTE(v int) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldPrizeMonths, v))
}

// PrizeMonthsLT applies the LT predicate on the "prize_months" field.
func PrizeMonthsLT(v int) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldPrizeMonths, v))
}

// PrizeMonthsLTE applies the LTE predicate on the "prize_months" field.
func PrizeMonthsLTE(v int) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldPrizeMonths, v))
}

// IntervalRuleEQ applies the EQ predicate on the "interval_rule" field.
func IntervalRuleEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldIntervalRule, v))
}

// IntervalRuleNEQ applies the NEQ predicate on the "interval_rule" field.
func IntervalRuleNEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldIntervalRule, v))
}

// IntervalRuleIn applies the In predicate on the "interval_rule" field.
func IntervalRuleIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldIntervalRule, vs...))
}

// IntervalRuleNotIn applies the NotIn predicate on the "interval_rule" field.
func IntervalRuleNotIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldIntervalRule, vs...))
}

// IntervalRuleGT applies the GT predicate on the "interval_rule" field.
func IntervalRuleGT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldIntervalRule, v))
}

// IntervalRuleGTE applies the GTE predicate on the "interval_rule" field.
func IntervalRuleGTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldIntervalRule, v))
}

// IntervalRuleLT applies the LT predicate on the "interval_rule" field.
func IntervalRuleLT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldIntervalRule, v))
}

// IntervalRuleLTE applies the LTE predicate on the "interval_rule" field.
func IntervalRuleLTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldIntervalRule, v))
}

// IntervalRuleContains applies the Contains predicate on the "interval_rule" field.
func IntervalRuleContains(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContains(FieldIntervalRule, v))
}

// IntervalRuleHasPrefix applies the HasPrefix predicate on the "interval_rule" field.
func IntervalRuleHasPrefix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasPrefix(FieldIntervalRule, v))
}

// IntervalRuleHasSuffix applies the HasSuffix predicate on the "interval_rule" field.
func IntervalRuleHasSuffix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasSuffix(FieldIntervalRule, v))
}

// IntervalRuleEqualFold applies the EqualFold predicate on the "interval_rule" field.
func IntervalRuleEqualFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEqualFold(FieldIntervalRule, v))
}

// IntervalRuleContainsFold applies the ContainsFold predicate on the "interval_rule" field.
func IntervalRuleContainsFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContainsFold(FieldIntervalRule, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContainsFold(FieldState, v))
}

// BillingStateEQ applies the EQ predicate on the "billing_state" field.
func BillingStateEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldBillingState, v))
}

// BillingStateNEQ applies the NEQ predicate on the "billing_state" field.
func BillingStateNEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldBillingState, v))
}

// BillingStateIn applies the In predicate on the "billing_state" field.
func BillingStateIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldBillingState, vs...))
}

// BillingStateNotIn applies the NotIn predicate on the "billing_state" field.
func BillingStateNotIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldBillingState, vs...))
}

// BillingStateGT applies the GT predicate on the "billing_state" field.
func BillingStateGT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldBillingState, v))
}

// BillingStateGTE applies the GTE predicate on the "billing_state" field.
func BillingStateGTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldBillingState, v))
}

// BillingStateLT applies the LT predicate on the "billing_state" field.
func BillingStateLT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldBillingState, v))
}

// BillingStateLTE applies the LTE predicate on the "billing_state" field.
func BillingStateLTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldBillingState, v))
}

// BillingStateContains applies the Contains predicate on the "billing_state" field.
func BillingStateContains(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContains(FieldBillingState, v))
}

// BillingStateHasPrefix applies the HasPrefix predicate on the "billing_state" field.
func BillingStateHasPrefix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasPrefix(FieldBillingState, v))
}

// BillingStateHasSuffix applies the HasSuffix predicate on the "billing_state" field.
func BillingStateHasSuffix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasSuffix(FieldBillingState, v))
}

// BillingStateEqualFold applies the EqualFold predicate on the "billing_state" field.
func BillingStateEqualFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEqualFold(FieldBillingState, v))
}

// BillingStateContainsFold applies the ContainsFold predicate on the "billing_state" field.
func BillingStateContainsFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContainsFold(FieldBillingState, v))
}

// EmailStateEQ applies the EQ predicate on the "email_state" field.
func EmailStateEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldEmailState, v))
}

// EmailStateNEQ applies the NEQ predicate on the "email_state" field.
func EmailStateNEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldEmailState, v))
}

// EmailStateIn applies the In predicate on the "email_state" field.
func EmailStateIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldEmailState, vs...))
}

// EmailStateNotIn applies the NotIn predicate on the "email_state" field.
func EmailStateNotIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldEmailState, vs...))
}

// EmailStateGT applies the GT predicate on the "email_state" field.
func EmailStateGT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldEmailState, v))
}

// EmailStateGTE applies the GTE predicate on the "email_state" field.
func EmailStateGTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldEmailState, v))
}

// EmailStateLT applies the LT predicate on the "email_state" field.
func EmailStateLT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldEmailState, v))
}

// EmailStateLTE applies the LTE predicate on the "email_state" field.
func EmailStateLTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldEmailState, v))
}

// EmailStateContains applies the Contains predicate on the "email_state" field.
func EmailStateContains(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContains(FieldEmailState, v))
}

// EmailStateHasPrefix applies the HasPrefix predicate on the "email_state" field.
func EmailStateHasPrefix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasPrefix(FieldEmailState, v))
}

// EmailStateHasSuffix applies the HasSuffix predicate on the "email_state" field.
func EmailStateHasSuffix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasSuffix(FieldEmailState, v))
}

// EmailStateEqualFold applies the EqualFold predicate on the "email_state" field.
func EmailStateEqualFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEqualFold(FieldEmailState, v))
}

// EmailStateContainsFold applies the ContainsFold predicate on the "email_state" field.
func EmailStateContainsFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContainsFold(FieldEmailState, v))
}

// PlannedStartEQ applies the EQ predicate on the "planned_start" field.
func PlannedStartEQ(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldPlannedStart, v))
}

// PlannedStartNEQ applies the NEQ predicate on the "planned_start" field.
func PlannedStartNEQ(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldPlannedStart, v))
}

// PlannedStartIn applies the In predicate on the "planned_start" field.
func PlannedStartIn(vs ...time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldPlannedStart, vs...))
}

// PlannedStartNotIn applies the NotIn predicate on the "planned_start" field.
func PlannedStartNotIn(vs ...time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldPlannedStart, vs...))
}

// PlannedStartGT applies the GT predicate on the "planned_start" field.
func PlannedStartGT(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldPlannedStart, v))
}

// PlannedStartGTE applies the GTE predicate on the "planned_start" field.
func PlannedStartGTE(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldPlannedStart, v))
}

// PlannedStartLT applies the LT predicate on the "planned_start" field.
func PlannedStartLT(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldPlannedStart, v))
}

// PlannedStartLTE applies the LTE predicate on the "planned_start" field.
func PlannedStartLTE(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldPlannedStart, v))
}

// PlannedStartIsNil applies the IsNil predicate on the "planned_start" field.
func PlannedStartIsNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIsNull(FieldPlannedStart))
}

// PlannedStartNotNil applies the NotNil predicate on the "planned_start" field.
func PlannedStartNotNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotNull(FieldPlannedStart))
}

// PlannedEndEQ applies the EQ predicate on the "planned_end" field.
func PlannedEndEQ(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldPlannedEnd, v))
}

// PlannedEndNEQ applies the NEQ predicate on the "planned_end" field.
func PlannedEndNEQ(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldPlannedEnd, v))
}

// PlannedEndIn applies the In predicate on the "planned_end" field.
func PlannedEndIn(vs ...time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldPlannedEnd, vs...))
}

// PlannedEndNotIn applies the NotIn predicate on the "planned_end" field.
func PlannedEndNotIn(vs ...time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldPlannedEnd, vs...))
}

// PlannedEndGT applies the GT predicate on the "planned_end" field.
func PlannedEndGT(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldPlannedEnd, v))
}

// PlannedEndGTE applies the GTE predicate on the "planned_end" field.
func PlannedEndGTE(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldPlannedEnd, v))
}

// PlannedEndLT applies the LT predicate on the "planned_end" field.
func PlannedEndLT(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldPlannedEnd, v))
}

// PlannedEndLTE applies the LTE predicate on the "planned_end" field.
func PlannedEndLTE(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldPlannedEnd, v))
}

// PlannedEndIsNil applies the IsNil predicate on the "planned_end" field.
func PlannedEndIsNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIsNull(FieldPlannedEnd))
}

// PlannedEndNotNil applies the NotNil predicate on the "planned_end" field.
func PlannedEndNotNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotNull(FieldPlannedEnd))
}

// ConfirmedStartEQ applies the EQ predicate on the "confirmed_start" field.
func ConfirmedStartEQ(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldConfirmedStart, v))
}

// ConfirmedStartNEQ applies the NEQ predicate on the "confirmed_start" field.
func ConfirmedStartNEQ(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldConfirmedStart, v))
}

// ConfirmedStartIn applies the In predicate on the "confirmed_start" field.
func ConfirmedStartIn(vs ...time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldConfirmedStart, vs...))
}

// ConfirmedStartNotIn applies the NotIn predicate on the "confirmed_start" field.
func ConfirmedStartNotIn(vs ...time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldConfirmedStart, vs...))
}

// ConfirmedStartGT applies the GT predicate on the "confirmed_start" field.
func ConfirmedStartGT(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldConfirmedStart, v))
}

// ConfirmedStartGTE applies the GTE predicate on the "confirmed_start" field.
func ConfirmedStartGTE(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldConfirmedStart, v))
}

// ConfirmedStartLT applies the LT predicate on the "confirmed_start" field.
func ConfirmedStartLT(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldConfirmedStart, v))
}

// ConfirmedStartLTE applies the LTE predicate on the "confirmed_start" field.
func ConfirmedStartLTE(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldConfirmedStart, v))
}

// ConfirmedStartIsNil applies the IsNil predicate on the "confirmed_start" field.
func ConfirmedStartIsNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIsNull(FieldConfirmedStart))
}

// ConfirmedStartNotNil applies the NotNil predicate on the "confirmed_start" field.
func ConfirmedStartNotNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotNull(FieldConfirmedStart))
}

// ConfirmedEndEQ applies the EQ predicate on the "confirmed_end" field.
func ConfirmedEndEQ(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldConfirmedEnd, v))
}

// ConfirmedEndNEQ applies the NEQ predicate on the "confirmed_end" field.
func ConfirmedEndNEQ(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldConfirmedEnd, v))
}

// ConfirmedEndIn applies the In predicate on the "confirmed_end" field.
func ConfirmedEndIn(vs ...time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldConfirmedEnd, vs...))
}

// ConfirmedEndNotIn applies the NotIn predicate on the "confirmed_end" field.
func ConfirmedEndNotIn(vs ...time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldConfirmedEnd, vs...))
}

// ConfirmedEndGT applies the GT predicate on the "confirmed_end" field.
func ConfirmedEndGT(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldConfirmedEnd, v))
}

// ConfirmedEndGTE applies the GTE predicate on the "confirmed_end" field.
func ConfirmedEndGTE(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldConfirmedEnd, v))
}

// ConfirmedEndLT applies the LT predicate on the "confirmed_end" field.
func ConfirmedEndLT(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldConfirmedEnd, v))
}

// ConfirmedEndLTE applies the LTE predicate on the "confirmed_end" field.
func ConfirmedEndLTE(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldConfirmedEnd, v))
}

// ConfirmedEndIsNil applies the IsNil predicate on the "confirmed_end" field.
func ConfirmedEndIsNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIsNull(FieldConfirmedEnd))
}

// ConfirmedEndNotNil applies the NotNil predicate on the "confirmed_end" field.
func ConfirmedEndNotNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotNull(FieldConfirmedEnd))
}

// GrantIDEQ applies the EQ predicate on the "grant_id" field.
func GrantIDEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldGrantID, v))
}

// GrantIDNEQ applies the NEQ predicate on the "grant_id" field.
func GrantIDNEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldGrantID, v))
}

// GrantIDIn applies the In predicate on the "grant_id" field.
func GrantIDIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldGrantID, vs...))
}

// GrantIDNotIn applies the NotIn predicate on the "grant_id" field.
func GrantIDNotIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldGrantID, vs...))
}

// GrantIDGT applies the GT predicate on the "grant_id" field.
func GrantIDGT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldGrantID, v))
}

// GrantIDGTE applies the GTE predicate on the "grant_id" field.
func GrantIDGTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldGrantID, v))
}

// GrantIDLT applies the LT predicate on the "grant_id" field.
func GrantIDLT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldGrantID, v))
}

// GrantIDLTE applies the LTE predicate on the "grant_id" field.
func GrantIDLTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldGrantID, v))
}

// GrantIDContains applies the Contains predicate on the "grant_id" field.
func GrantIDContains(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContains(FieldGrantID, v))
}

// GrantIDHasPrefix applies the HasPrefix predicate on the "grant_id" field.
func GrantIDHasPrefix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasPrefix(FieldGrantID, v))
}

// GrantIDHasSuffix applies the HasSuffix predicate on the "grant_id" field.
func GrantIDHasSuffix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasSuffix(FieldGrantID, v))
}

// GrantIDIsNil applies the IsNil predicate on the "grant_id" field.
func GrantIDIsNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIsNull(FieldGrantID))
}

// GrantIDNotNil applies the NotNil predicate on the "grant_id" field.
func GrantIDNotNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotNull(FieldGrantID))
}

// GrantIDEqualFold applies the EqualFold predicate on the "grant_id" field.
func GrantIDEqualFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEqualFold(FieldGrantID, v))
}

// GrantIDContainsFold applies the ContainsFold predicate on the "grant_id" field.
func GrantIDContainsFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContainsFold(FieldGrantID, v))
}

// BillingOperationIDEQ applies the EQ predicate on the "billing_operation_id" field.
func BillingOperationIDEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldBillingOperationID, v))
}

// BillingOperationIDNEQ applies the NEQ predicate on the "billing_operation_id" field.
func BillingOperationIDNEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldBillingOperationID, v))
}

// BillingOperationIDIn applies the In predicate on the "billing_operation_id" field.
func BillingOperationIDIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldBillingOperationID, vs...))
}

// BillingOperationIDNotIn applies the NotIn predicate on the "billing_operation_id" field.
func BillingOperationIDNotIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldBillingOperationID, vs...))
}

// BillingOperationIDGT applies the GT predicate on the "billing_operation_id" field.
func BillingOperationIDGT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldBillingOperationID, v))
}

// BillingOperationIDGTE applies the GTE predicate on the "billing_operation_id" field.
func BillingOperationIDGTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldBillingOperationID, v))
}

// BillingOperationIDLT applies the LT predicate on the "billing_operation_id" field.
func BillingOperationIDLT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldBillingOperationID, v))
}

// BillingOperationIDLTE applies the LTE predicate on the "billing_operation_id" field.
func BillingOperationIDLTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldBillingOperationID, v))
}

// BillingOperationIDContains applies the Contains predicate on the "billing_operation_id" field.
func BillingOperationIDContains(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContains(FieldBillingOperationID, v))
}

// BillingOperationIDHasPrefix applies the HasPrefix predicate on the "billing_operation_id" field.
func BillingOperationIDHasPrefix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasPrefix(FieldBillingOperationID, v))
}

// BillingOperationIDHasSuffix applies the HasSuffix predicate on the "billing_operation_id" field.
func BillingOperationIDHasSuffix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasSuffix(FieldBillingOperationID, v))
}

// BillingOperationIDIsNil applies the IsNil predicate on the "billing_operation_id" field.
func BillingOperationIDIsNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIsNull(FieldBillingOperationID))
}

// BillingOperationIDNotNil applies the NotNil predicate on the "billing_operation_id" field.
func BillingOperationIDNotNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotNull(FieldBillingOperationID))
}

// BillingOperationIDEqualFold applies the EqualFold predicate on the "billing_operation_id" field.
func BillingOperationIDEqualFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEqualFold(FieldBillingOperationID, v))
}

// BillingOperationIDContainsFold applies the ContainsFold predicate on the "billing_operation_id" field.
func BillingOperationIDContainsFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContainsFold(FieldBillingOperationID, v))
}

// FailureReasonEQ applies the EQ predicate on the "failure_reason" field.
func FailureReasonEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldFailureReason, v))
}

// FailureReasonNEQ applies the NEQ predicate on the "failure_reason" field.
func FailureReasonNEQ(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldFailureReason, v))
}

// FailureReasonIn applies the In predicate on the "failure_reason" field.
func FailureReasonIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldFailureReason, vs...))
}

// FailureReasonNotIn applies the NotIn predicate on the "failure_reason" field.
func FailureReasonNotIn(vs ...string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldFailureReason, vs...))
}

// FailureReasonGT applies the GT predicate on the "failure_reason" field.
func FailureReasonGT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldFailureReason, v))
}

// FailureReasonGTE applies the GTE predicate on the "failure_reason" field.
func FailureReasonGTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldFailureReason, v))
}

// FailureReasonLT applies the LT predicate on the "failure_reason" field.
func FailureReasonLT(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldFailureReason, v))
}

// FailureReasonLTE applies the LTE predicate on the "failure_reason" field.
func FailureReasonLTE(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldFailureReason, v))
}

// FailureReasonContains applies the Contains predicate on the "failure_reason" field.
func FailureReasonContains(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContains(FieldFailureReason, v))
}

// FailureReasonHasPrefix applies the HasPrefix predicate on the "failure_reason" field.
func FailureReasonHasPrefix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasPrefix(FieldFailureReason, v))
}

// FailureReasonHasSuffix applies the HasSuffix predicate on the "failure_reason" field.
func FailureReasonHasSuffix(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldHasSuffix(FieldFailureReason, v))
}

// FailureReasonIsNil applies the IsNil predicate on the "failure_reason" field.
func FailureReasonIsNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIsNull(FieldFailureReason))
}

// FailureReasonNotNil applies the NotNil predicate on the "failure_reason" field.
func FailureReasonNotNil() predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotNull(FieldFailureReason))
}

// FailureReasonEqualFold applies the EqualFold predicate on the "failure_reason" field.
func FailureReasonEqualFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEqualFold(FieldFailureReason, v))
}

// FailureReasonContainsFold applies the ContainsFold predicate on the "failure_reason" field.
func FailureReasonContainsFold(v string) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldContainsFold(FieldFailureReason, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldRetryCount, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v uint64) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldVersion, v))
}

// SelectedAtEQ applies the EQ predicate on the "selected_at" field.
func SelectedAtEQ(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldSelectedAt, v))
}

// SelectedAtNEQ applies the NEQ predicate on the "selected_at" field.
func SelectedAtNEQ(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldSelectedAt, v))
}

// SelectedAtIn applies the In predicate on the "selected_at" field.
func SelectedAtIn(vs ...time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldSelectedAt, vs...))
}

// SelectedAtNotIn applies the NotIn predicate on the "selected_at" field.
func SelectedAtNotIn(vs ...time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldSelectedAt, vs...))
}

// SelectedAtGT applies the GT predicate on the "selected_at" field.
func SelectedAtGT(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldSelectedAt, v))
}

// SelectedAtGTE applies the GTE predicate on the "selected_at" field.
func SelectedAtGTE(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldSelectedAt, v))
}

// SelectedAtLT applies the LT predicate on the "selected_at" field.
func SelectedAtLT(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldSelectedAt, v))
}

// SelectedAtLTE applies the LTE predicate on the "selected_at" field.
func SelectedAtLTE(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldSelectedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GiveawayAward) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GiveawayAward) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GiveawayAward) predicate.GiveawayAward {
	return predicate.GiveawayAward(sql.NotPredicates(p))
}
