// Copyright (c) 2026 Adam Ousmer. All rights reserved.
// Proprietary. No license granted. See LICENSE.md.

/**
 * Icon source of truth. Every glyph @bagel/ui draws -- for the console, the
 * marketing site, the docs and anything that consumes this library later --
 * comes from a published set (Lucide for UI strokes, Simple Icons for brand
 * marks) through this manifest; nothing is hand-drawn. Run it after editing
 * the manifest or bumping either @iconify-json package, then commit the
 * generated file:
 *
 *   bun ui/scripts/gen-icons.mjs
 *
 * ONE target, one manifest. It used to emit two files from two manifests
 * (web/kit/lib/icons.ts for the console, web/marketing/src/lib/icons.ts for
 * the site), which is how the two `Icon` components came to disagree about
 * their default size and their props while claiming to draw the same set: a
 * name meant a different glyph depending on which file you were looking at.
 * The manifests are merged here, so a name is a glyph everywhere.
 *
 * The merge had exactly one collision, and it is the reason `brandX` exists:
 * `x` was `lucide:x` (the close mark on every dismissable console surface) in
 * one file and `simple-icons:x` (the social network's logo, in the marketing
 * social rail) in the other. The stroke mark keeps the short name because it
 * is the one used by controls; the brand mark is prefixed like what it is.
 * Brand names stay grouped below so the next collision is visible before it
 * is generated rather than after it renders the wrong glyph.
 *
 * Output is the inner markup of a 24x24 viewBox so a wrapper (svelte/Icon,
 * astro/Icon) owns stroke weight, size and colour. Lucide bodies ship
 * per-path presentation attributes (stroke-width="2" etc.) which would beat
 * the wrapper's; they are stripped here so the existing CSS overrides and
 * the 1.6 weight keep working. Simple Icons are filled marks and keep
 * fill="currentColor" on the path so they render inside the stroke wrapper
 * without a fill prop.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const sets = {
  lucide: require('@iconify-json/lucide/icons.json'),
  'simple-icons': require('@iconify-json/simple-icons/icons.json')
};

// name used in code -> "set:icon". One flat map: see the note on `brandX`
// above before adding a name that already exists in another group.
const ICONS = {
  // navigation and page marks
  overview: 'lucide:layout-dashboard',
  commands: 'lucide:terminal',
  modules: 'lucide:layout-grid',
  card: 'lucide:credit-card',
  settings: 'lucide:sliders-horizontal',
  home: 'lucide:house',
  server: 'lucide:server',
  lanes: 'lucide:columns-3',
  pulse: 'lucide:activity',
  users: 'lucide:users',
  activity: 'lucide:chart-line',
  bell: 'lucide:bell',
  moderation: 'lucide:shield',
  audit: 'lucide:scroll-text',
  list: 'lucide:list',
  // icon-only controls and state marks
  x: 'lucide:x',
  trash: 'lucide:trash-2',
  edit: 'lucide:pencil',
  search: 'lucide:search',
  plus: 'lucide:plus',
  power: 'lucide:power',
  check: 'lucide:check',
  link: 'lucide:link',
  lock: 'lucide:lock',
  chevron: 'lucide:chevron-down',
  // editorial glyphs the marketing pages draw
  leaf: 'lucide:leaf',
  bulb: 'lucide:lightbulb',
  copy: 'lucide:copy',
  // brand marks (filled, Simple Icons). Prefixed `brand` where the plain name
  // is already a stroke glyph; `discord` keeps its short name because there
  // has never been a second `discord`.
  discord: 'simple-icons:discord',
  brandX: 'simple-icons:x',
  tiktok: 'simple-icons:tiktok',
  youtube: 'simple-icons:youtube',
  github: 'simple-icons:github'
};

const STRIP = /\s(?:fill="none"|stroke="currentColor"|stroke-linecap="round"|stroke-linejoin="round"|stroke-width="2")/g;

function body(ref) {
  const [set, name] = ref.split(':');
  const icon = sets[set]?.icons[name];
  if (!icon) throw new Error(`gen-icons: ${ref} not found`);
  if (sets[set].width !== 24 || sets[set].height !== 24) throw new Error(`gen-icons: ${set} is not 24x24`);
  return set === 'lucide' ? icon.body.replace(STRIP, '') : icon.body.replace('<path ', '<path stroke="none" ');
}

function emit(manifest) {
  const lines = Object.entries(manifest).map(([k, ref]) => `  ${k}: '${body(ref)}', // ${ref}`);
  return [
    '// Copyright (c) 2026 Adam Ousmer. All rights reserved.',
    '// Proprietary. No license granted. See LICENSE.md.',
    '',
    '// GENERATED by ui/scripts/gen-icons.mjs, do not edit. Values are',
    '// the inner markup of a viewBox="0 0 24 24" SVG; the Icon wrapper draws them.',
    `// Sources: @iconify-json/lucide ${require('@iconify-json/lucide/package.json').version},`,
    `// @iconify-json/simple-icons ${require('@iconify-json/simple-icons/package.json').version}.`,
    'export const icons = {',
    ...lines,
    '} as const;',
    '',
    'export type IconName = keyof typeof icons;',
    ''
  ].join('\n');
}

const target = new URL('../lib/icons.ts', import.meta.url).pathname;
const next = emit(ICONS);
let prev = '';
try {
  prev = readFileSync(target, 'utf8');
} catch {}
if (prev !== next) {
  writeFileSync(target, next);
  console.log(`wrote ui/lib/icons.ts (${Object.keys(ICONS).length} icons)`);
} else {
  console.log('ui/lib/icons.ts up to date');
}
