// Copyright (c) 2026 Adam Ousmer. All rights reserved.
// Proprietary. No license granted. See LICENSE.md.

import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const sets = {
  lucide: require('@iconify-json/lucide/icons.json'),
  'simple-icons': require('@iconify-json/simple-icons/icons.json')
};

const ICONS = {
  overview: 'lucide:layout-dashboard',
  commands: 'lucide:terminal',
  modules: 'lucide:layout-grid',
  music: 'lucide:music',
  card: 'lucide:credit-card',
  settings: 'lucide:sliders-horizontal',
  gear: 'lucide:settings',
  home: 'lucide:house',
  server: 'lucide:server',
  lanes: 'lucide:columns-3',
  pulse: 'lucide:activity',
  users: 'lucide:users',
  activity: 'lucide:chart-line',
  bell: 'lucide:bell',
  moderation: 'lucide:shield',
  audit: 'lucide:scroll-text',
  list: 'lucide:list',
  x: 'lucide:x',
  trash: 'lucide:trash-2',
  edit: 'lucide:pencil',
  search: 'lucide:search',
  plus: 'lucide:plus',
  power: 'lucide:power',
  check: 'lucide:check',
  link: 'lucide:link',
  start: 'lucide:sparkles',
  integrate: 'lucide:plug-zap',
  quiet: 'lucide:volume-x',
  importFile: 'lucide:file-input',
  lock: 'lucide:lock',
  chevron: 'lucide:chevron-down',
  leaf: 'lucide:leaf',
  bulb: 'lucide:lightbulb',
  copy: 'lucide:copy',
  arrowLeft: 'lucide:arrow-left',
  arrowUpRight: 'lucide:arrow-up-right',
  clock: 'lucide:clock',
  bolt: 'lucide:zap',
  share: 'lucide:share',
  addSquare: 'lucide:square-plus',
  minus: 'lucide:minus',
  expand: 'lucide:maximize-2',
  coins: 'lucide:coins',
  gamepad: 'lucide:gamepad-2',
  githubLine: 'lucide:github',
  discord: 'simple-icons:discord',
  brandX: 'simple-icons:x',
  tiktok: 'simple-icons:tiktok',
  youtube: 'simple-icons:youtube',
  github: 'simple-icons:github',
  twitch: 'simple-icons:twitch'
};

const STRIP = /\s(?:fill="none"|stroke="currentColor"|stroke-linecap="round"|stroke-linejoin="round"|stroke-width="2")/g;

// lucide redrew these after they shipped; keep the shipped glyphs.
const PINNED = {
  'lucide:credit-card': '<g><rect width="20" height="14" x="2" y="5" rx="2"/><path d="M2 10h20"/></g>',
  'lucide:leaf': '<g><path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8c0 5.5-4.78 10-10 10"/><path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12"/></g>'
};

function lookup(set, name) {
  const pack = sets[set] ?? { icons: {} };
  return pack.icons[name] ?? pack.icons[pack.aliases?.[name]?.parent];
}

const isSquare = (set) => sets[set].width === 24 && sets[set].height === 24;

function body(ref) {
  const [set, name] = ref.split(':');
  const icon = lookup(set, name);
  if (!icon) throw new Error(`gen-icons: ${ref} not found`);
  if (!isSquare(set)) throw new Error(`gen-icons: ${set} is not 24x24`);
  return PINNED[ref] ?? (set === 'lucide' ? icon.body.replace(STRIP, '') : icon.body.replace('<path ', '<path stroke="none" '));
}

function emit(manifest) {
  const lines = Object.entries(manifest).map(([k, ref]) => `  ${k}: '${body(ref)}', // ${ref}`);
  return [
    '// Copyright (c) 2026 Adam Ousmer. All rights reserved.',
    '// Proprietary. No license granted. See LICENSE.md.',
    '',
    '// GENERATED by ui/scripts/gen-icons.mjs, do not edit. Values are',
    '// the inner markup of a viewBox="0 0 24 24" SVG; the Icon wrapper draws them.',
    `// Sources: @iconify-json/lucide ${require('@iconify-json/lucide/package.json').version},`,
    `// @iconify-json/simple-icons ${require('@iconify-json/simple-icons/package.json').version}.`,
    'export const icons = {',
    ...lines,
    '} as const;',
    '',
    'export type IconName = keyof typeof icons;',
    ''
  ].join('\n');
}

const target = new URL('../lib/icons.ts', import.meta.url).pathname;
const next = emit(ICONS);
let prev = '';
try {
  prev = readFileSync(target, 'utf8');
} catch {}
if (prev !== next) {
  writeFileSync(target, next);
  console.log(`wrote ui/lib/icons.ts (${Object.keys(ICONS).length} icons)`);
} else {
  console.log('ui/lib/icons.ts up to date');
}
