apiVersion: v1
kind: Service
metadata:
  name: linkerd-dst-headless
  namespace: linkerd
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: grpc
      port: 8086
      targetPort: 8086
  selector:
    linkerd.io/control-plane-component: destination
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-policy
  namespace: linkerd
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: grpc
      port: 8090
      targetPort: 8090
  selector:
    linkerd.io/control-plane-component: destination
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-identity-headless
  namespace: linkerd
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
  selector:
    linkerd.io/control-plane-component: identity
