// Copyright (c) 2026 Adam Ousmer. All rights reserved.
// Proprietary. No license granted. See LICENSE.md.

import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tokenHead } from '../engine/common-tokens';
import { lex, type VarToken } from '../engine/tmpl';
import { SIMPLE_TOKENS as FOSSABOT_SIMPLE_TOKENS, SUBFIELD_TOKENS as FOSSABOT_SUBFIELD_TOKENS } from '../importer/fossabot/variables';
import { SIMPLE_TOKENS as NIGHTBOT_SIMPLE_TOKENS } from '../importer/nightbot/variables';
import { VARIABLES } from './variables';
import { MODULE_CATALOG } from '../catalog';
import { BUILTIN_COMMANDS } from '../catalog/builtin-commands';
import en from '../i18n/locales/en.json';
import fr from '../i18n/locales/fr.json';

// The golden fixture is Go's, read at run time rather than imported, so the
// TypeScript build never has to reach outside app/ for a module. Regenerating
// it is a Go-side flag (`go test ./app/twitch/sesame/engine/scope/... -run
// TestTokenCatalogGolden -scope.write-golden`), never a side effect of
// running this suite: see ../engine/pure.test.ts, which reads its own golden
// the same way for the same reason.
const GOLDEN_PATH = join(import.meta.dir, '../../../../app/twitch/sesame/engine/scope/testdata/token_catalog.golden.json');

interface GoldenFamily {
  id: string;
  examples: string[];
}

interface GoldenFile {
  note: string;
  families: GoldenFamily[];
}

const golden: GoldenFile = JSON.parse(readFileSync(GOLDEN_PATH, 'utf8'));
const goldenExamples = golden.families.flatMap((family) => family.examples);

// The reply-token golden is the other half of the same cross-language
// handshake, read the same way for the same reason: see
// app/twitch/sesame/modules/reply_tokens.go and reply_tokens_golden_test.go
// (regenerate with `go test ./app/twitch/sesame/modules/... -run
// TestReplyTokensGolden -modules.write-golden`).
const REPLY_TOKENS_GOLDEN_PATH = join(import.meta.dir, '../../../../app/twitch/sesame/modules/testdata/reply_tokens.golden.json');

interface ReplyTokensGoldenFile {
  note: string;
  replies: Record<string, string[]>;
}

const replyTokensGolden: ReplyTokensGoldenFile = JSON.parse(readFileSync(REPLY_TOKENS_GOLDEN_PATH, 'utf8'));

// replyNamespace derives a ReplyToken.hintKey's "<moduleId>.<replyKey>"
// namespace: hintKey is always "replyVars.<namespace>.<flattenedName>.hint"
// (see hintNamespace in catalog/module-def.ts's replyTokens()), and the
// namespace itself may contain a dot (e.g. "alerts.follow"), so this reads
// off the first and last two segments rather than splitting naively.
function replyNamespace(hintKey: string): string | undefined {
  const parts = hintKey.split('.');
  if (parts.length < 4 || parts[0] !== 'replyVars' || parts[parts.length - 1] !== 'hint') return undefined;
  return parts.slice(1, parts.length - 2).join('.');
}

const isDigits = (head: string): boolean => head !== '' && /^\d+$/.test(head);

// Heads the Go resolver inventory (CommandTokenFamilies, token_catalog.go)
// has no entry for by design, so rule B does not require them in golden:
//
//   positional: generated by shape (any digit string), never enumerated as
//   one head, the same reason common-tokens.ts's isCommonToken never lists
//   {1}...{30} by name.
//
//   if: parsed by pkg/tmpl's conditional grammar (parseCond) before a scope
//   ever sees a name to Own or Get, so CommandTokenFamilies has no scope to
//   walk it out of. Confirmed by reading that function: it only enumerates
//   messageFields, pureUtils and the named scope tokens below them.
const NOT_RESOLVER_OWNED = new Set(['positional', 'if']);

const headSet = new Set<string>();
for (const v of VARIABLES) {
  headSet.add(v.head);
  for (const alias of v.aliases ?? []) headSet.add(alias);
}

function lexesToOneVar(example: string): VarToken | null {
  const tokens = lex(example);
  return tokens.length === 1 && tokens[0].kind === 'var' ? tokens[0] : null;
}

describe('variables parity (engine/scope/testdata/token_catalog.golden.json)', () => {
  test('A: every golden example resolves to a manifest head or alias', () => {
    for (const example of goldenExamples) {
      const head = tokenHead(example);
      const covered = isDigits(head) || headSet.has(head);
      expect(covered, `${example} lexes to head "${head}", which is not in VARIABLES (heads or aliases). Add it to variables.ts.`).toBe(true);
    }
  });

  test('B: every manifest head and alias is answered by the Go resolver', () => {
    const goldenHeads = new Set(goldenExamples.map((example) => tokenHead(example)));
    for (const v of VARIABLES) {
      if (NOT_RESOLVER_OWNED.has(v.head)) continue;
      expect(goldenHeads.has(v.head), `variables.ts promises "${v.head}" (id ${v.id}) but no golden example resolves it.`).toBe(true);
      for (const alias of v.aliases ?? []) {
        expect(goldenHeads.has(alias), `variables.ts promises alias "${alias}" (id ${v.id}) but no golden example resolves it.`).toBe(true);
      }
    }
  });

  test('C: every form example lexes to exactly one variable token', () => {
    for (const v of VARIABLES) {
      for (const form of v.forms) {
        const token = lexesToOneVar(form.example);
        expect(token, `${v.id}'s example "${form.example}" does not lex to exactly one {…} token.`).not.toBeNull();
      }
    }
  });

  test('D: every id has name, hint and desc in both locales', () => {
    const enVars = (en as { vars?: Record<string, unknown> }).vars ?? {};
    const frVars = (fr as { vars?: Record<string, unknown> }).vars ?? {};
    for (const v of VARIABLES) {
      for (const [locale, table] of [['en', enVars], ['fr', frVars]] as const) {
        const entry = table[v.id] as { name?: string; hint?: string; desc?: string } | undefined;
        expect(entry, `${locale}.json has no vars.${v.id}`).toBeDefined();
        expect(entry?.name, `${locale}.json vars.${v.id}.name is missing`).toBeTruthy();
        expect(entry?.hint, `${locale}.json vars.${v.id}.hint is missing`).toBeTruthy();
        expect(entry?.desc, `${locale}.json vars.${v.id}.desc is missing`).toBeTruthy();
        for (const form of v.forms) {
          if (!form.chipHint) continue;
          const chip = (entry as Record<string, unknown> | undefined)?.[form.chipHint];
          expect(chip, `${locale}.json vars.${v.id}.${form.chipHint} is missing (chipHint on ${form.syntax})`).toBeTruthy();
        }
      }
    }
  });

  test('E: importer targets resolve to a manifest head or alias', () => {
    const targets = [
      ...Object.values(NIGHTBOT_SIMPLE_TOKENS),
      ...Object.values(FOSSABOT_SIMPLE_TOKENS),
      ...Object.values(FOSSABOT_SUBFIELD_TOKENS)
    ];
    for (const target of targets) {
      const head = tokenHead(target);
      const covered = isDigits(head) || headSet.has(head);
      expect(covered, `importer target "${target}" resolves to head "${head}", which is not in VARIABLES.`).toBe(true);
    }
  });

  test('F: ids are unique, heads and aliases are unique', () => {
    const ids = new Set<string>();
    const heads = new Set<string>();
    for (const v of VARIABLES) {
      expect(ids.has(v.id), `duplicate id "${v.id}"`).toBe(false);
      ids.add(v.id);
      expect(heads.has(v.head), `duplicate head "${v.head}" (id ${v.id})`).toBe(false);
      heads.add(v.head);
      for (const alias of v.aliases ?? []) {
        expect(heads.has(alias), `duplicate head/alias "${alias}" (id ${v.id})`).toBe(false);
        heads.add(alias);
      }
    }
  });

  // docs/specs/variables-catalog.md phase 3, section A.3: a ReplyToken's
  // hintKey is generated (see replyTokens in catalog/module-def.ts), so a
  // typo in a hand-written replyKey namespace would otherwise only surface
  // as a silent English fallback in the marketing builder, never a build or
  // test failure.
  test('G: every ReplyToken.hintKey resolves in en and fr', () => {
    const lookup = (tree: unknown, key: string): unknown => {
      let node: unknown = tree;
      for (const part of key.split('.')) {
        if (node == null || typeof node !== 'object') return undefined;
        node = (node as Record<string, unknown>)[part];
      }
      return node;
    };
    const replyTokenSources = [
      ...MODULE_CATALOG.flatMap((mod) => mod.replies.map((reply) => ({ where: `${mod.id}.${reply.key}`, tokens: reply.tokens ?? [] }))),
      ...BUILTIN_COMMANDS.map((cmd) => ({ where: `builtin.${cmd.id}`, tokens: cmd.tokens ?? [] }))
    ];
    for (const { where, tokens } of replyTokenSources) {
      for (const token of tokens) {
        if (!token.hintKey) continue;
        for (const [locale, tree] of [['en', en], ['fr', fr]] as const) {
          const value = lookup(tree, token.hintKey);
          expect(typeof value === 'string' && value.length > 0, `${where} token "${token.name}": ${locale}.json has no ${token.hintKey}`).toBe(true);
        }
      }
    }
  });

  // docs/specs/variables-catalog.md phase 5: reply_tokens.golden.json is the
  // Go side's reply-token inventory (ReplyTokenInventory, app/twitch/sesame/
  // modules/reply_tokens.go), a broadcaster's customizable reply templates
  // that chat itself actually fills a token in for. Not every kit reply has
  // one yet (games, raffle, valorant and the rest of the external-stats
  // previews are kit-only surfaces with no chat command behind them), so a
  // reply whose tokens carry no hintKey at all is skipped rather than
  // failed: replyTokens() only ever attaches a hintKey to every token in a
  // reply or to none of them (one hintNamespace argument for the whole
  // call), so a reply with some tokens hinted and some not should not be
  // reachable; if it happens anyway, that is the failure below telling the
  // fix is to pass the namespace to replyTokens().
  test('H: reply-token inventory matches app/twitch/sesame/modules/reply_tokens.go (Go golden)', () => {
    const replyTokenSources = [
      ...MODULE_CATALOG.flatMap((mod) => mod.replies.map((reply) => ({ where: `${mod.id}.${reply.key}`, tokens: reply.tokens ?? [] }))),
      ...BUILTIN_COMMANDS.map((cmd) => ({ where: `builtin.${cmd.id}`, tokens: cmd.tokens ?? [] }))
    ];

    const claimedNamespaces = new Set<string>();
    for (const { where, tokens } of replyTokenSources) {
      const hinted = tokens.filter((token) => token.hintKey);
      if (hinted.length === 0) continue; // no Go counterpart yet; expected

      const ns = replyNamespace(hinted[0].hintKey!);
      expect(ns, `${where}: could not read a namespace off hintKey "${hinted[0].hintKey}": pass the namespace to replyTokens().`).toBeTruthy();
      if (!ns) continue;
      claimedNamespaces.add(ns);

      const golden = replyTokensGolden.replies[ns];
      expect(golden, `${where}: reply_tokens.golden.json has no "${ns}" namespace. Add it to app/twitch/sesame/modules/reply_tokens.go and regenerate the golden, or drop the namespace from replyTokens() if chat does not answer this reply.`).toBeDefined();
      if (!golden) continue;

      const kitNames = [...new Set(tokens.map((token) => token.name))].sort();
      const goNames = [...golden].sort();
      expect(
        kitNames,
        `${where}: kit tokens ${JSON.stringify(kitNames)} do not match Go's "${ns}" tokens ${JSON.stringify(goNames)}. Fix web/kit/lib/catalog/*.ts or app/twitch/sesame/modules/reply_tokens.go.`
      ).toEqual(goNames);
    }

    for (const ns of Object.keys(replyTokensGolden.replies)) {
      expect(
        claimedNamespaces.has(ns),
        `app/twitch/sesame/modules/reply_tokens.go declares "${ns}" but no kit replyTokens() call names it. Fix web/kit/lib/catalog/*.ts.`
      ).toBe(true);
    }
  });
});
