// Copyright (c) 2026 Adam Ousmer. All rights reserved.
// Proprietary. No license granted. See LICENSE.md.

// The golden fixture is Go's, read at run time rather than imported, so the
// TypeScript build never has to reach outside app/ for a module. Regenerating
// it is a Go-side flag (`go test ./app/twitch/sesame/engine/scope/... -run
// TestTokenCatalogGolden -scope.write-golden`), never a side effect of
// running this suite: see ../engine/pure.test.ts, which reads its own golden
// the same way for the same reason.
//
// Every rule collects its problems into a flat list and asserts the list is
// empty: one failure then names every offender at once instead of stopping
// at the first, which is what a catalogue diff needs (a renamed scope drops
// several heads in one go).

import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tokenHead } from './head';
import { lex } from '../engine/tmpl';
import { SIMPLE_TOKENS as FOSSABOT_SIMPLE_TOKENS, SUBFIELD_TOKENS as FOSSABOT_SUBFIELD_TOKENS } from '../importer/fossabot/variables';
import { SIMPLE_TOKENS as NIGHTBOT_SIMPLE_TOKENS } from '../importer/nightbot/variables';
import { VARIABLES } from './variables';
import { forSurface } from './surfaces';
import type { VariableDef } from './types';
import { MODULE_CATALOG } from '../catalog';
import { BUILTIN_COMMANDS } from '../catalog/builtin-commands';
import type { ReplyToken } from '../catalog/module-def';
import en from '../i18n/locales/en.json';
import fr from '../i18n/locales/fr.json';

const GOLDEN_PATH = join(import.meta.dir, '../../../../app/twitch/sesame/engine/scope/testdata/token_catalog.golden.json');

interface GoldenFile {
  note: string;
  families: { id: string; examples: string[]; aliases?: string[] }[];
  surfaces: { timer: string[] };
}

const golden: GoldenFile = JSON.parse(readFileSync(GOLDEN_PATH, 'utf8'));
const goldenExamples = golden.families.flatMap((family) => family.examples);
const goldenHeads = new Set(goldenExamples.map((example) => tokenHead(example)));

// A family's `aliases` are its pre-simplification spellings (TokenFamily.
// Aliases, token_catalog.go): genuinely answered by the resolver, but left
// out of `examples` on purpose, since the public catalogue teaches the
// canonical spelling only. Rule B reads names from here as well as from
// goldenHeads so a manifest alias does not need a golden EXAMPLE of its own
// to be considered answered — that used to be a hand-kept TypeScript set
// (LEGACY_ALIASES) the Go side could drift out from under silently; reading
// it from the golden makes Go the one source for "this old spelling still
// resolves".
const goldenAliasHeads = new Set(golden.families.flatMap((family) => family.aliases ?? []).map(tokenHead));

// The reply-token golden is the other half of the same cross-language
// handshake, read the same way for the same reason: see
// app/twitch/sesame/modules/reply_tokens.go and reply_tokens_golden_test.go
// (regenerate with `go test ./app/twitch/sesame/modules/... -run
// TestReplyTokensGolden -modules.write-golden`).
const REPLY_TOKENS_GOLDEN_PATH = join(import.meta.dir, '../../../../app/twitch/sesame/modules/testdata/reply_tokens.golden.json');

interface ReplyTokensGoldenFile {
  note: string;
  replies: Record<string, string[]>;
}

const replyTokensGolden: ReplyTokensGoldenFile = JSON.parse(readFileSync(REPLY_TOKENS_GOLDEN_PATH, 'utf8'));

// Heads the Go resolver inventory (CommandTokenFamilies, token_catalog.go)
// has no entry for by design, so rule B does not require them in golden:
//
//   positional: generated by shape (any digit string), never enumerated as
//   one head by name.
//
//   if: parsed by pkg/tmpl's conditional grammar (parseCond) before a scope
//   ever sees a name to Own or Get, so CommandTokenFamilies has no scope to
//   walk it out of. Confirmed by reading that function: it only enumerates
//   messageFields, pureUtils and the named scope tokens below them.
const NOT_RESOLVER_OWNED = new Set(['positional', 'if']);

const isDigits = (head: string): boolean => head !== '' && /^\d+$/.test(head);

// {:m} (positional's leading slice) is the one token whose HEAD is empty by
// shape (tokenHead splits on ':', and the name before it is ""), so it needs
// its own recognizer beside isDigits rather than folding '' into headSet,
// which would also swallow a malformed example ("{}", "not a token") as
// silently covered.
const isPositionalLeadingSlice = (token: string): boolean => /^\{:\d+\}$/.test(token.trim());

/** Every name a variable answers to: its head plus its aliases. */
const namesOf = (v: VariableDef): string[] => [v.head, ...(v.aliases ?? [])];

const headSet = new Set(VARIABLES.flatMap(namesOf));

const isCovered = (token: string): boolean => {
  const head = tokenHead(token);
  return isDigits(head) || isPositionalLeadingSlice(token) || headSet.has(head);
};

const lexesToOneVar = (example: string): boolean => {
  const tokens = lex(example);
  return tokens.length === 1 && tokens[0].kind === 'var';
};

type LocaleTable = Record<string, Record<string, unknown> | undefined>;
const varsTable = (locale: typeof en): LocaleTable => ((locale as { vars?: LocaleTable }).vars ?? {});
const LOCALES: [string, LocaleTable][] = [['en', varsTable(en)], ['fr', varsTable(fr)]];

/** The copy keys one variable must carry under vars.<id>: the three every
 * variable has, plus one per form offered as its own chip (chipHint). */
const requiredCopyKeys = (v: VariableDef): string[] => [
  'name',
  'hint',
  'desc',
  ...v.forms.flatMap((form) => (form.chipHint ? [form.chipHint] : []))
];

const missingCopy = (locale: string, table: LocaleTable, v: VariableDef): string[] =>
  requiredCopyKeys(v)
    .filter((key) => !table[v.id]?.[key])
    .map((key) => `${locale}.json vars.${v.id}.${key} is missing`);

const duplicatesIn = (values: string[]): string[] =>
  values.filter((value, index) => values.indexOf(value) !== index);

/** Every reply that carries a token palette, module replies and built-in
 * commands alike, keyed the way the marketing surfaces name them. */
interface ReplySource {
  where: string;
  tokens: readonly ReplyToken[];
}

const REPLY_SOURCES: ReplySource[] = [
  ...MODULE_CATALOG.flatMap((mod) => mod.replies.map((reply) => ({ where: `${mod.id}.${reply.key}`, tokens: reply.tokens ?? [] }))),
  ...BUILTIN_COMMANDS.map((cmd) => ({ where: `builtin.${cmd.id}`, tokens: cmd.tokens ?? [] }))
];

/** Walk a dotted key through a locale tree; undefined on any miss. */
const leafAt = (tree: unknown, key: string): unknown =>
  key.split('.').reduce<unknown>((node, part) => (node && typeof node === 'object' ? (node as Record<string, unknown>)[part] : undefined), tree);

const hasText = (tree: unknown, key: string): boolean => {
  const leaf = leafAt(tree, key);
  return typeof leaf === 'string' && leaf !== '';
};

// docs/specs/variables-catalog.md phase 3, section A.3: a ReplyToken's
// hintKey is generated (see replyTokens in catalog/module-def.ts), so a
// typo in a hand-written replyKey namespace would otherwise only surface
// as a silent English fallback in the marketing builder, never a build or
// test failure.
// A ReplyToken.hintKey is always "replyVars.<namespace>.<flattenedName>.hint"
// (see hintNamespace in catalog/module-def.ts's replyTokens()), and the
// namespace itself contains a dot ("alerts.follow"), so the regex anchors on
// the fixed head and tail and keeps whatever sits between.
const replyNamespace = (hintKey: string): string | undefined => /^replyVars\.(.+)\.[^.]+\.hint$/.exec(hintKey)?.[1];

/** The Go namespace a kit reply claims, read off its first hinted token;
 * undefined for a reply with no Go counterpart yet (expected, skipped). */
const claimedNamespace = (source: ReplySource): string | undefined => {
  const hinted = source.tokens.find((token) => token.hintKey);
  return hinted ? replyNamespace(hinted.hintKey!) : undefined;
};

const sortedNames = (names: readonly string[]): string[] => [...new Set(names)].sort();

/** One reply's mismatches against the Go golden, as problem lines. */
const replyMismatches = (source: ReplySource): string[] => {
  const ns = claimedNamespace(source);
  if (!ns) return [];
  const goNames = replyTokensGolden.replies[ns];
  if (!goNames) return [`${source.where}: reply_tokens.golden.json has no "${ns}"; add it to app/twitch/sesame/modules/reply_tokens.go and regenerate`];
  const kitNames = sortedNames(source.tokens.map((token) => token.name));
  const same = JSON.stringify(kitNames) === JSON.stringify(sortedNames(goNames));
  return same ? [] : [`${source.where}: kit tokens ${JSON.stringify(kitNames)} differ from Go "${ns}" ${JSON.stringify(sortedNames(goNames))}`];
};

const unresolvedHintKeys = (locale: string, tree: unknown): string[] =>
  REPLY_SOURCES.flatMap((source) =>
    source.tokens
      .filter((token) => token.hintKey && !hasText(tree, token.hintKey))
      .map((token) => `${source.where} token "${token.name}": ${locale}.json has no ${token.hintKey}`)
  );

describe('variables parity (engine/scope/testdata/token_catalog.golden.json)', () => {
  test('A: every golden example resolves to a manifest head or alias', () => {
    const uncovered = goldenExamples.filter((example) => !isCovered(example));
    expect(uncovered, 'golden examples with no head or alias in VARIABLES; add them to variables.ts').toEqual([]);
  });

  test('B: every manifest head and alias is answered by the Go resolver', () => {
    const unanswered = VARIABLES.filter((v) => !NOT_RESOLVER_OWNED.has(v.head))
      .flatMap(namesOf)
      .filter((name) => !goldenHeads.has(name) && !goldenAliasHeads.has(name));
    expect(unanswered, 'variables.ts promises names no golden example resolves; check the scope files').toEqual([]);
  });

  test('C: every form example lexes to exactly one variable token', () => {
    const malformed = VARIABLES.flatMap((v) => v.forms.map((form) => ({ id: v.id, example: form.example })))
      .filter((form) => !lexesToOneVar(form.example))
      .map((form) => `${form.id}: ${form.example}`);
    expect(malformed, 'form examples that do not lex to exactly one {…} token').toEqual([]);
  });

  test('D: every id has name, hint, desc and chip copy in both locales', () => {
    const missing = LOCALES.flatMap(([locale, table]) => VARIABLES.flatMap((v) => missingCopy(locale, table, v)));
    expect(missing).toEqual([]);
  });

  test('E: importer targets resolve to a manifest head or alias', () => {
    const targets = [
      ...Object.values(NIGHTBOT_SIMPLE_TOKENS),
      ...Object.values(FOSSABOT_SIMPLE_TOKENS),
      ...Object.values(FOSSABOT_SUBFIELD_TOKENS)
    ];
    const uncovered = targets.filter((target) => !isCovered(target));
    expect(uncovered, 'importer targets with no head or alias in VARIABLES').toEqual([]);
  });

  test('F: ids are unique, heads and aliases are unique', () => {
    expect(duplicatesIn(VARIABLES.map((v) => v.id)), 'duplicate ids').toEqual([]);
    expect(duplicatesIn(VARIABLES.flatMap(namesOf)), 'duplicate heads or aliases').toEqual([]);
  });

  test('G: every ReplyToken.hintKey resolves in en and fr', () => {
    expect([...unresolvedHintKeys('en', en), ...unresolvedHintKeys('fr', fr)]).toEqual([]);
  });

  test('H: reply-token inventory matches app/twitch/sesame/modules/reply_tokens.go (Go golden)', () => {
    expect(REPLY_SOURCES.flatMap(replyMismatches)).toEqual([]);
    const claimed = new Set(REPLY_SOURCES.map(claimedNamespace));
    const unclaimed = Object.keys(replyTokensGolden.replies).filter((ns) => !claimed.has(ns));
    expect(unclaimed, 'Go declares reply namespaces no kit replyTokens() call names; fix web/kit/lib/catalog/*.ts').toEqual([]);
  });

  // Rule I: the timer surface handshake. golden.surfaces.timer names the
  // family IDs (golden.families[].id) app/twitch/sesame/engine/scope's
  // TimerFamilies() says a timer can resolve; forSurface('timer') is the kit
  // side of the same claim (engine/rehearsal.ts's timerOwns). Every OTHER
  // family's canonical examples (never aliases — Rule A already leaves those
  // out of the coverage contract) turn into the heads a timer must NOT
  // resolve, closing the loop so a family added to one side without the
  // other fails here instead of drifting silently.
  const timerFamilyIds = new Set(golden.surfaces.timer);
  const timerGoldenHeads = sortedNames(
    golden.families
      .filter((family) => timerFamilyIds.has(family.id))
      .flatMap((family) => family.examples)
      .map(tokenHead)
  );
  const nonTimerGoldenHeads = sortedNames(
    golden.families
      .filter((family) => !timerFamilyIds.has(family.id))
      .flatMap((family) => family.examples)
      .map(tokenHead)
  );

  test('I: forSurface(\'timer\') resolves exactly the golden surfaces.timer families', () => {
    const tsTimerHeads = sortedNames(forSurface('timer').map((v) => v.head));
    expect(tsTimerHeads, 'forSurface(\'timer\') / timerOwns must match TimerFamilies() via the golden').toEqual(timerGoldenHeads);
  });

  test('I: forSurface(\'timer\') never resolves a non-timer family\'s head', () => {
    const tsTimerHeadSet = new Set(forSurface('timer').map((v) => v.head));
    const leaked = nonTimerGoldenHeads.filter((head) => tsTimerHeadSet.has(head));
    expect(leaked, 'forSurface(\'timer\') resolves a head from a family timerChain does not mount').toEqual([]);
  });
});
