// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/app/db/loyalty/ent/counterbatch"
	"ItsBagelBot/app/db/loyalty/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CounterBatchDelete is the builder for deleting a CounterBatch entity.
type CounterBatchDelete struct {
	config
	hooks    []Hook
	mutation *CounterBatchMutation
}

// Where appends a list predicates to the CounterBatchDelete builder.
func (_d *CounterBatchDelete) Where(ps ...predicate.CounterBatch) *CounterBatchDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CounterBatchDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CounterBatchDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CounterBatchDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(counterbatch.Table, sqlgraph.NewFieldSpec(counterbatch.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CounterBatchDeleteOne is the builder for deleting a single CounterBatch entity.
type CounterBatchDeleteOne struct {
	_d *CounterBatchDelete
}

// Where appends a list predicates to the CounterBatchDelete builder.
func (_d *CounterBatchDeleteOne) Where(ps ...predicate.CounterBatch) *CounterBatchDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CounterBatchDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{counterbatch.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CounterBatchDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
