// Code generated by ent, DO NOT EDIT.

package tebexagreement

import (
	"ItsBagelBot/app/db/transactions/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint64) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldUserID, v))
}

// StoreID applies equality check predicate on the "store_id" field. It's identical to StoreIDEQ.
func StoreID(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldStoreID, v))
}

// RecurringReference applies equality check predicate on the "recurring_reference" field. It's identical to RecurringReferenceEQ.
func RecurringReference(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldRecurringReference, v))
}

// Interval applies equality check predicate on the "interval" field. It's identical to IntervalEQ.
func Interval(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldInterval, v))
}

// ProviderStatus applies equality check predicate on the "provider_status" field. It's identical to ProviderStatusEQ.
func ProviderStatus(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldProviderStatus, v))
}

// CancelRequested applies equality check predicate on the "cancel_requested" field. It's identical to CancelRequestedEQ.
func CancelRequested(v bool) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldCancelRequested, v))
}

// NextCollectionAt applies equality check predicate on the "next_collection_at" field. It's identical to NextCollectionAtEQ.
func NextCollectionAt(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldNextCollectionAt, v))
}

// PaidThroughAt applies equality check predicate on the "paid_through_at" field. It's identical to PaidThroughAtEQ.
func PaidThroughAt(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldPaidThroughAt, v))
}

// PaidThroughSource applies equality check predicate on the "paid_through_source" field. It's identical to PaidThroughSourceEQ.
func PaidThroughSource(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldPaidThroughSource, v))
}

// PausedUntil applies equality check predicate on the "paused_until" field. It's identical to PausedUntilEQ.
func PausedUntil(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldPausedUntil, v))
}

// LastSnapshotJSON applies equality check predicate on the "last_snapshot_json" field. It's identical to LastSnapshotJSONEQ.
func LastSnapshotJSON(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldLastSnapshotJSON, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldVerifiedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint64) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint64) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint64) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint64) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uint64) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uint64) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uint64) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uint64) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldUserID, v))
}

// StoreIDEQ applies the EQ predicate on the "store_id" field.
func StoreIDEQ(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldStoreID, v))
}

// StoreIDNEQ applies the NEQ predicate on the "store_id" field.
func StoreIDNEQ(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldStoreID, v))
}

// StoreIDIn applies the In predicate on the "store_id" field.
func StoreIDIn(vs ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldStoreID, vs...))
}

// StoreIDNotIn applies the NotIn predicate on the "store_id" field.
func StoreIDNotIn(vs ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldStoreID, vs...))
}

// StoreIDGT applies the GT predicate on the "store_id" field.
func StoreIDGT(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldStoreID, v))
}

// StoreIDGTE applies the GTE predicate on the "store_id" field.
func StoreIDGTE(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldStoreID, v))
}

// StoreIDLT applies the LT predicate on the "store_id" field.
func StoreIDLT(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldStoreID, v))
}

// StoreIDLTE applies the LTE predicate on the "store_id" field.
func StoreIDLTE(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldStoreID, v))
}

// StoreIDContains applies the Contains predicate on the "store_id" field.
func StoreIDContains(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldContains(FieldStoreID, v))
}

// StoreIDHasPrefix applies the HasPrefix predicate on the "store_id" field.
func StoreIDHasPrefix(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldHasPrefix(FieldStoreID, v))
}

// StoreIDHasSuffix applies the HasSuffix predicate on the "store_id" field.
func StoreIDHasSuffix(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldHasSuffix(FieldStoreID, v))
}

// StoreIDEqualFold applies the EqualFold predicate on the "store_id" field.
func StoreIDEqualFold(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEqualFold(FieldStoreID, v))
}

// StoreIDContainsFold applies the ContainsFold predicate on the "store_id" field.
func StoreIDContainsFold(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldContainsFold(FieldStoreID, v))
}

// RecurringReferenceEQ applies the EQ predicate on the "recurring_reference" field.
func RecurringReferenceEQ(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldRecurringReference, v))
}

// RecurringReferenceNEQ applies the NEQ predicate on the "recurring_reference" field.
func RecurringReferenceNEQ(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldRecurringReference, v))
}

// RecurringReferenceIn applies the In predicate on the "recurring_reference" field.
func RecurringReferenceIn(vs ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldRecurringReference, vs...))
}

// RecurringReferenceNotIn applies the NotIn predicate on the "recurring_reference" field.
func RecurringReferenceNotIn(vs ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldRecurringReference, vs...))
}

// RecurringReferenceGT applies the GT predicate on the "recurring_reference" field.
func RecurringReferenceGT(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldRecurringReference, v))
}

// RecurringReferenceGTE applies the GTE predicate on the "recurring_reference" field.
func RecurringReferenceGTE(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldRecurringReference, v))
}

// RecurringReferenceLT applies the LT predicate on the "recurring_reference" field.
func RecurringReferenceLT(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldRecurringReference, v))
}

// RecurringReferenceLTE applies the LTE predicate on the "recurring_reference" field.
func RecurringReferenceLTE(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldRecurringReference, v))
}

// RecurringReferenceContains applies the Contains predicate on the "recurring_reference" field.
func RecurringReferenceContains(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldContains(FieldRecurringReference, v))
}

// RecurringReferenceHasPrefix applies the HasPrefix predicate on the "recurring_reference" field.
func RecurringReferenceHasPrefix(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldHasPrefix(FieldRecurringReference, v))
}

// RecurringReferenceHasSuffix applies the HasSuffix predicate on the "recurring_reference" field.
func RecurringReferenceHasSuffix(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldHasSuffix(FieldRecurringReference, v))
}

// RecurringReferenceEqualFold applies the EqualFold predicate on the "recurring_reference" field.
func RecurringReferenceEqualFold(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEqualFold(FieldRecurringReference, v))
}

// RecurringReferenceContainsFold applies the ContainsFold predicate on the "recurring_reference" field.
func RecurringReferenceContainsFold(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldContainsFold(FieldRecurringReference, v))
}

// IntervalEQ applies the EQ predicate on the "interval" field.
func IntervalEQ(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldInterval, v))
}

// IntervalNEQ applies the NEQ predicate on the "interval" field.
func IntervalNEQ(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldInterval, v))
}

// IntervalIn applies the In predicate on the "interval" field.
func IntervalIn(vs ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldInterval, vs...))
}

// IntervalNotIn applies the NotIn predicate on the "interval" field.
func IntervalNotIn(vs ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldInterval, vs...))
}

// IntervalGT applies the GT predicate on the "interval" field.
func IntervalGT(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldInterval, v))
}

// IntervalGTE applies the GTE predicate on the "interval" field.
func IntervalGTE(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldInterval, v))
}

// IntervalLT applies the LT predicate on the "interval" field.
func IntervalLT(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldInterval, v))
}

// IntervalLTE applies the LTE predicate on the "interval" field.
func IntervalLTE(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldInterval, v))
}

// IntervalContains applies the Contains predicate on the "interval" field.
func IntervalContains(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldContains(FieldInterval, v))
}

// IntervalHasPrefix applies the HasPrefix predicate on the "interval" field.
func IntervalHasPrefix(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldHasPrefix(FieldInterval, v))
}

// IntervalHasSuffix applies the HasSuffix predicate on the "interval" field.
func IntervalHasSuffix(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldHasSuffix(FieldInterval, v))
}

// IntervalEqualFold applies the EqualFold predicate on the "interval" field.
func IntervalEqualFold(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEqualFold(FieldInterval, v))
}

// IntervalContainsFold applies the ContainsFold predicate on the "interval" field.
func IntervalContainsFold(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldContainsFold(FieldInterval, v))
}

// ProviderStatusEQ applies the EQ predicate on the "provider_status" field.
func ProviderStatusEQ(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldProviderStatus, v))
}

// ProviderStatusNEQ applies the NEQ predicate on the "provider_status" field.
func ProviderStatusNEQ(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldProviderStatus, v))
}

// ProviderStatusIn applies the In predicate on the "provider_status" field.
func ProviderStatusIn(vs ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldProviderStatus, vs...))
}

// ProviderStatusNotIn applies the NotIn predicate on the "provider_status" field.
func ProviderStatusNotIn(vs ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldProviderStatus, vs...))
}

// ProviderStatusGT applies the GT predicate on the "provider_status" field.
func ProviderStatusGT(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldProviderStatus, v))
}

// ProviderStatusGTE applies the GTE predicate on the "provider_status" field.
func ProviderStatusGTE(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldProviderStatus, v))
}

// ProviderStatusLT applies the LT predicate on the "provider_status" field.
func ProviderStatusLT(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldProviderStatus, v))
}

// ProviderStatusLTE applies the LTE predicate on the "provider_status" field.
func ProviderStatusLTE(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldProviderStatus, v))
}

// ProviderStatusContains applies the Contains predicate on the "provider_status" field.
func ProviderStatusContains(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldContains(FieldProviderStatus, v))
}

// ProviderStatusHasPrefix applies the HasPrefix predicate on the "provider_status" field.
func ProviderStatusHasPrefix(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldHasPrefix(FieldProviderStatus, v))
}

// ProviderStatusHasSuffix applies the HasSuffix predicate on the "provider_status" field.
func ProviderStatusHasSuffix(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldHasSuffix(FieldProviderStatus, v))
}

// ProviderStatusEqualFold applies the EqualFold predicate on the "provider_status" field.
func ProviderStatusEqualFold(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEqualFold(FieldProviderStatus, v))
}

// ProviderStatusContainsFold applies the ContainsFold predicate on the "provider_status" field.
func ProviderStatusContainsFold(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldContainsFold(FieldProviderStatus, v))
}

// CancelRequestedEQ applies the EQ predicate on the "cancel_requested" field.
func CancelRequestedEQ(v bool) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldCancelRequested, v))
}

// CancelRequestedNEQ applies the NEQ predicate on the "cancel_requested" field.
func CancelRequestedNEQ(v bool) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldCancelRequested, v))
}

// NextCollectionAtEQ applies the EQ predicate on the "next_collection_at" field.
func NextCollectionAtEQ(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldNextCollectionAt, v))
}

// NextCollectionAtNEQ applies the NEQ predicate on the "next_collection_at" field.
func NextCollectionAtNEQ(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldNextCollectionAt, v))
}

// NextCollectionAtIn applies the In predicate on the "next_collection_at" field.
func NextCollectionAtIn(vs ...time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldNextCollectionAt, vs...))
}

// NextCollectionAtNotIn applies the NotIn predicate on the "next_collection_at" field.
func NextCollectionAtNotIn(vs ...time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldNextCollectionAt, vs...))
}

// NextCollectionAtGT applies the GT predicate on the "next_collection_at" field.
func NextCollectionAtGT(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldNextCollectionAt, v))
}

// NextCollectionAtGTE applies the GTE predicate on the "next_collection_at" field.
func NextCollectionAtGTE(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldNextCollectionAt, v))
}

// NextCollectionAtLT applies the LT predicate on the "next_collection_at" field.
func NextCollectionAtLT(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldNextCollectionAt, v))
}

// NextCollectionAtLTE applies the LTE predicate on the "next_collection_at" field.
func NextCollectionAtLTE(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldNextCollectionAt, v))
}

// NextCollectionAtIsNil applies the IsNil predicate on the "next_collection_at" field.
func NextCollectionAtIsNil() predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIsNull(FieldNextCollectionAt))
}

// NextCollectionAtNotNil applies the NotNil predicate on the "next_collection_at" field.
func NextCollectionAtNotNil() predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotNull(FieldNextCollectionAt))
}

// PaidThroughAtEQ applies the EQ predicate on the "paid_through_at" field.
func PaidThroughAtEQ(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldPaidThroughAt, v))
}

// PaidThroughAtNEQ applies the NEQ predicate on the "paid_through_at" field.
func PaidThroughAtNEQ(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldPaidThroughAt, v))
}

// PaidThroughAtIn applies the In predicate on the "paid_through_at" field.
func PaidThroughAtIn(vs ...time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldPaidThroughAt, vs...))
}

// PaidThroughAtNotIn applies the NotIn predicate on the "paid_through_at" field.
func PaidThroughAtNotIn(vs ...time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldPaidThroughAt, vs...))
}

// PaidThroughAtGT applies the GT predicate on the "paid_through_at" field.
func PaidThroughAtGT(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldPaidThroughAt, v))
}

// PaidThroughAtGTE applies the GTE predicate on the "paid_through_at" field.
func PaidThroughAtGTE(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldPaidThroughAt, v))
}

// PaidThroughAtLT applies the LT predicate on the "paid_through_at" field.
func PaidThroughAtLT(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldPaidThroughAt, v))
}

// PaidThroughAtLTE applies the LTE predicate on the "paid_through_at" field.
func PaidThroughAtLTE(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldPaidThroughAt, v))
}

// PaidThroughAtIsNil applies the IsNil predicate on the "paid_through_at" field.
func PaidThroughAtIsNil() predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIsNull(FieldPaidThroughAt))
}

// PaidThroughAtNotNil applies the NotNil predicate on the "paid_through_at" field.
func PaidThroughAtNotNil() predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotNull(FieldPaidThroughAt))
}

// PaidThroughSourceEQ applies the EQ predicate on the "paid_through_source" field.
func PaidThroughSourceEQ(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldPaidThroughSource, v))
}

// PaidThroughSourceNEQ applies the NEQ predicate on the "paid_through_source" field.
func PaidThroughSourceNEQ(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldPaidThroughSource, v))
}

// PaidThroughSourceIn applies the In predicate on the "paid_through_source" field.
func PaidThroughSourceIn(vs ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldPaidThroughSource, vs...))
}

// PaidThroughSourceNotIn applies the NotIn predicate on the "paid_through_source" field.
func PaidThroughSourceNotIn(vs ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldPaidThroughSource, vs...))
}

// PaidThroughSourceGT applies the GT predicate on the "paid_through_source" field.
func PaidThroughSourceGT(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldPaidThroughSource, v))
}

// PaidThroughSourceGTE applies the GTE predicate on the "paid_through_source" field.
func PaidThroughSourceGTE(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldPaidThroughSource, v))
}

// PaidThroughSourceLT applies the LT predicate on the "paid_through_source" field.
func PaidThroughSourceLT(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldPaidThroughSource, v))
}

// PaidThroughSourceLTE applies the LTE predicate on the "paid_through_source" field.
func PaidThroughSourceLTE(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldPaidThroughSource, v))
}

// PaidThroughSourceContains applies the Contains predicate on the "paid_through_source" field.
func PaidThroughSourceContains(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldContains(FieldPaidThroughSource, v))
}

// PaidThroughSourceHasPrefix applies the HasPrefix predicate on the "paid_through_source" field.
func PaidThroughSourceHasPrefix(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldHasPrefix(FieldPaidThroughSource, v))
}

// PaidThroughSourceHasSuffix applies the HasSuffix predicate on the "paid_through_source" field.
func PaidThroughSourceHasSuffix(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldHasSuffix(FieldPaidThroughSource, v))
}

// PaidThroughSourceIsNil applies the IsNil predicate on the "paid_through_source" field.
func PaidThroughSourceIsNil() predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIsNull(FieldPaidThroughSource))
}

// PaidThroughSourceNotNil applies the NotNil predicate on the "paid_through_source" field.
func PaidThroughSourceNotNil() predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotNull(FieldPaidThroughSource))
}

// PaidThroughSourceEqualFold applies the EqualFold predicate on the "paid_through_source" field.
func PaidThroughSourceEqualFold(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEqualFold(FieldPaidThroughSource, v))
}

// PaidThroughSourceContainsFold applies the ContainsFold predicate on the "paid_through_source" field.
func PaidThroughSourceContainsFold(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldContainsFold(FieldPaidThroughSource, v))
}

// PausedUntilEQ applies the EQ predicate on the "paused_until" field.
func PausedUntilEQ(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldPausedUntil, v))
}

// PausedUntilNEQ applies the NEQ predicate on the "paused_until" field.
func PausedUntilNEQ(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldPausedUntil, v))
}

// PausedUntilIn applies the In predicate on the "paused_until" field.
func PausedUntilIn(vs ...time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldPausedUntil, vs...))
}

// PausedUntilNotIn applies the NotIn predicate on the "paused_until" field.
func PausedUntilNotIn(vs ...time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldPausedUntil, vs...))
}

// PausedUntilGT applies the GT predicate on the "paused_until" field.
func PausedUntilGT(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldPausedUntil, v))
}

// PausedUntilGTE applies the GTE predicate on the "paused_until" field.
func PausedUntilGTE(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldPausedUntil, v))
}

// PausedUntilLT applies the LT predicate on the "paused_until" field.
func PausedUntilLT(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldPausedUntil, v))
}

// PausedUntilLTE applies the LTE predicate on the "paused_until" field.
func PausedUntilLTE(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldPausedUntil, v))
}

// PausedUntilIsNil applies the IsNil predicate on the "paused_until" field.
func PausedUntilIsNil() predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIsNull(FieldPausedUntil))
}

// PausedUntilNotNil applies the NotNil predicate on the "paused_until" field.
func PausedUntilNotNil() predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotNull(FieldPausedUntil))
}

// LastSnapshotJSONEQ applies the EQ predicate on the "last_snapshot_json" field.
func LastSnapshotJSONEQ(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldLastSnapshotJSON, v))
}

// LastSnapshotJSONNEQ applies the NEQ predicate on the "last_snapshot_json" field.
func LastSnapshotJSONNEQ(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldLastSnapshotJSON, v))
}

// LastSnapshotJSONIn applies the In predicate on the "last_snapshot_json" field.
func LastSnapshotJSONIn(vs ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldLastSnapshotJSON, vs...))
}

// LastSnapshotJSONNotIn applies the NotIn predicate on the "last_snapshot_json" field.
func LastSnapshotJSONNotIn(vs ...string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldLastSnapshotJSON, vs...))
}

// LastSnapshotJSONGT applies the GT predicate on the "last_snapshot_json" field.
func LastSnapshotJSONGT(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldLastSnapshotJSON, v))
}

// LastSnapshotJSONGTE applies the GTE predicate on the "last_snapshot_json" field.
func LastSnapshotJSONGTE(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldLastSnapshotJSON, v))
}

// LastSnapshotJSONLT applies the LT predicate on the "last_snapshot_json" field.
func LastSnapshotJSONLT(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldLastSnapshotJSON, v))
}

// LastSnapshotJSONLTE applies the LTE predicate on the "last_snapshot_json" field.
func LastSnapshotJSONLTE(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldLastSnapshotJSON, v))
}

// LastSnapshotJSONContains applies the Contains predicate on the "last_snapshot_json" field.
func LastSnapshotJSONContains(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldContains(FieldLastSnapshotJSON, v))
}

// LastSnapshotJSONHasPrefix applies the HasPrefix predicate on the "last_snapshot_json" field.
func LastSnapshotJSONHasPrefix(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldHasPrefix(FieldLastSnapshotJSON, v))
}

// LastSnapshotJSONHasSuffix applies the HasSuffix predicate on the "last_snapshot_json" field.
func LastSnapshotJSONHasSuffix(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldHasSuffix(FieldLastSnapshotJSON, v))
}

// LastSnapshotJSONIsNil applies the IsNil predicate on the "last_snapshot_json" field.
func LastSnapshotJSONIsNil() predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIsNull(FieldLastSnapshotJSON))
}

// LastSnapshotJSONNotNil applies the NotNil predicate on the "last_snapshot_json" field.
func LastSnapshotJSONNotNil() predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotNull(FieldLastSnapshotJSON))
}

// LastSnapshotJSONEqualFold applies the EqualFold predicate on the "last_snapshot_json" field.
func LastSnapshotJSONEqualFold(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEqualFold(FieldLastSnapshotJSON, v))
}

// LastSnapshotJSONContainsFold applies the ContainsFold predicate on the "last_snapshot_json" field.
func LastSnapshotJSONContainsFold(v string) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldContainsFold(FieldLastSnapshotJSON, v))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldVerifiedAt, v))
}

// VerifiedAtIsNil applies the IsNil predicate on the "verified_at" field.
func VerifiedAtIsNil() predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIsNull(FieldVerifiedAt))
}

// VerifiedAtNotNil applies the NotNil predicate on the "verified_at" field.
func VerifiedAtNotNil() predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotNull(FieldVerifiedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TebexAgreement) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TebexAgreement) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TebexAgreement) predicate.TebexAgreement {
	return predicate.TebexAgreement(sql.NotPredicates(p))
}
