// Code generated by ent, DO NOT EDIT.

package tickettranscript

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tickettranscript type in the database.
	Label = "ticket_transcript"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldMessageCount holds the string denoting the message_count field in the database.
	FieldMessageCount = "message_count"
	// FieldStoredAt holds the string denoting the stored_at field in the database.
	FieldStoredAt = "stored_at"
	// EdgeTicket holds the string denoting the ticket edge name in mutations.
	EdgeTicket = "ticket"
	// Table holds the table name of the tickettranscript in the database.
	Table = "ticket_transcripts"
	// TicketTable is the table that holds the ticket relation/edge.
	TicketTable = "ticket_transcripts"
	// TicketInverseTable is the table name for the Ticket entity.
	// It exists in this package in order to avoid circular dependency with the "ticket" package.
	TicketInverseTable = "tickets"
	// TicketColumn is the table column denoting the ticket relation/edge.
	TicketColumn = "ticket_transcript"
)

// Columns holds all SQL columns for tickettranscript fields.
var Columns = []string{
	FieldID,
	FieldBody,
	FieldMessageCount,
	FieldStoredAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "ticket_transcripts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"ticket_transcript",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBody holds the default value on creation for the "body" field.
	DefaultBody string
	// DefaultMessageCount holds the default value on creation for the "message_count" field.
	DefaultMessageCount int
	// DefaultStoredAt holds the default value on creation for the "stored_at" field.
	DefaultStoredAt func() time.Time
	// UpdateDefaultStoredAt holds the default value on update for the "stored_at" field.
	UpdateDefaultStoredAt func() time.Time
)

// OrderOption defines the ordering options for the TicketTranscript queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByMessageCount orders the results by the message_count field.
func ByMessageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageCount, opts...).ToFunc()
}

// ByStoredAt orders the results by the stored_at field.
func ByStoredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoredAt, opts...).ToFunc()
}

// ByTicketField orders the results by ticket field.
func ByTicketField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTicketStep(), sql.OrderByField(field, opts...))
	}
}
func newTicketStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TicketInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, TicketTable, TicketColumn),
	)
}
