# Copyright (c) 2026 Adam Ousmer. All rights reserved.
# Proprietary. No license granted. See LICENSE.md.

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: console-dashboard-tls
  namespace: app
spec:
  secretName: console-dashboard-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - console-dashboard
    - console-dashboard.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: transactions-tls
  namespace: app
spec:
  secretName: transactions-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - transactions
    - transactions.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: commands-tls
  namespace: app
spec:
  secretName: commands-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - commands-status
    - commands-status.app
    - commands-status.app.svc
    - commands-status.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gossip-tls
  namespace: app
spec:
  secretName: gossip-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - gossip-status
    - gossip-status.app
    - gossip-status.app.svc
    - gossip-status.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loyalty-tls
  namespace: app
spec:
  secretName: loyalty-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - loyalty-status
    - loyalty-status.app
    - loyalty-status.app.svc
    - loyalty-status.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: modules-tls
  namespace: app
spec:
  secretName: modules-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - modules-status
    - modules-status.app
    - modules-status.app.svc
    - modules-status.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notifications-tls
  namespace: app
spec:
  secretName: notifications-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - notifications-status
    - notifications-status.app
    - notifications-status.app.svc
    - notifications-status.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: outgress-tls
  namespace: app
spec:
  secretName: outgress-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - outgress-status
    - outgress-status.app
    - outgress-status.app.svc
    - outgress-status.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: discord-ingress-tls
  namespace: app
spec:
  secretName: discord-ingress-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - discord-ingress-status
    - discord-ingress-status.app
    - discord-ingress-status.app.svc
    - discord-ingress-status.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: discord-engine-tls
  namespace: app
spec:
  secretName: discord-engine-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - discord-engine-status
    - discord-engine-status.app
    - discord-engine-status.app.svc
    - discord-engine-status.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: discord-outgress-tls
  namespace: app
spec:
  secretName: discord-outgress-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - discord-outgress-status
    - discord-outgress-status.app
    - discord-outgress-status.app.svc
    - discord-outgress-status.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: projector-tls
  namespace: app
spec:
  secretName: projector-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - projector-status
    - projector-status.app
    - projector-status.app.svc
    - projector-status.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sesame-tls
  namespace: app
spec:
  secretName: sesame-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - sesame-status
    - sesame-status.app
    - sesame-status.app.svc
    - sesame-status.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: users-tls
  namespace: app
spec:
  secretName: users-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - users-status
    - users-status.app
    - users-status.app.svc
    - users-status.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: twitch-ingress-tls
  namespace: app
spec:
  secretName: twitch-ingress-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - twitch-ingress-status
    - twitch-ingress-status.app
    - twitch-ingress-status.app.svc
    - twitch-ingress-status.app.svc.cluster.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: valkey-client-tls
  namespace: app
spec:
  secretName: valkey-client-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: valkey-client.app.svc.cluster.local
  dnsNames:
    - valkey-client.app.svc.cluster.local

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-client-tls
  namespace: app
spec:
  secretName: nats-client-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: fleet-intermediate-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - digital signature
    - key encipherment
    - client auth
  commonName: nats-client.app.svc.cluster.local
  dnsNames:
    - nats-client.app.svc.cluster.local
