---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: notifications
  namespace: flux-system
spec:
  image: ghcr.io/adamousmer/itsbagelbot/notifications
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: notifications
  namespace: flux-system
spec:
  digestReflectionPolicy: Always
  interval: 5m
  imageRepositoryRef:
    name: notifications
  filterTags:
    pattern: '^main-(?P<ts>[0-9]+)-[a-f0-9]{12}$'
    extract: $ts
  policy:
    numerical:
      order: asc
