---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: transactions
  namespace: flux-system
spec:
  image: ghcr.io/adamousmer/itsbagelbot/transactions
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: transactions
  namespace: flux-system
spec:
  digestReflectionPolicy: Always
  interval: 1h
  imageRepositoryRef:
    name: transactions
  filterTags:
    pattern: '^main-(?P<ts>[0-9]+)-[a-f0-9]{12}$'
    extract: $ts
  policy:
    numerical:
      order: asc
