// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/app/db/commands/ent/fetchkey"
	"ItsBagelBot/app/db/commands/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FetchKeyUpdate is the builder for updating FetchKey entities.
type FetchKeyUpdate struct {
	config
	hooks    []Hook
	mutation *FetchKeyMutation
}

// Where appends a list predicates to the FetchKeyUpdate builder.
func (_u *FetchKeyUpdate) Where(ps ...predicate.FetchKey) *FetchKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLabel sets the "label" field.
func (_u *FetchKeyUpdate) SetLabel(v string) *FetchKeyUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *FetchKeyUpdate) SetNillableLabel(v *string) *FetchKeyUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetKeyEnc sets the "key_enc" field.
func (_u *FetchKeyUpdate) SetKeyEnc(v []byte) *FetchKeyUpdate {
	_u.mutation.SetKeyEnc(v)
	return _u
}

// SetLast4 sets the "last4" field.
func (_u *FetchKeyUpdate) SetLast4(v string) *FetchKeyUpdate {
	_u.mutation.SetLast4(v)
	return _u
}

// SetNillableLast4 sets the "last4" field if the given value is not nil.
func (_u *FetchKeyUpdate) SetNillableLast4(v *string) *FetchKeyUpdate {
	if v != nil {
		_u.SetLast4(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FetchKeyUpdate) SetCreatedAt(v time.Time) *FetchKeyUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FetchKeyUpdate) SetNillableCreatedAt(v *time.Time) *FetchKeyUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FetchKeyUpdate) SetUpdatedAt(v time.Time) *FetchKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FetchKeyMutation object of the builder.
func (_u *FetchKeyUpdate) Mutation() *FetchKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FetchKeyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FetchKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FetchKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FetchKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FetchKeyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := fetchkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FetchKeyUpdate) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := fetchkey.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "FetchKey.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Last4(); ok {
		if err := fetchkey.Last4Validator(v); err != nil {
			return &ValidationError{Name: "last4", err: fmt.Errorf(`ent: validator failed for field "FetchKey.last4": %w`, err)}
		}
	}
	return nil
}

func (_u *FetchKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fetchkey.Table, fetchkey.Columns, sqlgraph.NewFieldSpec(fetchkey.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(fetchkey.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyEnc(); ok {
		_spec.SetField(fetchkey.FieldKeyEnc, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Last4(); ok {
		_spec.SetField(fetchkey.FieldLast4, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(fetchkey.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fetchkey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fetchkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FetchKeyUpdateOne is the builder for updating a single FetchKey entity.
type FetchKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FetchKeyMutation
}

// SetLabel sets the "label" field.
func (_u *FetchKeyUpdateOne) SetLabel(v string) *FetchKeyUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *FetchKeyUpdateOne) SetNillableLabel(v *string) *FetchKeyUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetKeyEnc sets the "key_enc" field.
func (_u *FetchKeyUpdateOne) SetKeyEnc(v []byte) *FetchKeyUpdateOne {
	_u.mutation.SetKeyEnc(v)
	return _u
}

// SetLast4 sets the "last4" field.
func (_u *FetchKeyUpdateOne) SetLast4(v string) *FetchKeyUpdateOne {
	_u.mutation.SetLast4(v)
	return _u
}

// SetNillableLast4 sets the "last4" field if the given value is not nil.
func (_u *FetchKeyUpdateOne) SetNillableLast4(v *string) *FetchKeyUpdateOne {
	if v != nil {
		_u.SetLast4(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *FetchKeyUpdateOne) SetCreatedAt(v time.Time) *FetchKeyUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *FetchKeyUpdateOne) SetNillableCreatedAt(v *time.Time) *FetchKeyUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FetchKeyUpdateOne) SetUpdatedAt(v time.Time) *FetchKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FetchKeyMutation object of the builder.
func (_u *FetchKeyUpdateOne) Mutation() *FetchKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the FetchKeyUpdate builder.
func (_u *FetchKeyUpdateOne) Where(ps ...predicate.FetchKey) *FetchKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FetchKeyUpdateOne) Select(field string, fields ...string) *FetchKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FetchKey entity.
func (_u *FetchKeyUpdateOne) Save(ctx context.Context) (*FetchKey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FetchKeyUpdateOne) SaveX(ctx context.Context) *FetchKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FetchKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FetchKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FetchKeyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := fetchkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FetchKeyUpdateOne) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := fetchkey.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "FetchKey.label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Last4(); ok {
		if err := fetchkey.Last4Validator(v); err != nil {
			return &ValidationError{Name: "last4", err: fmt.Errorf(`ent: validator failed for field "FetchKey.last4": %w`, err)}
		}
	}
	return nil
}

func (_u *FetchKeyUpdateOne) sqlSave(ctx context.Context) (_node *FetchKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fetchkey.Table, fetchkey.Columns, sqlgraph.NewFieldSpec(fetchkey.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FetchKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fetchkey.FieldID)
		for _, f := range fields {
			if !fetchkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fetchkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(fetchkey.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyEnc(); ok {
		_spec.SetField(fetchkey.FieldKeyEnc, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Last4(); ok {
		_spec.SetField(fetchkey.FieldLast4, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(fetchkey.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(fetchkey.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &FetchKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fetchkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
