// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/app/db/commands/ent/fetchkey"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// FetchKey is the model entity for the FetchKey schema.
type FetchKey struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uint64 `json:"user_id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// KeyEnc holds the value of the "key_enc" field.
	KeyEnc []byte `json:"-"`
	// Last4 holds the value of the "last4" field.
	Last4 string `json:"last4,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FetchKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fetchkey.FieldKeyEnc:
			values[i] = new([]byte)
		case fetchkey.FieldID, fetchkey.FieldUserID:
			values[i] = new(sql.NullInt64)
		case fetchkey.FieldLabel, fetchkey.FieldLast4:
			values[i] = new(sql.NullString)
		case fetchkey.FieldCreatedAt, fetchkey.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FetchKey fields.
func (_m *FetchKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fetchkey.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case fetchkey.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint64(value.Int64)
			}
		case fetchkey.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case fetchkey.FieldKeyEnc:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field key_enc", values[i])
			} else if value != nil {
				_m.KeyEnc = *value
			}
		case fetchkey.FieldLast4:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last4", values[i])
			} else if value.Valid {
				_m.Last4 = value.String
			}
		case fetchkey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case fetchkey.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FetchKey.
// This includes values selected through modifiers, order, etc.
func (_m *FetchKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FetchKey.
// Note that you need to call FetchKey.Unwrap() before calling this method if this FetchKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FetchKey) Update() *FetchKeyUpdateOne {
	return NewFetchKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FetchKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FetchKey) Unwrap() *FetchKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FetchKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FetchKey) String() string {
	var builder strings.Builder
	builder.WriteString("FetchKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("key_enc=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("last4=")
	builder.WriteString(_m.Last4)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FetchKeys is a parsable slice of FetchKey.
type FetchKeys []*FetchKey
