# Copyright (c) 2026 Adam Ousmer. All rights reserved.
# Proprietary. No license granted. See LICENSE.md.

---
- name: bring up private vlan
  ansible.builtin.command: "nmcli connection up vlan-private"
  changed_when: true
