// Copyright (c) 2026 Adam Ousmer. All rights reserved.
// Proprietary. No license granted. See LICENSE.md.

package tmpl

import (
	"flag"
	"os"
	"path/filepath"
	"testing"

	"ItsBagelBot/pkg/codec"
)

// writeGolden regenerates testdata/tokens.golden.json instead of asserting
// against it:
//
//	go test ./pkg/tmpl/... -run TestTokenGolden -tmpl.write-golden
//
// Regeneration is a flag and never a side effect of running the suite, per the
// repo's golden-output convention: a fixture the suite can rewrite documents
// whatever the code currently does, which is the opposite of the point. The
// file is a CROSS-LANGUAGE contract — console/shared/lib/tmpl.test.ts asserts
// the TypeScript lexer against the same rows — so a diff here means every
// surface that expands a broadcaster's template just changed.
var writeGolden = flag.Bool("tmpl.write-golden", false, "rewrite testdata/tokens.golden.json from goldenRows()")

// goldenPath is relative to the package directory, which is the working
// directory `go test` gives a test binary.
var goldenPath = filepath.Join("testdata", "tokens.golden.json")

// goldenRow is one lexer contract case: expanding Tmpl against Values must
// produce Want, byte for byte, in every language that implements this grammar.
// A key absent from Values is an unknown name (the span stays literal); a key
// present with "" is a name that resolved to nothing (the fallback renders).
type goldenRow struct {
	Name   string            `json:"name"`
	Tmpl   string            `json:"tmpl"`
	Values map[string]string `json:"values"`
	Want   string            `json:"want"`
}

// goldenFile is the committed fixture's shape. The note rides in the file so
// the next person to see a diff finds the rule without leaving the diff.
type goldenFile struct {
	Note string      `json:"note"`
	Rows []goldenRow `json:"rows"`
}

const goldenNote = "Generated by pkg/tmpl: go test ./pkg/tmpl/... -run TestTokenGolden -tmpl.write-golden. " +
	"Shared by the Go lexer (pkg/tmpl) and the TypeScript one (console/shared/lib/tmpl.ts). " +
	"A row's values map is the resolver: an absent key is an unknown name, a key mapped to \"\" is a name that resolved to nothing."

// vals builds a row's lookup table from flat key/value pairs. An empty table
// is a resolver that knows nothing, so every span in that row stays literal.
func vals(pairs ...string) map[string]string {
	out := make(map[string]string, len(pairs)/2)
	for i := 0; i+1 < len(pairs); i += 2 {
		out[pairs[i]] = pairs[i+1]
	}
	return out
}

// goldenRows builds the corpus in code (never by hand), so widening coverage
// is adding a case here and rerunning the flag rather than editing JSON.
func goldenRows() []goldenRow {
	rows := append(braceRows(), nameRows()...)
	rows = append(rows, fallbackRows()...)
	return append(rows, argumentRows()...)
}

// braceRows pin the brace grammar: what closes a span, what never opens one.
func braceRows() []goldenRow {
	user := vals("user", "bob", "title", "hi", "", "EMPTY")
	return []goldenRow{
		{"empty template", "", vals(), ""},
		{"no tokens", "plain text", user, "plain text"},
		{"one token", "{user}", user, "bob"},
		{"token in a sentence", "hi {user}!", user, "hi bob!"},
		{"unknown name stays literal", "{unknown}", user, "{unknown}"},
		{"unclosed brace is literal to the end", "{user", user, "{user"},
		{"empty braces are a name", "{}", user, "EMPTY"},
		{"a span closes at the first brace", "{{user}", user, "{{user}"},
		{"inner span already consumed", "{{user}}", user, "{{user}}"},
		{"open brace inside a span", "{a{user}", user, "{a{user}"},
		{"adjacent spans", "{user}{title}", user, "bobhi"},
		{"stray close brace before a span", "}{user}", user, "}bob"},
		{"spaces are part of the name", "{ user }", user, "{ user }"},
		{"stray close brace after a span", "{user}}", user, "bob}"},
		{"lone braces", "{}}{", user, "EMPTY}{"},
		{"literal between spans", "a{b}c{user}d", user, "a{b}cbobd"},
		{"trailing open brace", "{user}{", user, "bob{"},
	}
}

// nameRows pin the name/payload split: case folding stops at the ':'.
func nameRows() []goldenRow {
	pay := vals("user", "bob", "x:y", "XY", "x:Y", "XYUP", "choice:Hi,Yo", "Hi")
	return []goldenRow{
		{"upper-case name folds", "{USER}", pay, "bob"},
		{"mixed-case name folds", "{User}", pay, "bob"},
		{"empty payload is still a payload", "{user:}", pay, "{user:}"},
		{"empty name with a payload", "{:user}", pay, "{:user}"},
		{"lower-case payload", "{x:y}", pay, "XY"},
		{"payload keeps its case", "{x:Y}", pay, "XYUP"},
		{"name folds, payload does not", "{X:Y}", pay, "XYUP"},
		{"comma payload is one key", "{CHOICE:Hi,Yo}", pay, "Hi"},
		{"dotted names are one key", "{raider.login}", vals("raider.login", "crusty"), "crusty"},
	}
}

// fallbackRows pin the '|' grammar added in issue #884.
func fallbackRows() []goldenRow {
	arg := vals("1", "", "user", "bob", "so:Name", "", "choice:a|b", "AB")
	return []goldenRow{
		{"empty value renders the fallback", "hi {1|everyone}", arg, "hi everyone"},
		{"non-empty value ignores the fallback", "hi {user|everyone}", arg, "hi bob"},
		{"empty value with no fallback renders nothing", "hi {1}", arg, "hi "},
		{"explicit empty fallback renders nothing", "hi {1|}", arg, "hi "},
		{"fallback after a payload", "{so:Name|nobody}", arg, "nobody"},
		{"fallback does not rescue an unknown name", "{typo|rescued}", arg, "{typo|rescued}"},
		{"fallback text keeps its spaces and case", "{1|Nobody At All}", arg, "Nobody At All"},
		{"the LAST pipe splits, so a payload keeps its pipes", "{choice:a|b|c}", arg, "AB"},
		{"a payload keeping its only pipe needs no fallback", "{choice:a|b}", arg, "{choice:a|b}"},
		{"two fallbacks in one template", "{1|one} and {user|two}", arg, "one and bob"},
		{"fallback inside an unclosed brace is literal", "{1|one", arg, "{1|one"},
	}
}

// argumentRows pin the spans the argument and identity palette is written in
// (issues #883/#885) against the lexer, and the four fallback shapes issue
// #884 documents on every surface.
//
// The lexer knows no token names — a row's values map IS the palette — so
// these rows pin the SPLIT, not the palette: that {2:} keys on "2:" while {2}
// keys on "2", that a dotted name is one key, and that each of those spans
// falls back or stays literal by the same three-way rule as any other.
func argumentRows() []goldenRow {
	args := vals(
		"1", "kim", "2", "", "2:", "good luck", "3:", "",
		"touser", "", "userid", "4242", "user.login", "sam_login",
		"command", "hug", "urlfetch:x", "",
	)
	return []goldenRow{
		{"a word number is a name like any other", "hug {1}", args, "hug kim"},
		{"a trailing colon is an empty payload, not a bare name", "{2:}", args, "good luck"},
		{"the same number without the colon is a different key", "{2}", args, ""},
		{"an empty rest-of-args renders nothing", "[{3:}]", args, "[]"},
		{"a missing word falls back", "hug {2|none}", args, "hug none"},
		{"a named viewer falls back", "shout out to {touser|nobody}", args, "shout out to nobody"},
		{"an empty external value falls back", "temp is {urlfetch:x|down}", args, "temp is down"},
		{"a fallback never rescues a typo", "{unknown|x}", args, "{unknown|x}"},
		{"identity names resolve like any other", "{userid} {user.login} !{command}", args, "4242 sam_login !hug"},
	}
}

// TestTokenGolden asserts every row against the committed fixture and, with
// -tmpl.write-golden, rewrites it instead.
func TestTokenGolden(t *testing.T) {
	rows := goldenRows()
	for _, row := range rows {
		if got := Expand(row.Tmpl, rowRepl(row)); got != row.Want {
			t.Errorf("%s: Expand(%q) = %q, want %q", row.Name, row.Tmpl, got, row.Want)
		}
	}
	if *writeGolden {
		writeGoldenFile(t, rows)
		return
	}
	assertGoldenFile(t, rows)
}

// rowRepl is the row's values map as a resolver: absent means unknown.
func rowRepl(row goldenRow) func(string) (string, bool) {
	return func(key string) (string, bool) {
		val, ok := row.Values[key]
		return val, ok
	}
}

func writeGoldenFile(t *testing.T, rows []goldenRow) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
		t.Fatalf("mkdir testdata: %v", err)
	}
	if err := os.WriteFile(goldenPath, marshalGolden(t, rows), 0o644); err != nil {
		t.Fatalf("write %s: %v", goldenPath, err)
	}
	t.Logf("rewrote %s with %d rows", goldenPath, len(rows))
}

func assertGoldenFile(t *testing.T, rows []goldenRow) {
	t.Helper()
	have, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read %s (regenerate with -tmpl.write-golden): %v", goldenPath, err)
	}
	if want := marshalGolden(t, rows); string(have) != string(want) {
		t.Errorf("%s is stale. Every consumer of this grammar (Go and TypeScript) "+
			"just changed output; if that was intended, rerun with -tmpl.write-golden.", goldenPath)
	}
}

func marshalGolden(t *testing.T, rows []goldenRow) []byte {
	t.Helper()
	// codec, not encoding/json: pkg/codec is the fleet's one JSON
	// implementation (a guard test enforces it) and its SortMapKeys makes a
	// row's values map encode byte-identically across processes, which a
	// golden file depends on.
	out, err := codec.MarshalIndent(goldenFile{Note: goldenNote, Rows: rows}, "", "  ")
	if err != nil {
		t.Fatalf("marshal golden: %v", err)
	}
	return append(out, '\n')
}
