// Code generated by ent, DO NOT EDIT.

package balance

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the balance type in the database.
	Label = "balance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldViewerID holds the string denoting the viewer_id field in the database.
	FieldViewerID = "viewer_id"
	// FieldViewerLogin holds the string denoting the viewer_login field in the database.
	FieldViewerLogin = "viewer_login"
	// FieldViewerName holds the string denoting the viewer_name field in the database.
	FieldViewerName = "viewer_name"
	// FieldPoints holds the string denoting the points field in the database.
	FieldPoints = "points"
	// FieldWatchSeconds holds the string denoting the watch_seconds field in the database.
	FieldWatchSeconds = "watch_seconds"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the balance in the database.
	Table = "balances"
)

// Columns holds all SQL columns for balance fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldViewerID,
	FieldViewerLogin,
	FieldViewerName,
	FieldPoints,
	FieldWatchSeconds,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ViewerLoginValidator is a validator for the "viewer_login" field. It is called by the builders before save.
	ViewerLoginValidator func(string) error
	// ViewerNameValidator is a validator for the "viewer_name" field. It is called by the builders before save.
	ViewerNameValidator func(string) error
	// DefaultPoints holds the default value on creation for the "points" field.
	DefaultPoints int64
	// DefaultWatchSeconds holds the default value on creation for the "watch_seconds" field.
	DefaultWatchSeconds uint64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Balance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByViewerID orders the results by the viewer_id field.
func ByViewerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewerID, opts...).ToFunc()
}

// ByViewerLogin orders the results by the viewer_login field.
func ByViewerLogin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewerLogin, opts...).ToFunc()
}

// ByViewerName orders the results by the viewer_name field.
func ByViewerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldViewerName, opts...).ToFunc()
}

// ByPoints orders the results by the points field.
func ByPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoints, opts...).ToFunc()
}

// ByWatchSeconds orders the results by the watch_seconds field.
func ByWatchSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWatchSeconds, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
