// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminAuditsColumns holds the columns for the "admin_audits" table.
	AdminAuditsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "actor_id", Type: field.TypeUint64},
		{Name: "actor_login", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "target", Type: field.TypeString, Nullable: true},
		{Name: "detail", Type: field.TypeString, Nullable: true},
		{Name: "ok", Type: field.TypeBool, Default: true},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AdminAuditsTable holds the schema information for the "admin_audits" table.
	AdminAuditsTable = &schema.Table{
		Name:       "admin_audits",
		Columns:    AdminAuditsColumns,
		PrimaryKey: []*schema.Column{AdminAuditsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "adminaudit_created_at",
				Unique:  false,
				Columns: []*schema.Column{AdminAuditsColumns[8]},
			},
			{
				Name:    "adminaudit_actor_id",
				Unique:  false,
				Columns: []*schema.Column{AdminAuditsColumns[1]},
			},
		},
	}
	// AdminUsersColumns holds the columns for the "admin_users" table.
	AdminUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "login", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"moderator", "admin", "owner"}, Default: "moderator"},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "added_by", Type: field.TypeUint64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AdminUsersTable holds the schema information for the "admin_users" table.
	AdminUsersTable = &schema.Table{
		Name:       "admin_users",
		Columns:    AdminUsersColumns,
		PrimaryKey: []*schema.Column{AdminUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "adminuser_active",
				Unique:  false,
				Columns: []*schema.Column{AdminUsersColumns[4]},
			},
		},
	}
	// TokensColumns holds the columns for the "tokens" table.
	TokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"access_token", "user_token"}, Default: "access_token"},
		{Name: "token", Type: field.TypeBytes},
		{Name: "refresh_token", Type: field.TypeBytes, Nullable: true},
		{Name: "platform", Type: field.TypeEnum, Enums: []string{"twitch"}, Default: "twitch"},
		{Name: "user_tokens", Type: field.TypeUint64},
	}
	// TokensTable holds the schema information for the "tokens" table.
	TokensTable = &schema.Table{
		Name:       "tokens",
		Columns:    TokensColumns,
		PrimaryKey: []*schema.Column{TokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tokens_users_tokens",
				Columns:    []*schema.Column{TokensColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tokens_type_platform_user_tokens",
				Unique:  true,
				Columns: []*schema.Column{TokensColumns[1], TokensColumns[4], TokensColumns[5]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"free", "paid", "vip"}, Default: "free"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_id_is_active",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[0], UsersColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminAuditsTable,
		AdminUsersTable,
		TokensTable,
		UsersTable,
	}
)

func init() {
	TokensTable.ForeignKeys[0].RefTable = UsersTable
}
