// Code generated by ent, DO NOT EDIT.

package guildbinding

import (
	"ItsBagelBot/app/db/discord/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldLTE(FieldID, id))
}

// GuildID applies equality check predicate on the "guild_id" field. It's identical to GuildIDEQ.
func GuildID(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEQ(FieldGuildID, v))
}

// BroadcasterID applies equality check predicate on the "broadcaster_id" field. It's identical to BroadcasterIDEQ.
func BroadcasterID(v uint64) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEQ(FieldBroadcasterID, v))
}

// InstalledBy applies equality check predicate on the "installed_by" field. It's identical to InstalledByEQ.
func InstalledBy(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEQ(FieldInstalledBy, v))
}

// BoundAt applies equality check predicate on the "bound_at" field. It's identical to BoundAtEQ.
func BoundAt(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEQ(FieldBoundAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// GuildIDEQ applies the EQ predicate on the "guild_id" field.
func GuildIDEQ(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEQ(FieldGuildID, v))
}

// GuildIDNEQ applies the NEQ predicate on the "guild_id" field.
func GuildIDNEQ(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldNEQ(FieldGuildID, v))
}

// GuildIDIn applies the In predicate on the "guild_id" field.
func GuildIDIn(vs ...string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldIn(FieldGuildID, vs...))
}

// GuildIDNotIn applies the NotIn predicate on the "guild_id" field.
func GuildIDNotIn(vs ...string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldNotIn(FieldGuildID, vs...))
}

// GuildIDGT applies the GT predicate on the "guild_id" field.
func GuildIDGT(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldGT(FieldGuildID, v))
}

// GuildIDGTE applies the GTE predicate on the "guild_id" field.
func GuildIDGTE(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldGTE(FieldGuildID, v))
}

// GuildIDLT applies the LT predicate on the "guild_id" field.
func GuildIDLT(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldLT(FieldGuildID, v))
}

// GuildIDLTE applies the LTE predicate on the "guild_id" field.
func GuildIDLTE(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldLTE(FieldGuildID, v))
}

// GuildIDContains applies the Contains predicate on the "guild_id" field.
func GuildIDContains(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldContains(FieldGuildID, v))
}

// GuildIDHasPrefix applies the HasPrefix predicate on the "guild_id" field.
func GuildIDHasPrefix(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldHasPrefix(FieldGuildID, v))
}

// GuildIDHasSuffix applies the HasSuffix predicate on the "guild_id" field.
func GuildIDHasSuffix(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldHasSuffix(FieldGuildID, v))
}

// GuildIDEqualFold applies the EqualFold predicate on the "guild_id" field.
func GuildIDEqualFold(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEqualFold(FieldGuildID, v))
}

// GuildIDContainsFold applies the ContainsFold predicate on the "guild_id" field.
func GuildIDContainsFold(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldContainsFold(FieldGuildID, v))
}

// BroadcasterIDEQ applies the EQ predicate on the "broadcaster_id" field.
func BroadcasterIDEQ(v uint64) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEQ(FieldBroadcasterID, v))
}

// BroadcasterIDNEQ applies the NEQ predicate on the "broadcaster_id" field.
func BroadcasterIDNEQ(v uint64) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldNEQ(FieldBroadcasterID, v))
}

// BroadcasterIDIn applies the In predicate on the "broadcaster_id" field.
func BroadcasterIDIn(vs ...uint64) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldIn(FieldBroadcasterID, vs...))
}

// BroadcasterIDNotIn applies the NotIn predicate on the "broadcaster_id" field.
func BroadcasterIDNotIn(vs ...uint64) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldNotIn(FieldBroadcasterID, vs...))
}

// BroadcasterIDGT applies the GT predicate on the "broadcaster_id" field.
func BroadcasterIDGT(v uint64) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldGT(FieldBroadcasterID, v))
}

// BroadcasterIDGTE applies the GTE predicate on the "broadcaster_id" field.
func BroadcasterIDGTE(v uint64) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldGTE(FieldBroadcasterID, v))
}

// BroadcasterIDLT applies the LT predicate on the "broadcaster_id" field.
func BroadcasterIDLT(v uint64) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldLT(FieldBroadcasterID, v))
}

// BroadcasterIDLTE applies the LTE predicate on the "broadcaster_id" field.
func BroadcasterIDLTE(v uint64) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldLTE(FieldBroadcasterID, v))
}

// InstalledByEQ applies the EQ predicate on the "installed_by" field.
func InstalledByEQ(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEQ(FieldInstalledBy, v))
}

// InstalledByNEQ applies the NEQ predicate on the "installed_by" field.
func InstalledByNEQ(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldNEQ(FieldInstalledBy, v))
}

// InstalledByIn applies the In predicate on the "installed_by" field.
func InstalledByIn(vs ...string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldIn(FieldInstalledBy, vs...))
}

// InstalledByNotIn applies the NotIn predicate on the "installed_by" field.
func InstalledByNotIn(vs ...string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldNotIn(FieldInstalledBy, vs...))
}

// InstalledByGT applies the GT predicate on the "installed_by" field.
func InstalledByGT(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldGT(FieldInstalledBy, v))
}

// InstalledByGTE applies the GTE predicate on the "installed_by" field.
func InstalledByGTE(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldGTE(FieldInstalledBy, v))
}

// InstalledByLT applies the LT predicate on the "installed_by" field.
func InstalledByLT(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldLT(FieldInstalledBy, v))
}

// InstalledByLTE applies the LTE predicate on the "installed_by" field.
func InstalledByLTE(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldLTE(FieldInstalledBy, v))
}

// InstalledByContains applies the Contains predicate on the "installed_by" field.
func InstalledByContains(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldContains(FieldInstalledBy, v))
}

// InstalledByHasPrefix applies the HasPrefix predicate on the "installed_by" field.
func InstalledByHasPrefix(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldHasPrefix(FieldInstalledBy, v))
}

// InstalledByHasSuffix applies the HasSuffix predicate on the "installed_by" field.
func InstalledByHasSuffix(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldHasSuffix(FieldInstalledBy, v))
}

// InstalledByIsNil applies the IsNil predicate on the "installed_by" field.
func InstalledByIsNil() predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldIsNull(FieldInstalledBy))
}

// InstalledByNotNil applies the NotNil predicate on the "installed_by" field.
func InstalledByNotNil() predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldNotNull(FieldInstalledBy))
}

// InstalledByEqualFold applies the EqualFold predicate on the "installed_by" field.
func InstalledByEqualFold(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEqualFold(FieldInstalledBy, v))
}

// InstalledByContainsFold applies the ContainsFold predicate on the "installed_by" field.
func InstalledByContainsFold(v string) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldContainsFold(FieldInstalledBy, v))
}

// BoundAtEQ applies the EQ predicate on the "bound_at" field.
func BoundAtEQ(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEQ(FieldBoundAt, v))
}

// BoundAtNEQ applies the NEQ predicate on the "bound_at" field.
func BoundAtNEQ(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldNEQ(FieldBoundAt, v))
}

// BoundAtIn applies the In predicate on the "bound_at" field.
func BoundAtIn(vs ...time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldIn(FieldBoundAt, vs...))
}

// BoundAtNotIn applies the NotIn predicate on the "bound_at" field.
func BoundAtNotIn(vs ...time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldNotIn(FieldBoundAt, vs...))
}

// BoundAtGT applies the GT predicate on the "bound_at" field.
func BoundAtGT(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldGT(FieldBoundAt, v))
}

// BoundAtGTE applies the GTE predicate on the "bound_at" field.
func BoundAtGTE(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldGTE(FieldBoundAt, v))
}

// BoundAtLT applies the LT predicate on the "bound_at" field.
func BoundAtLT(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldLT(FieldBoundAt, v))
}

// BoundAtLTE applies the LTE predicate on the "bound_at" field.
func BoundAtLTE(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldLTE(FieldBoundAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GuildBinding {
	return predicate.GuildBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GuildBinding) predicate.GuildBinding {
	return predicate.GuildBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GuildBinding) predicate.GuildBinding {
	return predicate.GuildBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GuildBinding) predicate.GuildBinding {
	return predicate.GuildBinding(sql.NotPredicates(p))
}
