apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: node
    app.kubernetes.io/instance: valkey
    app.kubernetes.io/name: valkey
  name: valkey
  namespace: valkey
spec:
  ports:
  - name: tls-redis
    port: 6380
    protocol: TCP
    targetPort: redis-tls
  - name: tls-sentinel
    port: 26380
    protocol: TCP
    targetPort: sentinel-tls
  selector:
    app.kubernetes.io/component: node
    app.kubernetes.io/instance: valkey
    app.kubernetes.io/name: valkey
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: valkey
    app.kubernetes.io/name: valkey
  name: valkey-headless
  namespace: valkey
spec:
  ports:
  - name: redis-tls
    port: 6380
    protocol: TCP
    targetPort: redis-tls
  - name: sentinel-tls
    port: 26380
    protocol: TCP
    targetPort: sentinel-tls
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: node
    app.kubernetes.io/instance: valkey
    app.kubernetes.io/name: valkey
  type: ClusterIP
