// Copyright (c) 2026 Adam Ousmer. All rights reserved.
// Proprietary. No license granted. See LICENSE.md.

package codec

import (
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

var jsonImplementations = []string{
	"encoding/json",
	"github.com/bytedance/sonic",
	"github.com/buger/jsonparser",
	"github.com/json-iterator/go",
	"github.com/goccy/go-json",
	"github.com/segmentio/encoding/json",
	"github.com/minio/simdjson-go",
	"github.com/valyala/fastjson",
	"github.com/tidwall/gjson",
}

var skipDirs = map[string]bool{
	".git": true, ".claude": true, "node_modules": true,
	"web": true, "console": true, "docs": true, "vendor": true, "mail": true,
}

var codecDir = filepath.Join("pkg", "codec")

func TestOnlyThisPackageImportsAJSONImplementation(t *testing.T) {
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("locate module root: %v", err)
	}

	offenders, err := findJSONImports(root)
	if err != nil {
		t.Fatalf("walk %s: %v", root, err)
	}
	if len(offenders) > 0 {
		t.Fatalf("only pkg/codec may import a JSON implementation; use the codec API instead:\n\t%s",
			strings.Join(offenders, "\n\t"))
	}
}

func findJSONImports(root string) ([]string, error) {
	var offenders []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		switch {
		case err != nil:
			return err
		case d.IsDir() && skipDirs[d.Name()]:
			return filepath.SkipDir
		case d.IsDir(), !policed(root, path):
			return nil
		}
		for _, imported := range bannedImportsOf(path) {
			rel, relErr := filepath.Rel(root, path)
			if relErr != nil {
				return relErr
			}
			offenders = append(offenders, rel+" imports "+imported)
		}
		return nil
	})
	return offenders, err
}

func policed(root, path string) bool {
	if !strings.HasSuffix(path, ".go") {
		return false
	}
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return false
	}
	return filepath.Dir(rel) != codecDir
}

func bannedImportsOf(path string) []string {
	file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ImportsOnly|parser.ParseComments)
	if err != nil || isGenerated(file.Comments) {
		return nil
	}

	var found []string
	for _, imported := range file.Imports {
		importPath, unquoteErr := strconv.Unquote(imported.Path.Value)
		if unquoteErr == nil && isJSONImplementation(importPath) {
			found = append(found, importPath)
		}
	}
	return found
}

func isJSONImplementation(importPath string) bool {
	for _, banned := range jsonImplementations {
		if importPath == banned || strings.HasPrefix(importPath, banned+"/") {
			return true
		}
	}
	return false
}

func isGenerated(groups []*ast.CommentGroup) bool {
	for _, group := range groups {
		for _, comment := range group.List {
			if strings.Contains(comment.Text, "Code generated by") &&
				strings.Contains(comment.Text, "DO NOT EDIT") {
				return true
			}
		}
	}
	return false
}
