apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: valkey
  namespace: valkey
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: node
      app.kubernetes.io/name: valkey
