// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/app/loyalty/ent/counterentry"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CounterEntry is the model entity for the CounterEntry schema.
type CounterEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uint64 `json:"user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Command holds the value of the "command" field.
	Command string `json:"command,omitempty"`
	// ViewerID holds the value of the "viewer_id" field.
	ViewerID uint64 `json:"viewer_id,omitempty"`
	// ViewerLogin holds the value of the "viewer_login" field.
	ViewerLogin string `json:"viewer_login,omitempty"`
	// ViewerName holds the value of the "viewer_name" field.
	ViewerName string `json:"viewer_name,omitempty"`
	// Value holds the value of the "value" field.
	Value int64 `json:"value,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CounterEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case counterentry.FieldID, counterentry.FieldUserID, counterentry.FieldViewerID, counterentry.FieldValue:
			values[i] = new(sql.NullInt64)
		case counterentry.FieldName, counterentry.FieldCommand, counterentry.FieldViewerLogin, counterentry.FieldViewerName:
			values[i] = new(sql.NullString)
		case counterentry.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CounterEntry fields.
func (_m *CounterEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case counterentry.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case counterentry.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint64(value.Int64)
			}
		case counterentry.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case counterentry.FieldCommand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field command", values[i])
			} else if value.Valid {
				_m.Command = value.String
			}
		case counterentry.FieldViewerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field viewer_id", values[i])
			} else if value.Valid {
				_m.ViewerID = uint64(value.Int64)
			}
		case counterentry.FieldViewerLogin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field viewer_login", values[i])
			} else if value.Valid {
				_m.ViewerLogin = value.String
			}
		case counterentry.FieldViewerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field viewer_name", values[i])
			} else if value.Valid {
				_m.ViewerName = value.String
			}
		case counterentry.FieldValue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.Int64
			}
		case counterentry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the CounterEntry.
// This includes values selected through modifiers, order, etc.
func (_m *CounterEntry) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CounterEntry.
// Note that you need to call CounterEntry.Unwrap() before calling this method if this CounterEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CounterEntry) Update() *CounterEntryUpdateOne {
	return NewCounterEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CounterEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CounterEntry) Unwrap() *CounterEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CounterEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CounterEntry) String() string {
	var builder strings.Builder
	builder.WriteString("CounterEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("command=")
	builder.WriteString(_m.Command)
	builder.WriteString(", ")
	builder.WriteString("viewer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ViewerID))
	builder.WriteString(", ")
	builder.WriteString("viewer_login=")
	builder.WriteString(_m.ViewerLogin)
	builder.WriteString(", ")
	builder.WriteString("viewer_name=")
	builder.WriteString(_m.ViewerName)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", _m.Value))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CounterEntries is a parsable slice of CounterEntry.
type CounterEntries []*CounterEntry
