// Code generated by ent, DO NOT EDIT.

package fetchkey

import (
	"ItsBagelBot/app/commands/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint64) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEQ(FieldUserID, v))
}

// KeyEnc applies equality check predicate on the "key_enc" field. It's identical to KeyEncEQ.
func KeyEnc(v []byte) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEQ(FieldKeyEnc, v))
}

// Last4 applies equality check predicate on the "last4" field. It's identical to Last4EQ.
func Last4(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEQ(FieldLast4, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint64) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint64) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint64) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint64) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uint64) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uint64) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uint64) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uint64) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLTE(FieldUserID, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldContainsFold(FieldLabel, v))
}

// KeyEncEQ applies the EQ predicate on the "key_enc" field.
func KeyEncEQ(v []byte) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEQ(FieldKeyEnc, v))
}

// KeyEncNEQ applies the NEQ predicate on the "key_enc" field.
func KeyEncNEQ(v []byte) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNEQ(FieldKeyEnc, v))
}

// KeyEncIn applies the In predicate on the "key_enc" field.
func KeyEncIn(vs ...[]byte) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldIn(FieldKeyEnc, vs...))
}

// KeyEncNotIn applies the NotIn predicate on the "key_enc" field.
func KeyEncNotIn(vs ...[]byte) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNotIn(FieldKeyEnc, vs...))
}

// KeyEncGT applies the GT predicate on the "key_enc" field.
func KeyEncGT(v []byte) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGT(FieldKeyEnc, v))
}

// KeyEncGTE applies the GTE predicate on the "key_enc" field.
func KeyEncGTE(v []byte) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGTE(FieldKeyEnc, v))
}

// KeyEncLT applies the LT predicate on the "key_enc" field.
func KeyEncLT(v []byte) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLT(FieldKeyEnc, v))
}

// KeyEncLTE applies the LTE predicate on the "key_enc" field.
func KeyEncLTE(v []byte) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLTE(FieldKeyEnc, v))
}

// Last4EQ applies the EQ predicate on the "last4" field.
func Last4EQ(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEQ(FieldLast4, v))
}

// Last4NEQ applies the NEQ predicate on the "last4" field.
func Last4NEQ(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNEQ(FieldLast4, v))
}

// Last4In applies the In predicate on the "last4" field.
func Last4In(vs ...string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldIn(FieldLast4, vs...))
}

// Last4NotIn applies the NotIn predicate on the "last4" field.
func Last4NotIn(vs ...string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNotIn(FieldLast4, vs...))
}

// Last4GT applies the GT predicate on the "last4" field.
func Last4GT(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGT(FieldLast4, v))
}

// Last4GTE applies the GTE predicate on the "last4" field.
func Last4GTE(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGTE(FieldLast4, v))
}

// Last4LT applies the LT predicate on the "last4" field.
func Last4LT(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLT(FieldLast4, v))
}

// Last4LTE applies the LTE predicate on the "last4" field.
func Last4LTE(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLTE(FieldLast4, v))
}

// Last4Contains applies the Contains predicate on the "last4" field.
func Last4Contains(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldContains(FieldLast4, v))
}

// Last4HasPrefix applies the HasPrefix predicate on the "last4" field.
func Last4HasPrefix(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldHasPrefix(FieldLast4, v))
}

// Last4HasSuffix applies the HasSuffix predicate on the "last4" field.
func Last4HasSuffix(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldHasSuffix(FieldLast4, v))
}

// Last4EqualFold applies the EqualFold predicate on the "last4" field.
func Last4EqualFold(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEqualFold(FieldLast4, v))
}

// Last4ContainsFold applies the ContainsFold predicate on the "last4" field.
func Last4ContainsFold(v string) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldContainsFold(FieldLast4, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FetchKey {
	return predicate.FetchKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FetchKey) predicate.FetchKey {
	return predicate.FetchKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FetchKey) predicate.FetchKey {
	return predicate.FetchKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FetchKey) predicate.FetchKey {
	return predicate.FetchKey(sql.NotPredicates(p))
}
