// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/app/users/ent/adminuser"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminUserCreate is the builder for creating a AdminUser entity.
type AdminUserCreate struct {
	config
	mutation *AdminUserMutation
	hooks    []Hook
}

// SetLogin sets the "login" field.
func (_c *AdminUserCreate) SetLogin(v string) *AdminUserCreate {
	_c.mutation.SetLogin(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *AdminUserCreate) SetDisplayName(v string) *AdminUserCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *AdminUserCreate) SetRole(v adminuser.Role) *AdminUserCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *AdminUserCreate) SetNillableRole(v *adminuser.Role) *AdminUserCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *AdminUserCreate) SetActive(v bool) *AdminUserCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *AdminUserCreate) SetNillableActive(v *bool) *AdminUserCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetAddedBy sets the "added_by" field.
func (_c *AdminUserCreate) SetAddedBy(v uint64) *AdminUserCreate {
	_c.mutation.SetAddedBy(v)
	return _c
}

// SetNillableAddedBy sets the "added_by" field if the given value is not nil.
func (_c *AdminUserCreate) SetNillableAddedBy(v *uint64) *AdminUserCreate {
	if v != nil {
		_c.SetAddedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminUserCreate) SetCreatedAt(v time.Time) *AdminUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdminUserCreate) SetNillableCreatedAt(v *time.Time) *AdminUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AdminUserCreate) SetUpdatedAt(v time.Time) *AdminUserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AdminUserCreate) SetNillableUpdatedAt(v *time.Time) *AdminUserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AdminUserCreate) SetID(v uint64) *AdminUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AdminUserMutation object of the builder.
func (_c *AdminUserCreate) Mutation() *AdminUserMutation {
	return _c.mutation
}

// Save creates the AdminUser in the database.
func (_c *AdminUserCreate) Save(ctx context.Context) (*AdminUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminUserCreate) SaveX(ctx context.Context) *AdminUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminUserCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := adminuser.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := adminuser.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.AddedBy(); !ok {
		v := adminuser.DefaultAddedBy
		_c.mutation.SetAddedBy(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adminuser.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := adminuser.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminUserCreate) check() error {
	if _, ok := _c.mutation.Login(); !ok {
		return &ValidationError{Name: "login", err: errors.New(`ent: missing required field "AdminUser.login"`)}
	}
	if v, ok := _c.mutation.Login(); ok {
		if err := adminuser.LoginValidator(v); err != nil {
			return &ValidationError{Name: "login", err: fmt.Errorf(`ent: validator failed for field "AdminUser.login": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "AdminUser.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := adminuser.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "AdminUser.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "AdminUser.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := adminuser.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "AdminUser.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "AdminUser.active"`)}
	}
	if _, ok := _c.mutation.AddedBy(); !ok {
		return &ValidationError{Name: "added_by", err: errors.New(`ent: missing required field "AdminUser.added_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminUser.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AdminUser.updated_at"`)}
	}
	return nil
}

func (_c *AdminUserCreate) sqlSave(ctx context.Context) (*AdminUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminUserCreate) createSpec() (*AdminUser, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminuser.Table, sqlgraph.NewFieldSpec(adminuser.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Login(); ok {
		_spec.SetField(adminuser.FieldLogin, field.TypeString, value)
		_node.Login = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(adminuser.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(adminuser.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(adminuser.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.AddedBy(); ok {
		_spec.SetField(adminuser.FieldAddedBy, field.TypeUint64, value)
		_node.AddedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(adminuser.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AdminUserCreateBulk is the builder for creating many AdminUser entities in bulk.
type AdminUserCreateBulk struct {
	config
	err      error
	builders []*AdminUserCreate
}

// Save creates the AdminUser entities in the database.
func (_c *AdminUserCreateBulk) Save(ctx context.Context) ([]*AdminUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminUserCreateBulk) SaveX(ctx context.Context) []*AdminUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
