// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/app/users/ent/delegation"
	"ItsBagelBot/app/users/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// DelegationUpdate is the builder for updating Delegation entities.
type DelegationUpdate struct {
	config
	hooks    []Hook
	mutation *DelegationMutation
}

// Where appends a list predicates to the DelegationUpdate builder.
func (_u *DelegationUpdate) Where(ps ...predicate.Delegation) *DelegationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetToken sets the "token" field.
func (_u *DelegationUpdate) SetToken(v string) *DelegationUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *DelegationUpdate) SetNillableToken(v *string) *DelegationUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *DelegationUpdate) SetOwnerID(v uint64) *DelegationUpdate {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *DelegationUpdate) SetNillableOwnerID(v *uint64) *DelegationUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *DelegationUpdate) AddOwnerID(v int64) *DelegationUpdate {
	_u.mutation.AddOwnerID(v)
	return _u
}

// SetOwnerLogin sets the "owner_login" field.
func (_u *DelegationUpdate) SetOwnerLogin(v string) *DelegationUpdate {
	_u.mutation.SetOwnerLogin(v)
	return _u
}

// SetNillableOwnerLogin sets the "owner_login" field if the given value is not nil.
func (_u *DelegationUpdate) SetNillableOwnerLogin(v *string) *DelegationUpdate {
	if v != nil {
		_u.SetOwnerLogin(*v)
	}
	return _u
}

// SetSections sets the "sections" field.
func (_u *DelegationUpdate) SetSections(v []string) *DelegationUpdate {
	_u.mutation.SetSections(v)
	return _u
}

// AppendSections appends value to the "sections" field.
func (_u *DelegationUpdate) AppendSections(v []string) *DelegationUpdate {
	_u.mutation.AppendSections(v)
	return _u
}

// SetDelegateID sets the "delegate_id" field.
func (_u *DelegationUpdate) SetDelegateID(v uint64) *DelegationUpdate {
	_u.mutation.ResetDelegateID()
	_u.mutation.SetDelegateID(v)
	return _u
}

// SetNillableDelegateID sets the "delegate_id" field if the given value is not nil.
func (_u *DelegationUpdate) SetNillableDelegateID(v *uint64) *DelegationUpdate {
	if v != nil {
		_u.SetDelegateID(*v)
	}
	return _u
}

// AddDelegateID adds value to the "delegate_id" field.
func (_u *DelegationUpdate) AddDelegateID(v int64) *DelegationUpdate {
	_u.mutation.AddDelegateID(v)
	return _u
}

// ClearDelegateID clears the value of the "delegate_id" field.
func (_u *DelegationUpdate) ClearDelegateID() *DelegationUpdate {
	_u.mutation.ClearDelegateID()
	return _u
}

// SetDelegateLogin sets the "delegate_login" field.
func (_u *DelegationUpdate) SetDelegateLogin(v string) *DelegationUpdate {
	_u.mutation.SetDelegateLogin(v)
	return _u
}

// SetNillableDelegateLogin sets the "delegate_login" field if the given value is not nil.
func (_u *DelegationUpdate) SetNillableDelegateLogin(v *string) *DelegationUpdate {
	if v != nil {
		_u.SetDelegateLogin(*v)
	}
	return _u
}

// ClearDelegateLogin clears the value of the "delegate_login" field.
func (_u *DelegationUpdate) ClearDelegateLogin() *DelegationUpdate {
	_u.mutation.ClearDelegateLogin()
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *DelegationUpdate) SetConsumedAt(v time.Time) *DelegationUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *DelegationUpdate) SetNillableConsumedAt(v *time.Time) *DelegationUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *DelegationUpdate) ClearConsumedAt() *DelegationUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DelegationUpdate) SetExpiresAt(v time.Time) *DelegationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DelegationUpdate) SetNillableExpiresAt(v *time.Time) *DelegationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *DelegationUpdate) ClearExpiresAt() *DelegationUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the DelegationMutation object of the builder.
func (_u *DelegationUpdate) Mutation() *DelegationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DelegationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DelegationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DelegationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DelegationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DelegationUpdate) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := delegation.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Delegation.token": %w`, err)}
		}
	}
	return nil
}

func (_u *DelegationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(delegation.Table, delegation.Columns, sqlgraph.NewFieldSpec(delegation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(delegation.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(delegation.FieldOwnerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(delegation.FieldOwnerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.OwnerLogin(); ok {
		_spec.SetField(delegation.FieldOwnerLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sections(); ok {
		_spec.SetField(delegation.FieldSections, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSections(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, delegation.FieldSections, value)
		})
	}
	if value, ok := _u.mutation.DelegateID(); ok {
		_spec.SetField(delegation.FieldDelegateID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDelegateID(); ok {
		_spec.AddField(delegation.FieldDelegateID, field.TypeUint64, value)
	}
	if _u.mutation.DelegateIDCleared() {
		_spec.ClearField(delegation.FieldDelegateID, field.TypeUint64)
	}
	if value, ok := _u.mutation.DelegateLogin(); ok {
		_spec.SetField(delegation.FieldDelegateLogin, field.TypeString, value)
	}
	if _u.mutation.DelegateLoginCleared() {
		_spec.ClearField(delegation.FieldDelegateLogin, field.TypeString)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(delegation.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(delegation.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(delegation.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(delegation.FieldExpiresAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{delegation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DelegationUpdateOne is the builder for updating a single Delegation entity.
type DelegationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DelegationMutation
}

// SetToken sets the "token" field.
func (_u *DelegationUpdateOne) SetToken(v string) *DelegationUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *DelegationUpdateOne) SetNillableToken(v *string) *DelegationUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *DelegationUpdateOne) SetOwnerID(v uint64) *DelegationUpdateOne {
	_u.mutation.ResetOwnerID()
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *DelegationUpdateOne) SetNillableOwnerID(v *uint64) *DelegationUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// AddOwnerID adds value to the "owner_id" field.
func (_u *DelegationUpdateOne) AddOwnerID(v int64) *DelegationUpdateOne {
	_u.mutation.AddOwnerID(v)
	return _u
}

// SetOwnerLogin sets the "owner_login" field.
func (_u *DelegationUpdateOne) SetOwnerLogin(v string) *DelegationUpdateOne {
	_u.mutation.SetOwnerLogin(v)
	return _u
}

// SetNillableOwnerLogin sets the "owner_login" field if the given value is not nil.
func (_u *DelegationUpdateOne) SetNillableOwnerLogin(v *string) *DelegationUpdateOne {
	if v != nil {
		_u.SetOwnerLogin(*v)
	}
	return _u
}

// SetSections sets the "sections" field.
func (_u *DelegationUpdateOne) SetSections(v []string) *DelegationUpdateOne {
	_u.mutation.SetSections(v)
	return _u
}

// AppendSections appends value to the "sections" field.
func (_u *DelegationUpdateOne) AppendSections(v []string) *DelegationUpdateOne {
	_u.mutation.AppendSections(v)
	return _u
}

// SetDelegateID sets the "delegate_id" field.
func (_u *DelegationUpdateOne) SetDelegateID(v uint64) *DelegationUpdateOne {
	_u.mutation.ResetDelegateID()
	_u.mutation.SetDelegateID(v)
	return _u
}

// SetNillableDelegateID sets the "delegate_id" field if the given value is not nil.
func (_u *DelegationUpdateOne) SetNillableDelegateID(v *uint64) *DelegationUpdateOne {
	if v != nil {
		_u.SetDelegateID(*v)
	}
	return _u
}

// AddDelegateID adds value to the "delegate_id" field.
func (_u *DelegationUpdateOne) AddDelegateID(v int64) *DelegationUpdateOne {
	_u.mutation.AddDelegateID(v)
	return _u
}

// ClearDelegateID clears the value of the "delegate_id" field.
func (_u *DelegationUpdateOne) ClearDelegateID() *DelegationUpdateOne {
	_u.mutation.ClearDelegateID()
	return _u
}

// SetDelegateLogin sets the "delegate_login" field.
func (_u *DelegationUpdateOne) SetDelegateLogin(v string) *DelegationUpdateOne {
	_u.mutation.SetDelegateLogin(v)
	return _u
}

// SetNillableDelegateLogin sets the "delegate_login" field if the given value is not nil.
func (_u *DelegationUpdateOne) SetNillableDelegateLogin(v *string) *DelegationUpdateOne {
	if v != nil {
		_u.SetDelegateLogin(*v)
	}
	return _u
}

// ClearDelegateLogin clears the value of the "delegate_login" field.
func (_u *DelegationUpdateOne) ClearDelegateLogin() *DelegationUpdateOne {
	_u.mutation.ClearDelegateLogin()
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *DelegationUpdateOne) SetConsumedAt(v time.Time) *DelegationUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *DelegationUpdateOne) SetNillableConsumedAt(v *time.Time) *DelegationUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *DelegationUpdateOne) ClearConsumedAt() *DelegationUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DelegationUpdateOne) SetExpiresAt(v time.Time) *DelegationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DelegationUpdateOne) SetNillableExpiresAt(v *time.Time) *DelegationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *DelegationUpdateOne) ClearExpiresAt() *DelegationUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// Mutation returns the DelegationMutation object of the builder.
func (_u *DelegationUpdateOne) Mutation() *DelegationMutation {
	return _u.mutation
}

// Where appends a list predicates to the DelegationUpdate builder.
func (_u *DelegationUpdateOne) Where(ps ...predicate.Delegation) *DelegationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DelegationUpdateOne) Select(field string, fields ...string) *DelegationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Delegation entity.
func (_u *DelegationUpdateOne) Save(ctx context.Context) (*Delegation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DelegationUpdateOne) SaveX(ctx context.Context) *Delegation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DelegationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DelegationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DelegationUpdateOne) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := delegation.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Delegation.token": %w`, err)}
		}
	}
	return nil
}

func (_u *DelegationUpdateOne) sqlSave(ctx context.Context) (_node *Delegation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(delegation.Table, delegation.Columns, sqlgraph.NewFieldSpec(delegation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Delegation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, delegation.FieldID)
		for _, f := range fields {
			if !delegation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != delegation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(delegation.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(delegation.FieldOwnerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedOwnerID(); ok {
		_spec.AddField(delegation.FieldOwnerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.OwnerLogin(); ok {
		_spec.SetField(delegation.FieldOwnerLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sections(); ok {
		_spec.SetField(delegation.FieldSections, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSections(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, delegation.FieldSections, value)
		})
	}
	if value, ok := _u.mutation.DelegateID(); ok {
		_spec.SetField(delegation.FieldDelegateID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDelegateID(); ok {
		_spec.AddField(delegation.FieldDelegateID, field.TypeUint64, value)
	}
	if _u.mutation.DelegateIDCleared() {
		_spec.ClearField(delegation.FieldDelegateID, field.TypeUint64)
	}
	if value, ok := _u.mutation.DelegateLogin(); ok {
		_spec.SetField(delegation.FieldDelegateLogin, field.TypeString, value)
	}
	if _u.mutation.DelegateLoginCleared() {
		_spec.ClearField(delegation.FieldDelegateLogin, field.TypeString)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(delegation.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(delegation.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(delegation.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(delegation.FieldExpiresAt, field.TypeTime)
	}
	_node = &Delegation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{delegation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
