// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/app/users/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"-"`
	// EmailEnc holds the value of the "email_enc" field.
	EmailEnc []byte `json:"-"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// Banned holds the value of the "banned" field.
	Banned bool `json:"banned,omitempty"`
	// Status holds the value of the "status" field.
	Status user.Status `json:"status,omitempty"`
	// Locale holds the value of the "locale" field.
	Locale string `json:"locale,omitempty"`
	// SubscriptionSource holds the value of the "subscription_source" field.
	SubscriptionSource string `json:"subscription_source,omitempty"`
	// SubscriptionExpiresAt holds the value of the "subscription_expires_at" field.
	SubscriptionExpiresAt *time.Time `json:"subscription_expires_at,omitempty"`
	// SubscriptionRef holds the value of the "subscription_ref" field.
	SubscriptionRef *string `json:"subscription_ref,omitempty"`
	// SubscriptionCancelPending holds the value of the "subscription_cancel_pending" field.
	SubscriptionCancelPending bool `json:"subscription_cancel_pending,omitempty"`
	// BillingEventAt holds the value of the "billing_event_at" field.
	BillingEventAt *time.Time `json:"billing_event_at,omitempty"`
	// BillingEventID holds the value of the "billing_event_id" field.
	BillingEventID *string `json:"billing_event_id,omitempty"`
	// GiftsSent holds the value of the "gifts_sent" field.
	GiftsSent uint32 `json:"gifts_sent,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Tokens holds the value of the tokens edge.
	Tokens []*Tokens `json:"tokens,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TokensOrErr returns the Tokens value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TokensOrErr() ([]*Tokens, error) {
	if e.loadedTypes[0] {
		return e.Tokens, nil
	}
	return nil, &NotLoadedError{edge: "tokens"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldEmailEnc:
			values[i] = new([]byte)
		case user.FieldIsActive, user.FieldBanned, user.FieldSubscriptionCancelPending:
			values[i] = new(sql.NullBool)
		case user.FieldID, user.FieldGiftsSent:
			values[i] = new(sql.NullInt64)
		case user.FieldUsername, user.FieldEmail, user.FieldStatus, user.FieldLocale, user.FieldSubscriptionSource, user.FieldSubscriptionRef, user.FieldBillingEventID:
			values[i] = new(sql.NullString)
		case user.FieldSubscriptionExpiresAt, user.FieldBillingEventAt, user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldEmailEnc:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field email_enc", values[i])
			} else if value != nil {
				_m.EmailEnc = *value
			}
		case user.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case user.FieldBanned:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field banned", values[i])
			} else if value.Valid {
				_m.Banned = value.Bool
			}
		case user.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = user.Status(value.String)
			}
		case user.FieldLocale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field locale", values[i])
			} else if value.Valid {
				_m.Locale = value.String
			}
		case user.FieldSubscriptionSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_source", values[i])
			} else if value.Valid {
				_m.SubscriptionSource = value.String
			}
		case user.FieldSubscriptionExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_expires_at", values[i])
			} else if value.Valid {
				_m.SubscriptionExpiresAt = new(time.Time)
				*_m.SubscriptionExpiresAt = value.Time
			}
		case user.FieldSubscriptionRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_ref", values[i])
			} else if value.Valid {
				_m.SubscriptionRef = new(string)
				*_m.SubscriptionRef = value.String
			}
		case user.FieldSubscriptionCancelPending:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_cancel_pending", values[i])
			} else if value.Valid {
				_m.SubscriptionCancelPending = value.Bool
			}
		case user.FieldBillingEventAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field billing_event_at", values[i])
			} else if value.Valid {
				_m.BillingEventAt = new(time.Time)
				*_m.BillingEventAt = value.Time
			}
		case user.FieldBillingEventID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_event_id", values[i])
			} else if value.Valid {
				_m.BillingEventID = new(string)
				*_m.BillingEventID = value.String
			}
		case user.FieldGiftsSent:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gifts_sent", values[i])
			} else if value.Valid {
				_m.GiftsSent = uint32(value.Int64)
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTokens queries the "tokens" edge of the User entity.
func (_m *User) QueryTokens() *TokensQuery {
	return NewUserClient(_m.config).QueryTokens(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("email=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("email_enc=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("banned=")
	builder.WriteString(fmt.Sprintf("%v", _m.Banned))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("locale=")
	builder.WriteString(_m.Locale)
	builder.WriteString(", ")
	builder.WriteString("subscription_source=")
	builder.WriteString(_m.SubscriptionSource)
	builder.WriteString(", ")
	if v := _m.SubscriptionExpiresAt; v != nil {
		builder.WriteString("subscription_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SubscriptionRef; v != nil {
		builder.WriteString("subscription_ref=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("subscription_cancel_pending=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionCancelPending))
	builder.WriteString(", ")
	if v := _m.BillingEventAt; v != nil {
		builder.WriteString("billing_event_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.BillingEventID; v != nil {
		builder.WriteString("billing_event_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("gifts_sent=")
	builder.WriteString(fmt.Sprintf("%v", _m.GiftsSent))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
