// Code generated by ent, DO NOT EDIT.

package botgrants

import (
	"ItsBagelBot/internal/db/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldLTE(FieldID, id))
}

// BroadcasterUserID applies equality check predicate on the "broadcaster_user_id" field. It's identical to BroadcasterUserIDEQ.
func BroadcasterUserID(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEQ(FieldBroadcasterUserID, v))
}

// Scopes applies equality check predicate on the "scopes" field. It's identical to ScopesEQ.
func Scopes(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEQ(FieldScopes, v))
}

// RefreshTokenEnc applies equality check predicate on the "refresh_token_enc" field. It's identical to RefreshTokenEncEQ.
func RefreshTokenEnc(v []byte) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEQ(FieldRefreshTokenEnc, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEQ(FieldUpdatedAt, v))
}

// BroadcasterUserIDEQ applies the EQ predicate on the "broadcaster_user_id" field.
func BroadcasterUserIDEQ(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEQ(FieldBroadcasterUserID, v))
}

// BroadcasterUserIDNEQ applies the NEQ predicate on the "broadcaster_user_id" field.
func BroadcasterUserIDNEQ(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldNEQ(FieldBroadcasterUserID, v))
}

// BroadcasterUserIDIn applies the In predicate on the "broadcaster_user_id" field.
func BroadcasterUserIDIn(vs ...string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldIn(FieldBroadcasterUserID, vs...))
}

// BroadcasterUserIDNotIn applies the NotIn predicate on the "broadcaster_user_id" field.
func BroadcasterUserIDNotIn(vs ...string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldNotIn(FieldBroadcasterUserID, vs...))
}

// BroadcasterUserIDGT applies the GT predicate on the "broadcaster_user_id" field.
func BroadcasterUserIDGT(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldGT(FieldBroadcasterUserID, v))
}

// BroadcasterUserIDGTE applies the GTE predicate on the "broadcaster_user_id" field.
func BroadcasterUserIDGTE(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldGTE(FieldBroadcasterUserID, v))
}

// BroadcasterUserIDLT applies the LT predicate on the "broadcaster_user_id" field.
func BroadcasterUserIDLT(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldLT(FieldBroadcasterUserID, v))
}

// BroadcasterUserIDLTE applies the LTE predicate on the "broadcaster_user_id" field.
func BroadcasterUserIDLTE(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldLTE(FieldBroadcasterUserID, v))
}

// BroadcasterUserIDContains applies the Contains predicate on the "broadcaster_user_id" field.
func BroadcasterUserIDContains(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldContains(FieldBroadcasterUserID, v))
}

// BroadcasterUserIDHasPrefix applies the HasPrefix predicate on the "broadcaster_user_id" field.
func BroadcasterUserIDHasPrefix(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldHasPrefix(FieldBroadcasterUserID, v))
}

// BroadcasterUserIDHasSuffix applies the HasSuffix predicate on the "broadcaster_user_id" field.
func BroadcasterUserIDHasSuffix(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldHasSuffix(FieldBroadcasterUserID, v))
}

// BroadcasterUserIDEqualFold applies the EqualFold predicate on the "broadcaster_user_id" field.
func BroadcasterUserIDEqualFold(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEqualFold(FieldBroadcasterUserID, v))
}

// BroadcasterUserIDContainsFold applies the ContainsFold predicate on the "broadcaster_user_id" field.
func BroadcasterUserIDContainsFold(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldContainsFold(FieldBroadcasterUserID, v))
}

// ScopesEQ applies the EQ predicate on the "scopes" field.
func ScopesEQ(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEQ(FieldScopes, v))
}

// ScopesNEQ applies the NEQ predicate on the "scopes" field.
func ScopesNEQ(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldNEQ(FieldScopes, v))
}

// ScopesIn applies the In predicate on the "scopes" field.
func ScopesIn(vs ...string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldIn(FieldScopes, vs...))
}

// ScopesNotIn applies the NotIn predicate on the "scopes" field.
func ScopesNotIn(vs ...string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldNotIn(FieldScopes, vs...))
}

// ScopesGT applies the GT predicate on the "scopes" field.
func ScopesGT(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldGT(FieldScopes, v))
}

// ScopesGTE applies the GTE predicate on the "scopes" field.
func ScopesGTE(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldGTE(FieldScopes, v))
}

// ScopesLT applies the LT predicate on the "scopes" field.
func ScopesLT(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldLT(FieldScopes, v))
}

// ScopesLTE applies the LTE predicate on the "scopes" field.
func ScopesLTE(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldLTE(FieldScopes, v))
}

// ScopesContains applies the Contains predicate on the "scopes" field.
func ScopesContains(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldContains(FieldScopes, v))
}

// ScopesHasPrefix applies the HasPrefix predicate on the "scopes" field.
func ScopesHasPrefix(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldHasPrefix(FieldScopes, v))
}

// ScopesHasSuffix applies the HasSuffix predicate on the "scopes" field.
func ScopesHasSuffix(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldHasSuffix(FieldScopes, v))
}

// ScopesEqualFold applies the EqualFold predicate on the "scopes" field.
func ScopesEqualFold(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEqualFold(FieldScopes, v))
}

// ScopesContainsFold applies the ContainsFold predicate on the "scopes" field.
func ScopesContainsFold(v string) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldContainsFold(FieldScopes, v))
}

// RefreshTokenEncEQ applies the EQ predicate on the "refresh_token_enc" field.
func RefreshTokenEncEQ(v []byte) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEQ(FieldRefreshTokenEnc, v))
}

// RefreshTokenEncNEQ applies the NEQ predicate on the "refresh_token_enc" field.
func RefreshTokenEncNEQ(v []byte) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldNEQ(FieldRefreshTokenEnc, v))
}

// RefreshTokenEncIn applies the In predicate on the "refresh_token_enc" field.
func RefreshTokenEncIn(vs ...[]byte) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldIn(FieldRefreshTokenEnc, vs...))
}

// RefreshTokenEncNotIn applies the NotIn predicate on the "refresh_token_enc" field.
func RefreshTokenEncNotIn(vs ...[]byte) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldNotIn(FieldRefreshTokenEnc, vs...))
}

// RefreshTokenEncGT applies the GT predicate on the "refresh_token_enc" field.
func RefreshTokenEncGT(v []byte) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldGT(FieldRefreshTokenEnc, v))
}

// RefreshTokenEncGTE applies the GTE predicate on the "refresh_token_enc" field.
func RefreshTokenEncGTE(v []byte) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldGTE(FieldRefreshTokenEnc, v))
}

// RefreshTokenEncLT applies the LT predicate on the "refresh_token_enc" field.
func RefreshTokenEncLT(v []byte) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldLT(FieldRefreshTokenEnc, v))
}

// RefreshTokenEncLTE applies the LTE predicate on the "refresh_token_enc" field.
func RefreshTokenEncLTE(v []byte) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldLTE(FieldRefreshTokenEnc, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BotGrants {
	return predicate.BotGrants(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BotGrants) predicate.BotGrants {
	return predicate.BotGrants(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BotGrants) predicate.BotGrants {
	return predicate.BotGrants(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BotGrants) predicate.BotGrants {
	return predicate.BotGrants(sql.NotPredicates(p))
}
