// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CommandsColumns holds the columns for the "commands" table.
	CommandsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeUint64},
		{Name: "name", Type: field.TypeString},
		{Name: "aliases", Type: field.TypeJSON, Nullable: true},
		{Name: "response", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "stream_online_only", Type: field.TypeBool, Default: false},
		{Name: "perm", Type: field.TypeString, Default: "everyone"},
		{Name: "cooldown", Type: field.TypeUint, Default: 0},
		{Name: "allowed_user_id", Type: field.TypeUint64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CommandsTable holds the schema information for the "commands" table.
	CommandsTable = &schema.Table{
		Name:       "commands",
		Columns:    CommandsColumns,
		PrimaryKey: []*schema.Column{CommandsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "commands_user_id_name",
				Unique:  true,
				Columns: []*schema.Column{CommandsColumns[1], CommandsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CommandsTable,
	}
)

func init() {
}
