// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminAudit is the predicate function for adminaudit builders.
type AdminAudit func(*sql.Selector)

// AdminUser is the predicate function for adminuser builders.
type AdminUser func(*sql.Selector)

// Tokens is the predicate function for tokens builders.
type Tokens func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
