// Copyright (c) 2026 Adam Ousmer. All rights reserved.
// Proprietary. No license granted. See LICENSE.md.

package discord

import (
	"os"
	"reflect"
	"slices"
	"testing"

	"ItsBagelBot/pkg/codec"
)

// TestConfigFieldsMatchTheSharedFixture pins Config's JSON tags against
// testdata/config_fields.json, the same file console/shared reads in its own
// test.
//
// The two sides are one JSON object seen from two languages, and nothing in
// either toolchain makes them agree: a field added to Config alone compiles,
// ships, and is dropped on the floor by the dashboard's parser, which is how a
// setting silently stops saving. A field added to the console alone is worse —
// it round-trips through the page and vanishes at the first config.set.
//
// The fixture is not regenerated by this test on purpose (see the
// golden-output rule): a fixture that rewrites itself would go green on
// exactly the change it exists to catch.
func TestConfigFieldsMatchTheSharedFixture(t *testing.T) {
	want := readFieldFixture(t)
	got := configJSONTags()
	if !slices.Equal(got, want) {
		t.Fatalf("Config json tags drifted from testdata/config_fields.json\n only in Go:      %v\n only in fixture: %v",
			missing(got, want), missing(want, got))
	}
}

// configJSONTags is the sorted list of Config's JSON field names.
func configJSONTags() []string {
	rt := reflect.TypeOf(Config{})
	out := make([]string, 0, rt.NumField())
	for i := range rt.NumField() {
		tag := rt.Field(i).Tag.Get("json")
		name, _, _ := cutComma(tag)
		if name == "" || name == "-" {
			continue
		}
		out = append(out, name)
	}
	slices.Sort(out)
	return out
}

func cutComma(tag string) (string, string, bool) {
	for i := range len(tag) {
		if tag[i] == ',' {
			return tag[:i], tag[i+1:], true
		}
	}
	return tag, "", false
}

func readFieldFixture(t *testing.T) []string {
	t.Helper()
	raw, err := os.ReadFile("testdata/config_fields.json")
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var doc struct {
		Fields []string `json:"fields"`
	}
	if err := codec.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("decode fixture: %v", err)
	}
	return doc.Fields
}

func missing(from, other []string) []string {
	out := []string{}
	for _, v := range from {
		if !slices.Contains(other, v) {
			out = append(out, v)
		}
	}
	return out
}
