// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/app/notifications/ent/notification"
	"ItsBagelBot/app/notifications/ent/notificationread"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationCreate is the builder for creating a Notification entity.
type NotificationCreate struct {
	config
	mutation *NotificationMutation
	hooks    []Hook
}

// SetScope sets the "scope" field.
func (_c *NotificationCreate) SetScope(v notification.Scope) *NotificationCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetTargetUserID sets the "target_user_id" field.
func (_c *NotificationCreate) SetTargetUserID(v uint64) *NotificationCreate {
	_c.mutation.SetTargetUserID(v)
	return _c
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableTargetUserID(v *uint64) *NotificationCreate {
	if v != nil {
		_c.SetTargetUserID(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *NotificationCreate) SetTitle(v string) *NotificationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *NotificationCreate) SetBody(v string) *NotificationCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetLevel sets the "level" field.
func (_c *NotificationCreate) SetLevel(v notification.Level) *NotificationCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableLevel(v *notification.Level) *NotificationCreate {
	if v != nil {
		_c.SetLevel(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *NotificationCreate) SetCreatedBy(v uint64) *NotificationCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedByLogin sets the "created_by_login" field.
func (_c *NotificationCreate) SetCreatedByLogin(v string) *NotificationCreate {
	_c.mutation.SetCreatedByLogin(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotificationCreate) SetCreatedAt(v time.Time) *NotificationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableCreatedAt(v *time.Time) *NotificationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *NotificationCreate) SetExpiresAt(v time.Time) *NotificationCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *NotificationCreate) SetNillableExpiresAt(v *time.Time) *NotificationCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// AddReadIDs adds the "reads" edge to the NotificationRead entity by IDs.
func (_c *NotificationCreate) AddReadIDs(ids ...int) *NotificationCreate {
	_c.mutation.AddReadIDs(ids...)
	return _c
}

// AddReads adds the "reads" edges to the NotificationRead entity.
func (_c *NotificationCreate) AddReads(v ...*NotificationRead) *NotificationCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReadIDs(ids...)
}

// Mutation returns the NotificationMutation object of the builder.
func (_c *NotificationCreate) Mutation() *NotificationMutation {
	return _c.mutation
}

// Save creates the Notification in the database.
func (_c *NotificationCreate) Save(ctx context.Context) (*Notification, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotificationCreate) SaveX(ctx context.Context) *Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotificationCreate) defaults() {
	if _, ok := _c.mutation.Level(); !ok {
		v := notification.DefaultLevel
		_c.mutation.SetLevel(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := notification.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotificationCreate) check() error {
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "Notification.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := notification.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Notification.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Notification.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Notification.body"`)}
	}
	if v, ok := _c.mutation.Body(); ok {
		if err := notification.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Notification.body": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "Notification.level"`)}
	}
	if v, ok := _c.mutation.Level(); ok {
		if err := notification.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Notification.level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Notification.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedByLogin(); !ok {
		return &ValidationError{Name: "created_by_login", err: errors.New(`ent: missing required field "Notification.created_by_login"`)}
	}
	if v, ok := _c.mutation.CreatedByLogin(); ok {
		if err := notification.CreatedByLoginValidator(v); err != nil {
			return &ValidationError{Name: "created_by_login", err: fmt.Errorf(`ent: validator failed for field "Notification.created_by_login": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Notification.created_at"`)}
	}
	return nil
}

func (_c *NotificationCreate) sqlSave(ctx context.Context) (*Notification, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotificationCreate) createSpec() (*Notification, *sqlgraph.CreateSpec) {
	var (
		_node = &Notification{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notification.Table, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(notification.FieldScope, field.TypeEnum, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.TargetUserID(); ok {
		_spec.SetField(notification.FieldTargetUserID, field.TypeUint64, value)
		_node.TargetUserID = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(notification.FieldLevel, field.TypeEnum, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(notification.FieldCreatedBy, field.TypeUint64, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedByLogin(); ok {
		_spec.SetField(notification.FieldCreatedByLogin, field.TypeString, value)
		_node.CreatedByLogin = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notification.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(notification.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if nodes := _c.mutation.ReadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notification.ReadsTable,
			Columns: []string{notification.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotificationCreateBulk is the builder for creating many Notification entities in bulk.
type NotificationCreateBulk struct {
	config
	err      error
	builders []*NotificationCreate
}

// Save creates the Notification entities in the database.
func (_c *NotificationCreateBulk) Save(ctx context.Context) ([]*Notification, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Notification, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotificationCreateBulk) SaveX(ctx context.Context) []*Notification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotificationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotificationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
