// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/app/notifications/ent/notification"
	"ItsBagelBot/app/notifications/ent/notificationread"
	"ItsBagelBot/app/notifications/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetScope sets the "scope" field.
func (_u *NotificationUpdate) SetScope(v notification.Scope) *NotificationUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableScope(v *notification.Scope) *NotificationUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetTargetUserID sets the "target_user_id" field.
func (_u *NotificationUpdate) SetTargetUserID(v uint64) *NotificationUpdate {
	_u.mutation.ResetTargetUserID()
	_u.mutation.SetTargetUserID(v)
	return _u
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableTargetUserID(v *uint64) *NotificationUpdate {
	if v != nil {
		_u.SetTargetUserID(*v)
	}
	return _u
}

// AddTargetUserID adds value to the "target_user_id" field.
func (_u *NotificationUpdate) AddTargetUserID(v int64) *NotificationUpdate {
	_u.mutation.AddTargetUserID(v)
	return _u
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (_u *NotificationUpdate) ClearTargetUserID() *NotificationUpdate {
	_u.mutation.ClearTargetUserID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdate) SetTitle(v string) *NotificationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableTitle(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *NotificationUpdate) SetBody(v string) *NotificationUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableBody(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *NotificationUpdate) SetLevel(v notification.Level) *NotificationUpdate {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableLevel(v *notification.Level) *NotificationUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *NotificationUpdate) SetCreatedBy(v uint64) *NotificationUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableCreatedBy(v *uint64) *NotificationUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *NotificationUpdate) AddCreatedBy(v int64) *NotificationUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetCreatedByLogin sets the "created_by_login" field.
func (_u *NotificationUpdate) SetCreatedByLogin(v string) *NotificationUpdate {
	_u.mutation.SetCreatedByLogin(v)
	return _u
}

// SetNillableCreatedByLogin sets the "created_by_login" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableCreatedByLogin(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetCreatedByLogin(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *NotificationUpdate) SetExpiresAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableExpiresAt(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *NotificationUpdate) ClearExpiresAt() *NotificationUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// AddReadIDs adds the "reads" edge to the NotificationRead entity by IDs.
func (_u *NotificationUpdate) AddReadIDs(ids ...int) *NotificationUpdate {
	_u.mutation.AddReadIDs(ids...)
	return _u
}

// AddReads adds the "reads" edges to the NotificationRead entity.
func (_u *NotificationUpdate) AddReads(v ...*NotificationRead) *NotificationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReadIDs(ids...)
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdate) Mutation() *NotificationMutation {
	return _u.mutation
}

// ClearReads clears all "reads" edges to the NotificationRead entity.
func (_u *NotificationUpdate) ClearReads() *NotificationUpdate {
	_u.mutation.ClearReads()
	return _u
}

// RemoveReadIDs removes the "reads" edge to NotificationRead entities by IDs.
func (_u *NotificationUpdate) RemoveReadIDs(ids ...int) *NotificationUpdate {
	_u.mutation.RemoveReadIDs(ids...)
	return _u
}

// RemoveReads removes "reads" edges to NotificationRead entities.
func (_u *NotificationUpdate) RemoveReads(v ...*NotificationRead) *NotificationUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReadIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdate) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := notification.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Notification.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := notification.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Notification.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Level(); ok {
		if err := notification.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Notification.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedByLogin(); ok {
		if err := notification.CreatedByLoginValidator(v); err != nil {
			return &ValidationError{Name: "created_by_login", err: fmt.Errorf(`ent: validator failed for field "Notification.created_by_login": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(notification.FieldScope, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TargetUserID(); ok {
		_spec.SetField(notification.FieldTargetUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTargetUserID(); ok {
		_spec.AddField(notification.FieldTargetUserID, field.TypeUint64, value)
	}
	if _u.mutation.TargetUserIDCleared() {
		_spec.ClearField(notification.FieldTargetUserID, field.TypeUint64)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(notification.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(notification.FieldCreatedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(notification.FieldCreatedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.CreatedByLogin(); ok {
		_spec.SetField(notification.FieldCreatedByLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(notification.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(notification.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.ReadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notification.ReadsTable,
			Columns: []string{notification.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationread.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReadsIDs(); len(nodes) > 0 && !_u.mutation.ReadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notification.ReadsTable,
			Columns: []string{notification.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notification.ReadsTable,
			Columns: []string{notification.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetScope sets the "scope" field.
func (_u *NotificationUpdateOne) SetScope(v notification.Scope) *NotificationUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableScope(v *notification.Scope) *NotificationUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetTargetUserID sets the "target_user_id" field.
func (_u *NotificationUpdateOne) SetTargetUserID(v uint64) *NotificationUpdateOne {
	_u.mutation.ResetTargetUserID()
	_u.mutation.SetTargetUserID(v)
	return _u
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableTargetUserID(v *uint64) *NotificationUpdateOne {
	if v != nil {
		_u.SetTargetUserID(*v)
	}
	return _u
}

// AddTargetUserID adds value to the "target_user_id" field.
func (_u *NotificationUpdateOne) AddTargetUserID(v int64) *NotificationUpdateOne {
	_u.mutation.AddTargetUserID(v)
	return _u
}

// ClearTargetUserID clears the value of the "target_user_id" field.
func (_u *NotificationUpdateOne) ClearTargetUserID() *NotificationUpdateOne {
	_u.mutation.ClearTargetUserID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdateOne) SetTitle(v string) *NotificationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableTitle(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *NotificationUpdateOne) SetBody(v string) *NotificationUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableBody(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *NotificationUpdateOne) SetLevel(v notification.Level) *NotificationUpdateOne {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableLevel(v *notification.Level) *NotificationUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *NotificationUpdateOne) SetCreatedBy(v uint64) *NotificationUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableCreatedBy(v *uint64) *NotificationUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *NotificationUpdateOne) AddCreatedBy(v int64) *NotificationUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// SetCreatedByLogin sets the "created_by_login" field.
func (_u *NotificationUpdateOne) SetCreatedByLogin(v string) *NotificationUpdateOne {
	_u.mutation.SetCreatedByLogin(v)
	return _u
}

// SetNillableCreatedByLogin sets the "created_by_login" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableCreatedByLogin(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetCreatedByLogin(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *NotificationUpdateOne) SetExpiresAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableExpiresAt(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *NotificationUpdateOne) ClearExpiresAt() *NotificationUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// AddReadIDs adds the "reads" edge to the NotificationRead entity by IDs.
func (_u *NotificationUpdateOne) AddReadIDs(ids ...int) *NotificationUpdateOne {
	_u.mutation.AddReadIDs(ids...)
	return _u
}

// AddReads adds the "reads" edges to the NotificationRead entity.
func (_u *NotificationUpdateOne) AddReads(v ...*NotificationRead) *NotificationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReadIDs(ids...)
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdateOne) Mutation() *NotificationMutation {
	return _u.mutation
}

// ClearReads clears all "reads" edges to the NotificationRead entity.
func (_u *NotificationUpdateOne) ClearReads() *NotificationUpdateOne {
	_u.mutation.ClearReads()
	return _u
}

// RemoveReadIDs removes the "reads" edge to NotificationRead entities by IDs.
func (_u *NotificationUpdateOne) RemoveReadIDs(ids ...int) *NotificationUpdateOne {
	_u.mutation.RemoveReadIDs(ids...)
	return _u
}

// RemoveReads removes "reads" edges to NotificationRead entities.
func (_u *NotificationUpdateOne) RemoveReads(v ...*NotificationRead) *NotificationUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReadIDs(ids...)
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Notification entity.
func (_u *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdateOne) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := notification.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "Notification.scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Body(); ok {
		if err := notification.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Notification.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Level(); ok {
		if err := notification.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Notification.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedByLogin(); ok {
		if err := notification.CreatedByLoginValidator(v); err != nil {
			return &ValidationError{Name: "created_by_login", err: fmt.Errorf(`ent: validator failed for field "Notification.created_by_login": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(notification.FieldScope, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TargetUserID(); ok {
		_spec.SetField(notification.FieldTargetUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTargetUserID(); ok {
		_spec.AddField(notification.FieldTargetUserID, field.TypeUint64, value)
	}
	if _u.mutation.TargetUserIDCleared() {
		_spec.ClearField(notification.FieldTargetUserID, field.TypeUint64)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(notification.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(notification.FieldCreatedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(notification.FieldCreatedBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.CreatedByLogin(); ok {
		_spec.SetField(notification.FieldCreatedByLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(notification.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(notification.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.ReadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notification.ReadsTable,
			Columns: []string{notification.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationread.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReadsIDs(); len(nodes) > 0 && !_u.mutation.ReadsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notification.ReadsTable,
			Columns: []string{notification.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   notification.ReadsTable,
			Columns: []string{notification.ReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Notification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
