// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GuildBinding is the predicate function for guildbinding builders.
type GuildBinding func(*sql.Selector)

// MemberXP is the predicate function for memberxp builders.
type MemberXP func(*sql.Selector)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)

// TicketTranscript is the predicate function for tickettranscript builders.
type TicketTranscript func(*sql.Selector)
