// Copyright (c) 2026 Adam Ousmer. All rights reserved.
// Proprietary. No license granted. See LICENSE.md.

// The structure of the "modules" guide: section order and ids, block kinds,
// which mock screen or widget each block shows, and the shape of the data
// those widgets take. Every k('...') names one line of copy in
// src/content/guides/modules.<lang>.ts.
import { k, type GuideSkeleton } from '../skeleton';

const skeleton: GuideSkeleton = {
    slug: 'modules',
    meta: {
        title: k('meta.title'),
        description: k('meta.description'),
        eyebrow: k('meta.eyebrow'),
        heading: k('meta.heading'),
        lead: k('meta.lead'),
        minutes: k('meta.minutes'),
        card: {
            title: k('meta.card.title'),
            description: k('meta.card.description'),
            meta: k('meta.card.meta'),
            chips: [k('meta.card.chips.0'), k('meta.card.chips.1'), k('meta.card.chips.2'), k('meta.card.chips.3')],
        },
    },
    sections: [
        {
            id: 'page',
            heading: k('page.heading'),
            note: k('page.note'),
            blocks: [
                { kind: 'prose', html: k('page.b0.html') },
                {
                    kind: 'dash',
                    screen: 'ModulesGrid',
                    path: '/modules',
                    caption: k('page.b1.caption'),
                    notes: [
                        { n: 1, text: k('page.b1.notes.0.text') },
                        { n: 2, text: k('page.b1.notes.1.text') },
                        { n: 3, text: k('page.b1.notes.2.text') },
                        { n: 4, text: k('page.b1.notes.3.text') },
                        { n: 5, text: k('page.b1.notes.4.text') },
                        { n: 6, text: k('page.b1.notes.5.text') },
                    ],
                },
                { kind: 'prose', html: k('page.b2.html') },
                {
                    kind: 'table',
                    head: [k('page.b3.head.0'), k('page.b3.head.1'), k('page.b3.head.2')],
                    rows: [
                        [k('page.b3.rows.0.0'), k('page.b3.rows.0.1'), k('page.b3.rows.0.2')],
                        [k('page.b3.rows.1.0'), k('page.b3.rows.1.1'), k('page.b3.rows.1.2')],
                        [k('page.b3.rows.2.0'), k('page.b3.rows.2.1'), k('page.b3.rows.2.2')],
                        [k('page.b3.rows.3.0'), k('page.b3.rows.3.1'), k('page.b3.rows.3.2')],
                        [k('page.b3.rows.4.0'), k('page.b3.rows.4.1'), k('page.b3.rows.4.2')],
                        [k('page.b3.rows.5.0'), k('page.b3.rows.5.1'), k('page.b3.rows.5.2')],
                    ],
                    caption: k('page.b3.caption'),
                },
                { kind: 'callout', tone: 'note', html: k('page.b4.html') },
            ],
        },
        {
            id: 'catalog',
            heading: k('catalog.heading'),
            note: k('catalog.note'),
            blocks: [
                { kind: 'prose', html: k('catalog.b0.html') },
                {
                    kind: 'widget',
                    name: 'ModuleCatalog',
                    labels: {
                        all: k('catalog.b1.labels.all'),
                        searchLabel: k('catalog.b1.labels.searchLabel'),
                        searchPlaceholder: k('catalog.b1.labels.searchPlaceholder'),
                        countAll: k('catalog.b1.labels.countAll'),
                        countCat: k('catalog.b1.labels.countCat'),
                        countMatch: k('catalog.b1.labels.countMatch'),
                        commands: k('catalog.b1.labels.commands'),
                        needs: k('catalog.b1.labels.needs'),
                        free: k('catalog.b1.labels.free'),
                        premium: k('catalog.b1.labels.premium'),
                        empty: k('catalog.b1.labels.empty'),
                    },
                    props: {
                        categories: [
                            k('catalog.b1.props.categories.0'),
                            k('catalog.b1.props.categories.1'),
                            k('catalog.b1.props.categories.2'),
                            k('catalog.b1.props.categories.3'),
                            k('catalog.b1.props.categories.4'),
                            k('catalog.b1.props.categories.5'),
                            k('catalog.b1.props.categories.6'),
                        ],
                        modules: [
                            {
                                name: k('catalog.b1.props.modules.0.name'),
                                tagline: k('catalog.b1.props.modules.0.tagline'),
                                cat: k('catalog.b1.props.modules.0.cat'),
                                plan: k('catalog.b1.props.modules.0.plan'),
                                start: k('catalog.b1.props.modules.0.start'),
                            },
                            {
                                name: k('catalog.b1.props.modules.1.name'),
                                tagline: k('catalog.b1.props.modules.1.tagline'),
                                cat: k('catalog.b1.props.modules.1.cat'),
                                start: k('catalog.b1.props.modules.1.start'),
                            },
                            {
                                name: k('catalog.b1.props.modules.2.name'),
                                tagline: k('catalog.b1.props.modules.2.tagline'),
                                cat: k('catalog.b1.props.modules.2.cat'),
                                start: k('catalog.b1.props.modules.2.start'),
                                needs: k('catalog.b1.props.modules.2.needs'),
                                commands: k('catalog.b1.props.modules.2.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.3.name'),
                                tagline: k('catalog.b1.props.modules.3.tagline'),
                                cat: k('catalog.b1.props.modules.3.cat'),
                                start: k('catalog.b1.props.modules.3.start'),
                                commands: k('catalog.b1.props.modules.3.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.4.name'),
                                tagline: k('catalog.b1.props.modules.4.tagline'),
                                cat: k('catalog.b1.props.modules.4.cat'),
                                start: k('catalog.b1.props.modules.4.start'),
                                needs: k('catalog.b1.props.modules.4.needs'),
                            },
                            {
                                name: k('catalog.b1.props.modules.5.name'),
                                tagline: k('catalog.b1.props.modules.5.tagline'),
                                cat: k('catalog.b1.props.modules.5.cat'),
                                start: k('catalog.b1.props.modules.5.start'),
                            },
                            {
                                name: k('catalog.b1.props.modules.6.name'),
                                tagline: k('catalog.b1.props.modules.6.tagline'),
                                cat: k('catalog.b1.props.modules.6.cat'),
                                start: k('catalog.b1.props.modules.6.start'),
                                needs: k('catalog.b1.props.modules.6.needs'),
                            },
                            {
                                name: k('catalog.b1.props.modules.7.name'),
                                tagline: k('catalog.b1.props.modules.7.tagline'),
                                cat: k('catalog.b1.props.modules.7.cat'),
                                start: k('catalog.b1.props.modules.7.start'),
                                needs: k('catalog.b1.props.modules.7.needs'),
                            },
                            {
                                name: k('catalog.b1.props.modules.8.name'),
                                tagline: k('catalog.b1.props.modules.8.tagline'),
                                cat: k('catalog.b1.props.modules.8.cat'),
                                start: k('catalog.b1.props.modules.8.start'),
                                needs: k('catalog.b1.props.modules.8.needs'),
                            },
                            {
                                name: k('catalog.b1.props.modules.9.name'),
                                tagline: k('catalog.b1.props.modules.9.tagline'),
                                cat: k('catalog.b1.props.modules.9.cat'),
                                start: k('catalog.b1.props.modules.9.start'),
                                commands: k('catalog.b1.props.modules.9.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.10.name'),
                                tagline: k('catalog.b1.props.modules.10.tagline'),
                                cat: k('catalog.b1.props.modules.10.cat'),
                                start: k('catalog.b1.props.modules.10.start'),
                                commands: k('catalog.b1.props.modules.10.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.11.name'),
                                tagline: k('catalog.b1.props.modules.11.tagline'),
                                cat: k('catalog.b1.props.modules.11.cat'),
                                start: k('catalog.b1.props.modules.11.start'),
                                commands: k('catalog.b1.props.modules.11.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.12.name'),
                                tagline: k('catalog.b1.props.modules.12.tagline'),
                                cat: k('catalog.b1.props.modules.12.cat'),
                                start: k('catalog.b1.props.modules.12.start'),
                                needs: k('catalog.b1.props.modules.12.needs'),
                                commands: k('catalog.b1.props.modules.12.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.13.name'),
                                tagline: k('catalog.b1.props.modules.13.tagline'),
                                cat: k('catalog.b1.props.modules.13.cat'),
                                start: k('catalog.b1.props.modules.13.start'),
                                needs: k('catalog.b1.props.modules.13.needs'),
                                commands: k('catalog.b1.props.modules.13.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.14.name'),
                                tagline: k('catalog.b1.props.modules.14.tagline'),
                                cat: k('catalog.b1.props.modules.14.cat'),
                                start: k('catalog.b1.props.modules.14.start'),
                                commands: k('catalog.b1.props.modules.14.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.15.name'),
                                tagline: k('catalog.b1.props.modules.15.tagline'),
                                cat: k('catalog.b1.props.modules.15.cat'),
                                start: k('catalog.b1.props.modules.15.start'),
                                needs: k('catalog.b1.props.modules.15.needs'),
                                commands: k('catalog.b1.props.modules.15.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.16.name'),
                                tagline: k('catalog.b1.props.modules.16.tagline'),
                                cat: k('catalog.b1.props.modules.16.cat'),
                                start: k('catalog.b1.props.modules.16.start'),
                                needs: k('catalog.b1.props.modules.16.needs'),
                                commands: k('catalog.b1.props.modules.16.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.17.name'),
                                tagline: k('catalog.b1.props.modules.17.tagline'),
                                cat: k('catalog.b1.props.modules.17.cat'),
                                start: k('catalog.b1.props.modules.17.start'),
                                needs: k('catalog.b1.props.modules.17.needs'),
                            },
                            {
                                name: k('catalog.b1.props.modules.18.name'),
                                tagline: k('catalog.b1.props.modules.18.tagline'),
                                cat: k('catalog.b1.props.modules.18.cat'),
                                plan: k('catalog.b1.props.modules.18.plan'),
                                start: k('catalog.b1.props.modules.18.start'),
                                needs: k('catalog.b1.props.modules.18.needs'),
                            },
                            {
                                name: k('catalog.b1.props.modules.19.name'),
                                tagline: k('catalog.b1.props.modules.19.tagline'),
                                cat: k('catalog.b1.props.modules.19.cat'),
                                start: k('catalog.b1.props.modules.19.start'),
                                needs: k('catalog.b1.props.modules.19.needs'),
                                commands: k('catalog.b1.props.modules.19.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.20.name'),
                                tagline: k('catalog.b1.props.modules.20.tagline'),
                                cat: k('catalog.b1.props.modules.20.cat'),
                                start: k('catalog.b1.props.modules.20.start'),
                                needs: k('catalog.b1.props.modules.20.needs'),
                                commands: k('catalog.b1.props.modules.20.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.21.name'),
                                tagline: k('catalog.b1.props.modules.21.tagline'),
                                cat: k('catalog.b1.props.modules.21.cat'),
                                start: k('catalog.b1.props.modules.21.start'),
                                needs: k('catalog.b1.props.modules.21.needs'),
                                commands: k('catalog.b1.props.modules.21.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.22.name'),
                                tagline: k('catalog.b1.props.modules.22.tagline'),
                                cat: k('catalog.b1.props.modules.22.cat'),
                                start: k('catalog.b1.props.modules.22.start'),
                                needs: k('catalog.b1.props.modules.22.needs'),
                                commands: k('catalog.b1.props.modules.22.commands'),
                            },
                            {
                                name: k('catalog.b1.props.modules.23.name'),
                                tagline: k('catalog.b1.props.modules.23.tagline'),
                                cat: k('catalog.b1.props.modules.23.cat'),
                                start: k('catalog.b1.props.modules.23.start'),
                                needs: k('catalog.b1.props.modules.23.needs'),
                                commands: k('catalog.b1.props.modules.23.commands'),
                            },
                        ],
                    },
                },
                { kind: 'callout', tone: 'tip', html: k('catalog.b2.html') },
            ],
        },
        {
            id: 'configure',
            heading: k('configure.heading'),
            note: k('configure.note'),
            blocks: [
                { kind: 'prose', html: k('configure.b0.html') },
                {
                    kind: 'dash',
                    screen: 'ModuleConfigure',
                    path: '/modules/alerts',
                    caption: k('configure.b1.caption'),
                    notes: [
                        { n: 1, text: k('configure.b1.notes.0.text') },
                        { n: 2, text: k('configure.b1.notes.1.text') },
                        { n: 3, text: k('configure.b1.notes.2.text') },
                        { n: 4, text: k('configure.b1.notes.3.text') },
                        { n: 5, text: k('configure.b1.notes.4.text') },
                    ],
                },
                { kind: 'prose', html: k('configure.b2.html') },
                { kind: 'callout', tone: 'note', html: k('configure.b3.html') },
            ],
        },
        {
            id: 'points',
            heading: k('points.heading'),
            note: k('points.note'),
            blocks: [
                { kind: 'prose', html: k('points.b0.html') },
                {
                    kind: 'table',
                    head: [k('points.b1.head.0'), k('points.b1.head.1'), k('points.b1.head.2')],
                    rows: [
                        [k('points.b1.rows.0.0'), k('points.b1.rows.0.1'), k('points.b1.rows.0.2')],
                        [k('points.b1.rows.1.0'), k('points.b1.rows.1.1'), k('points.b1.rows.1.2')],
                    ],
                    caption: k('points.b1.caption'),
                },
                {
                    kind: 'chat',
                    title: k('points.b2.title'),
                    caption: k('points.b2.caption'),
                    lines: [
                        {
                            who: 'viewer',
                            name: k('points.b2.lines.0.name'),
                            text: k('points.b2.lines.0.text'),
                        },
                        { who: 'bot', text: k('points.b2.lines.1.text') },
                        {
                            who: 'viewer',
                            name: k('points.b2.lines.2.name'),
                            text: k('points.b2.lines.2.text'),
                        },
                        { who: 'bot', text: k('points.b2.lines.3.text') },
                        {
                            who: 'viewer',
                            name: k('points.b2.lines.4.name'),
                            text: k('points.b2.lines.4.text'),
                        },
                        { who: 'bot', text: k('points.b2.lines.5.text') },
                        {
                            who: 'viewer',
                            name: k('points.b2.lines.6.name'),
                            text: k('points.b2.lines.6.text'),
                        },
                        { who: 'bot', text: k('points.b2.lines.7.text') },
                    ],
                },
                { kind: 'callout', tone: 'warn', html: k('points.b3.html') },
            ],
        },
        {
            id: 'games',
            heading: k('games.heading'),
            note: k('games.note'),
            blocks: [
                { kind: 'prose', html: k('games.b0.html') },
                {
                    kind: 'cards',
                    columns: 3,
                    items: [
                        {
                            title: k('games.b1.items.0.title'),
                            html: k('games.b1.items.0.html'),
                            chips: [k('games.b1.items.0.chips.0')],
                        },
                        {
                            title: k('games.b1.items.1.title'),
                            html: k('games.b1.items.1.html'),
                            chips: [k('games.b1.items.1.chips.0')],
                        },
                        {
                            title: k('games.b1.items.2.title'),
                            html: k('games.b1.items.2.html'),
                            chips: [k('games.b1.items.2.chips.0')],
                        },
                        {
                            title: k('games.b1.items.3.title'),
                            html: k('games.b1.items.3.html'),
                            chips: [k('games.b1.items.3.chips.0')],
                        },
                        {
                            title: k('games.b1.items.4.title'),
                            html: k('games.b1.items.4.html'),
                            chips: [k('games.b1.items.4.chips.0')],
                        },
                    ],
                },
                { kind: 'callout', tone: 'warn', html: k('games.b2.html') },
            ],
        },
        {
            id: 'gear',
            heading: k('gear.heading'),
            note: k('gear.note'),
            blocks: [
                { kind: 'prose', html: k('gear.b0.html') },
                { kind: 'prose', html: k('gear.b1.html') },
                { kind: 'callout', tone: 'warn', html: k('gear.b2.html') },
                { kind: 'prose', html: k('gear.b3.html') },
            ],
        },
        {
            id: 'builtins',
            heading: k('builtins.heading'),
            note: k('builtins.note'),
            blocks: [
                { kind: 'prose', html: k('builtins.b0.html') },
                {
                    kind: 'table',
                    head: [k('builtins.b1.head.0'), k('builtins.b1.head.1'), k('builtins.b1.head.2')],
                    rows: [
                        [k('builtins.b1.rows.0.0'), k('builtins.b1.rows.0.1'), k('builtins.b1.rows.0.2')],
                        [k('builtins.b1.rows.1.0'), k('builtins.b1.rows.1.1'), k('builtins.b1.rows.1.2')],
                        [k('builtins.b1.rows.2.0'), k('builtins.b1.rows.2.1'), k('builtins.b1.rows.2.2')],
                        [k('builtins.b1.rows.3.0'), k('builtins.b1.rows.3.1'), k('builtins.b1.rows.3.2')],
                        [k('builtins.b1.rows.4.0'), k('builtins.b1.rows.4.1'), k('builtins.b1.rows.4.2')],
                        [k('builtins.b1.rows.5.0'), k('builtins.b1.rows.5.1'), k('builtins.b1.rows.5.2')],
                        [k('builtins.b1.rows.6.0'), k('builtins.b1.rows.6.1'), k('builtins.b1.rows.6.2')],
                        [k('builtins.b1.rows.7.0'), k('builtins.b1.rows.7.1'), k('builtins.b1.rows.7.2')],
                        [k('builtins.b1.rows.8.0'), k('builtins.b1.rows.8.1'), k('builtins.b1.rows.8.2')],
                    ],
                    caption: k('builtins.b1.caption'),
                },
                { kind: 'prose', html: k('builtins.b2.html') },
                { kind: 'callout', tone: 'note', html: k('builtins.b3.html') },
            ],
        },
    ],
};

export default skeleton;
