// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/app/db/discord/ent/guildbinding"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GuildBinding is the model entity for the GuildBinding schema.
type GuildBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// GuildID holds the value of the "guild_id" field.
	GuildID string `json:"guild_id,omitempty"`
	// BroadcasterID holds the value of the "broadcaster_id" field.
	BroadcasterID uint64 `json:"broadcaster_id,omitempty"`
	// InstalledBy holds the value of the "installed_by" field.
	InstalledBy string `json:"installed_by,omitempty"`
	// BoundAt holds the value of the "bound_at" field.
	BoundAt time.Time `json:"bound_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GuildBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case guildbinding.FieldID, guildbinding.FieldBroadcasterID:
			values[i] = new(sql.NullInt64)
		case guildbinding.FieldGuildID, guildbinding.FieldInstalledBy:
			values[i] = new(sql.NullString)
		case guildbinding.FieldBoundAt, guildbinding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GuildBinding fields.
func (_m *GuildBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case guildbinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case guildbinding.FieldGuildID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field guild_id", values[i])
			} else if value.Valid {
				_m.GuildID = value.String
			}
		case guildbinding.FieldBroadcasterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field broadcaster_id", values[i])
			} else if value.Valid {
				_m.BroadcasterID = uint64(value.Int64)
			}
		case guildbinding.FieldInstalledBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field installed_by", values[i])
			} else if value.Valid {
				_m.InstalledBy = value.String
			}
		case guildbinding.FieldBoundAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field bound_at", values[i])
			} else if value.Valid {
				_m.BoundAt = value.Time
			}
		case guildbinding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GuildBinding.
// This includes values selected through modifiers, order, etc.
func (_m *GuildBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GuildBinding.
// Note that you need to call GuildBinding.Unwrap() before calling this method if this GuildBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GuildBinding) Update() *GuildBindingUpdateOne {
	return NewGuildBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GuildBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GuildBinding) Unwrap() *GuildBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GuildBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GuildBinding) String() string {
	var builder strings.Builder
	builder.WriteString("GuildBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("guild_id=")
	builder.WriteString(_m.GuildID)
	builder.WriteString(", ")
	builder.WriteString("broadcaster_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BroadcasterID))
	builder.WriteString(", ")
	builder.WriteString("installed_by=")
	builder.WriteString(_m.InstalledBy)
	builder.WriteString(", ")
	builder.WriteString("bound_at=")
	builder.WriteString(_m.BoundAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GuildBindings is a parsable slice of GuildBinding.
type GuildBindings []*GuildBinding
