// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/app/db/transactions/ent/billingoperation"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BillingOperationCreate is the builder for creating a BillingOperation entity.
type BillingOperationCreate struct {
	config
	mutation *BillingOperationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAwardID sets the "award_id" field.
func (_c *BillingOperationCreate) SetAwardID(v string) *BillingOperationCreate {
	_c.mutation.SetAwardID(v)
	return _c
}

// SetAgreementID sets the "agreement_id" field.
func (_c *BillingOperationCreate) SetAgreementID(v string) *BillingOperationCreate {
	_c.mutation.SetAgreementID(v)
	return _c
}

// SetRecurringReference sets the "recurring_reference" field.
func (_c *BillingOperationCreate) SetRecurringReference(v string) *BillingOperationCreate {
	_c.mutation.SetRecurringReference(v)
	return _c
}

// SetRequestedStart sets the "requested_start" field.
func (_c *BillingOperationCreate) SetRequestedStart(v time.Time) *BillingOperationCreate {
	_c.mutation.SetRequestedStart(v)
	return _c
}

// SetRequestedEnd sets the "requested_end" field.
func (_c *BillingOperationCreate) SetRequestedEnd(v time.Time) *BillingOperationCreate {
	_c.mutation.SetRequestedEnd(v)
	return _c
}

// SetState sets the "state" field.
func (_c *BillingOperationCreate) SetState(v string) *BillingOperationCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *BillingOperationCreate) SetNillableState(v *string) *BillingOperationCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetBeforeSnapshotJSON sets the "before_snapshot_json" field.
func (_c *BillingOperationCreate) SetBeforeSnapshotJSON(v string) *BillingOperationCreate {
	_c.mutation.SetBeforeSnapshotJSON(v)
	return _c
}

// SetNillableBeforeSnapshotJSON sets the "before_snapshot_json" field if the given value is not nil.
func (_c *BillingOperationCreate) SetNillableBeforeSnapshotJSON(v *string) *BillingOperationCreate {
	if v != nil {
		_c.SetBeforeSnapshotJSON(*v)
	}
	return _c
}

// SetAfterSnapshotJSON sets the "after_snapshot_json" field.
func (_c *BillingOperationCreate) SetAfterSnapshotJSON(v string) *BillingOperationCreate {
	_c.mutation.SetAfterSnapshotJSON(v)
	return _c
}

// SetNillableAfterSnapshotJSON sets the "after_snapshot_json" field if the given value is not nil.
func (_c *BillingOperationCreate) SetNillableAfterSnapshotJSON(v *string) *BillingOperationCreate {
	if v != nil {
		_c.SetAfterSnapshotJSON(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *BillingOperationCreate) SetAttempts(v uint64) *BillingOperationCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *BillingOperationCreate) SetNillableAttempts(v *uint64) *BillingOperationCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *BillingOperationCreate) SetLastError(v string) *BillingOperationCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *BillingOperationCreate) SetNillableLastError(v *string) *BillingOperationCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetLeaseUntil sets the "lease_until" field.
func (_c *BillingOperationCreate) SetLeaseUntil(v time.Time) *BillingOperationCreate {
	_c.mutation.SetLeaseUntil(v)
	return _c
}

// SetNillableLeaseUntil sets the "lease_until" field if the given value is not nil.
func (_c *BillingOperationCreate) SetNillableLeaseUntil(v *time.Time) *BillingOperationCreate {
	if v != nil {
		_c.SetLeaseUntil(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *BillingOperationCreate) SetVersion(v uint64) *BillingOperationCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *BillingOperationCreate) SetNillableVersion(v *uint64) *BillingOperationCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetVerifiedAt sets the "verified_at" field.
func (_c *BillingOperationCreate) SetVerifiedAt(v time.Time) *BillingOperationCreate {
	_c.mutation.SetVerifiedAt(v)
	return _c
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_c *BillingOperationCreate) SetNillableVerifiedAt(v *time.Time) *BillingOperationCreate {
	if v != nil {
		_c.SetVerifiedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BillingOperationCreate) SetCreatedAt(v time.Time) *BillingOperationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BillingOperationCreate) SetNillableCreatedAt(v *time.Time) *BillingOperationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BillingOperationCreate) SetUpdatedAt(v time.Time) *BillingOperationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BillingOperationCreate) SetNillableUpdatedAt(v *time.Time) *BillingOperationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BillingOperationCreate) SetID(v string) *BillingOperationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BillingOperationMutation object of the builder.
func (_c *BillingOperationCreate) Mutation() *BillingOperationMutation {
	return _c.mutation
}

// Save creates the BillingOperation in the database.
func (_c *BillingOperationCreate) Save(ctx context.Context) (*BillingOperation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BillingOperationCreate) SaveX(ctx context.Context) *BillingOperation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingOperationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingOperationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BillingOperationCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := billingoperation.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := billingoperation.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := billingoperation.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := billingoperation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := billingoperation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BillingOperationCreate) check() error {
	if _, ok := _c.mutation.AwardID(); !ok {
		return &ValidationError{Name: "award_id", err: errors.New(`ent: missing required field "BillingOperation.award_id"`)}
	}
	if v, ok := _c.mutation.AwardID(); ok {
		if err := billingoperation.AwardIDValidator(v); err != nil {
			return &ValidationError{Name: "award_id", err: fmt.Errorf(`ent: validator failed for field "BillingOperation.award_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AgreementID(); !ok {
		return &ValidationError{Name: "agreement_id", err: errors.New(`ent: missing required field "BillingOperation.agreement_id"`)}
	}
	if v, ok := _c.mutation.AgreementID(); ok {
		if err := billingoperation.AgreementIDValidator(v); err != nil {
			return &ValidationError{Name: "agreement_id", err: fmt.Errorf(`ent: validator failed for field "BillingOperation.agreement_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecurringReference(); !ok {
		return &ValidationError{Name: "recurring_reference", err: errors.New(`ent: missing required field "BillingOperation.recurring_reference"`)}
	}
	if v, ok := _c.mutation.RecurringReference(); ok {
		if err := billingoperation.RecurringReferenceValidator(v); err != nil {
			return &ValidationError{Name: "recurring_reference", err: fmt.Errorf(`ent: validator failed for field "BillingOperation.recurring_reference": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestedStart(); !ok {
		return &ValidationError{Name: "requested_start", err: errors.New(`ent: missing required field "BillingOperation.requested_start"`)}
	}
	if _, ok := _c.mutation.RequestedEnd(); !ok {
		return &ValidationError{Name: "requested_end", err: errors.New(`ent: missing required field "BillingOperation.requested_end"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "BillingOperation.state"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "BillingOperation.attempts"`)}
	}
	if v, ok := _c.mutation.LastError(); ok {
		if err := billingoperation.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "BillingOperation.last_error": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "BillingOperation.version"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BillingOperation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BillingOperation.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := billingoperation.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "BillingOperation.id": %w`, err)}
		}
	}
	return nil
}

func (_c *BillingOperationCreate) sqlSave(ctx context.Context) (*BillingOperation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BillingOperation.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BillingOperationCreate) createSpec() (*BillingOperation, *sqlgraph.CreateSpec) {
	var (
		_node = &BillingOperation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(billingoperation.Table, sqlgraph.NewFieldSpec(billingoperation.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AwardID(); ok {
		_spec.SetField(billingoperation.FieldAwardID, field.TypeString, value)
		_node.AwardID = value
	}
	if value, ok := _c.mutation.AgreementID(); ok {
		_spec.SetField(billingoperation.FieldAgreementID, field.TypeString, value)
		_node.AgreementID = value
	}
	if value, ok := _c.mutation.RecurringReference(); ok {
		_spec.SetField(billingoperation.FieldRecurringReference, field.TypeString, value)
		_node.RecurringReference = value
	}
	if value, ok := _c.mutation.RequestedStart(); ok {
		_spec.SetField(billingoperation.FieldRequestedStart, field.TypeTime, value)
		_node.RequestedStart = value
	}
	if value, ok := _c.mutation.RequestedEnd(); ok {
		_spec.SetField(billingoperation.FieldRequestedEnd, field.TypeTime, value)
		_node.RequestedEnd = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(billingoperation.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.BeforeSnapshotJSON(); ok {
		_spec.SetField(billingoperation.FieldBeforeSnapshotJSON, field.TypeString, value)
		_node.BeforeSnapshotJSON = value
	}
	if value, ok := _c.mutation.AfterSnapshotJSON(); ok {
		_spec.SetField(billingoperation.FieldAfterSnapshotJSON, field.TypeString, value)
		_node.AfterSnapshotJSON = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(billingoperation.FieldAttempts, field.TypeUint64, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(billingoperation.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.LeaseUntil(); ok {
		_spec.SetField(billingoperation.FieldLeaseUntil, field.TypeTime, value)
		_node.LeaseUntil = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(billingoperation.FieldVersion, field.TypeUint64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.VerifiedAt(); ok {
		_spec.SetField(billingoperation.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(billingoperation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(billingoperation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BillingOperation.Create().
//		SetAwardID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BillingOperationUpsert) {
//			SetAwardID(v+v).
//		}).
//		Exec(ctx)
func (_c *BillingOperationCreate) OnConflict(opts ...sql.ConflictOption) *BillingOperationUpsertOne {
	_c.conflict = opts
	return &BillingOperationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BillingOperation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BillingOperationCreate) OnConflictColumns(columns ...string) *BillingOperationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BillingOperationUpsertOne{
		create: _c,
	}
}

type (
	// BillingOperationUpsertOne is the builder for "upsert"-ing
	//  one BillingOperation node.
	BillingOperationUpsertOne struct {
		create *BillingOperationCreate
	}

	// BillingOperationUpsert is the "OnConflict" setter.
	BillingOperationUpsert struct {
		*sql.UpdateSet
	}
)

// SetAwardID sets the "award_id" field.
func (u *BillingOperationUpsert) SetAwardID(v string) *BillingOperationUpsert {
	u.Set(billingoperation.FieldAwardID, v)
	return u
}

// UpdateAwardID sets the "award_id" field to the value that was provided on create.
func (u *BillingOperationUpsert) UpdateAwardID() *BillingOperationUpsert {
	u.SetExcluded(billingoperation.FieldAwardID)
	return u
}

// SetAgreementID sets the "agreement_id" field.
func (u *BillingOperationUpsert) SetAgreementID(v string) *BillingOperationUpsert {
	u.Set(billingoperation.FieldAgreementID, v)
	return u
}

// UpdateAgreementID sets the "agreement_id" field to the value that was provided on create.
func (u *BillingOperationUpsert) UpdateAgreementID() *BillingOperationUpsert {
	u.SetExcluded(billingoperation.FieldAgreementID)
	return u
}

// SetRecurringReference sets the "recurring_reference" field.
func (u *BillingOperationUpsert) SetRecurringReference(v string) *BillingOperationUpsert {
	u.Set(billingoperation.FieldRecurringReference, v)
	return u
}

// UpdateRecurringReference sets the "recurring_reference" field to the value that was provided on create.
func (u *BillingOperationUpsert) UpdateRecurringReference() *BillingOperationUpsert {
	u.SetExcluded(billingoperation.FieldRecurringReference)
	return u
}

// SetState sets the "state" field.
func (u *BillingOperationUpsert) SetState(v string) *BillingOperationUpsert {
	u.Set(billingoperation.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *BillingOperationUpsert) UpdateState() *BillingOperationUpsert {
	u.SetExcluded(billingoperation.FieldState)
	return u
}

// SetBeforeSnapshotJSON sets the "before_snapshot_json" field.
func (u *BillingOperationUpsert) SetBeforeSnapshotJSON(v string) *BillingOperationUpsert {
	u.Set(billingoperation.FieldBeforeSnapshotJSON, v)
	return u
}

// UpdateBeforeSnapshotJSON sets the "before_snapshot_json" field to the value that was provided on create.
func (u *BillingOperationUpsert) UpdateBeforeSnapshotJSON() *BillingOperationUpsert {
	u.SetExcluded(billingoperation.FieldBeforeSnapshotJSON)
	return u
}

// ClearBeforeSnapshotJSON clears the value of the "before_snapshot_json" field.
func (u *BillingOperationUpsert) ClearBeforeSnapshotJSON() *BillingOperationUpsert {
	u.SetNull(billingoperation.FieldBeforeSnapshotJSON)
	return u
}

// SetAfterSnapshotJSON sets the "after_snapshot_json" field.
func (u *BillingOperationUpsert) SetAfterSnapshotJSON(v string) *BillingOperationUpsert {
	u.Set(billingoperation.FieldAfterSnapshotJSON, v)
	return u
}

// UpdateAfterSnapshotJSON sets the "after_snapshot_json" field to the value that was provided on create.
func (u *BillingOperationUpsert) UpdateAfterSnapshotJSON() *BillingOperationUpsert {
	u.SetExcluded(billingoperation.FieldAfterSnapshotJSON)
	return u
}

// ClearAfterSnapshotJSON clears the value of the "after_snapshot_json" field.
func (u *BillingOperationUpsert) ClearAfterSnapshotJSON() *BillingOperationUpsert {
	u.SetNull(billingoperation.FieldAfterSnapshotJSON)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *BillingOperationUpsert) SetAttempts(v uint64) *BillingOperationUpsert {
	u.Set(billingoperation.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *BillingOperationUpsert) UpdateAttempts() *BillingOperationUpsert {
	u.SetExcluded(billingoperation.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *BillingOperationUpsert) AddAttempts(v uint64) *BillingOperationUpsert {
	u.Add(billingoperation.FieldAttempts, v)
	return u
}

// SetLastError sets the "last_error" field.
func (u *BillingOperationUpsert) SetLastError(v string) *BillingOperationUpsert {
	u.Set(billingoperation.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *BillingOperationUpsert) UpdateLastError() *BillingOperationUpsert {
	u.SetExcluded(billingoperation.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *BillingOperationUpsert) ClearLastError() *BillingOperationUpsert {
	u.SetNull(billingoperation.FieldLastError)
	return u
}

// SetLeaseUntil sets the "lease_until" field.
func (u *BillingOperationUpsert) SetLeaseUntil(v time.Time) *BillingOperationUpsert {
	u.Set(billingoperation.FieldLeaseUntil, v)
	return u
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *BillingOperationUpsert) UpdateLeaseUntil() *BillingOperationUpsert {
	u.SetExcluded(billingoperation.FieldLeaseUntil)
	return u
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (u *BillingOperationUpsert) ClearLeaseUntil() *BillingOperationUpsert {
	u.SetNull(billingoperation.FieldLeaseUntil)
	return u
}

// SetVersion sets the "version" field.
func (u *BillingOperationUpsert) SetVersion(v uint64) *BillingOperationUpsert {
	u.Set(billingoperation.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *BillingOperationUpsert) UpdateVersion() *BillingOperationUpsert {
	u.SetExcluded(billingoperation.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *BillingOperationUpsert) AddVersion(v uint64) *BillingOperationUpsert {
	u.Add(billingoperation.FieldVersion, v)
	return u
}

// SetVerifiedAt sets the "verified_at" field.
func (u *BillingOperationUpsert) SetVerifiedAt(v time.Time) *BillingOperationUpsert {
	u.Set(billingoperation.FieldVerifiedAt, v)
	return u
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *BillingOperationUpsert) UpdateVerifiedAt() *BillingOperationUpsert {
	u.SetExcluded(billingoperation.FieldVerifiedAt)
	return u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *BillingOperationUpsert) ClearVerifiedAt() *BillingOperationUpsert {
	u.SetNull(billingoperation.FieldVerifiedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingOperationUpsert) SetUpdatedAt(v time.Time) *BillingOperationUpsert {
	u.Set(billingoperation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingOperationUpsert) UpdateUpdatedAt() *BillingOperationUpsert {
	u.SetExcluded(billingoperation.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.BillingOperation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(billingoperation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BillingOperationUpsertOne) UpdateNewValues() *BillingOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(billingoperation.FieldID)
		}
		if _, exists := u.create.mutation.RequestedStart(); exists {
			s.SetIgnore(billingoperation.FieldRequestedStart)
		}
		if _, exists := u.create.mutation.RequestedEnd(); exists {
			s.SetIgnore(billingoperation.FieldRequestedEnd)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(billingoperation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BillingOperation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BillingOperationUpsertOne) Ignore() *BillingOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BillingOperationUpsertOne) DoNothing() *BillingOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BillingOperationCreate.OnConflict
// documentation for more info.
func (u *BillingOperationUpsertOne) Update(set func(*BillingOperationUpsert)) *BillingOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BillingOperationUpsert{UpdateSet: update})
	}))
	return u
}

// SetAwardID sets the "award_id" field.
func (u *BillingOperationUpsertOne) SetAwardID(v string) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetAwardID(v)
	})
}

// UpdateAwardID sets the "award_id" field to the value that was provided on create.
func (u *BillingOperationUpsertOne) UpdateAwardID() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateAwardID()
	})
}

// SetAgreementID sets the "agreement_id" field.
func (u *BillingOperationUpsertOne) SetAgreementID(v string) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetAgreementID(v)
	})
}

// UpdateAgreementID sets the "agreement_id" field to the value that was provided on create.
func (u *BillingOperationUpsertOne) UpdateAgreementID() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateAgreementID()
	})
}

// SetRecurringReference sets the "recurring_reference" field.
func (u *BillingOperationUpsertOne) SetRecurringReference(v string) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetRecurringReference(v)
	})
}

// UpdateRecurringReference sets the "recurring_reference" field to the value that was provided on create.
func (u *BillingOperationUpsertOne) UpdateRecurringReference() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateRecurringReference()
	})
}

// SetState sets the "state" field.
func (u *BillingOperationUpsertOne) SetState(v string) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *BillingOperationUpsertOne) UpdateState() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateState()
	})
}

// SetBeforeSnapshotJSON sets the "before_snapshot_json" field.
func (u *BillingOperationUpsertOne) SetBeforeSnapshotJSON(v string) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetBeforeSnapshotJSON(v)
	})
}

// UpdateBeforeSnapshotJSON sets the "before_snapshot_json" field to the value that was provided on create.
func (u *BillingOperationUpsertOne) UpdateBeforeSnapshotJSON() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateBeforeSnapshotJSON()
	})
}

// ClearBeforeSnapshotJSON clears the value of the "before_snapshot_json" field.
func (u *BillingOperationUpsertOne) ClearBeforeSnapshotJSON() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.ClearBeforeSnapshotJSON()
	})
}

// SetAfterSnapshotJSON sets the "after_snapshot_json" field.
func (u *BillingOperationUpsertOne) SetAfterSnapshotJSON(v string) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetAfterSnapshotJSON(v)
	})
}

// UpdateAfterSnapshotJSON sets the "after_snapshot_json" field to the value that was provided on create.
func (u *BillingOperationUpsertOne) UpdateAfterSnapshotJSON() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateAfterSnapshotJSON()
	})
}

// ClearAfterSnapshotJSON clears the value of the "after_snapshot_json" field.
func (u *BillingOperationUpsertOne) ClearAfterSnapshotJSON() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.ClearAfterSnapshotJSON()
	})
}

// SetAttempts sets the "attempts" field.
func (u *BillingOperationUpsertOne) SetAttempts(v uint64) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *BillingOperationUpsertOne) AddAttempts(v uint64) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *BillingOperationUpsertOne) UpdateAttempts() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *BillingOperationUpsertOne) SetLastError(v string) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *BillingOperationUpsertOne) UpdateLastError() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *BillingOperationUpsertOne) ClearLastError() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.ClearLastError()
	})
}

// SetLeaseUntil sets the "lease_until" field.
func (u *BillingOperationUpsertOne) SetLeaseUntil(v time.Time) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetLeaseUntil(v)
	})
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *BillingOperationUpsertOne) UpdateLeaseUntil() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateLeaseUntil()
	})
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (u *BillingOperationUpsertOne) ClearLeaseUntil() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.ClearLeaseUntil()
	})
}

// SetVersion sets the "version" field.
func (u *BillingOperationUpsertOne) SetVersion(v uint64) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *BillingOperationUpsertOne) AddVersion(v uint64) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *BillingOperationUpsertOne) UpdateVersion() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateVersion()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *BillingOperationUpsertOne) SetVerifiedAt(v time.Time) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *BillingOperationUpsertOne) UpdateVerifiedAt() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *BillingOperationUpsertOne) ClearVerifiedAt() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.ClearVerifiedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingOperationUpsertOne) SetUpdatedAt(v time.Time) *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingOperationUpsertOne) UpdateUpdatedAt() *BillingOperationUpsertOne {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BillingOperationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BillingOperationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BillingOperationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BillingOperationUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: BillingOperationUpsertOne.ID is not supported by MySQL driver. Use BillingOperationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BillingOperationUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BillingOperationCreateBulk is the builder for creating many BillingOperation entities in bulk.
type BillingOperationCreateBulk struct {
	config
	err      error
	builders []*BillingOperationCreate
	conflict []sql.ConflictOption
}

// Save creates the BillingOperation entities in the database.
func (_c *BillingOperationCreateBulk) Save(ctx context.Context) ([]*BillingOperation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BillingOperation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BillingOperationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BillingOperationCreateBulk) SaveX(ctx context.Context) []*BillingOperation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BillingOperationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BillingOperationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BillingOperation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BillingOperationUpsert) {
//			SetAwardID(v+v).
//		}).
//		Exec(ctx)
func (_c *BillingOperationCreateBulk) OnConflict(opts ...sql.ConflictOption) *BillingOperationUpsertBulk {
	_c.conflict = opts
	return &BillingOperationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BillingOperation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BillingOperationCreateBulk) OnConflictColumns(columns ...string) *BillingOperationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BillingOperationUpsertBulk{
		create: _c,
	}
}

// BillingOperationUpsertBulk is the builder for "upsert"-ing
// a bulk of BillingOperation nodes.
type BillingOperationUpsertBulk struct {
	create *BillingOperationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BillingOperation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(billingoperation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BillingOperationUpsertBulk) UpdateNewValues() *BillingOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(billingoperation.FieldID)
			}
			if _, exists := b.mutation.RequestedStart(); exists {
				s.SetIgnore(billingoperation.FieldRequestedStart)
			}
			if _, exists := b.mutation.RequestedEnd(); exists {
				s.SetIgnore(billingoperation.FieldRequestedEnd)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(billingoperation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BillingOperation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BillingOperationUpsertBulk) Ignore() *BillingOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BillingOperationUpsertBulk) DoNothing() *BillingOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BillingOperationCreateBulk.OnConflict
// documentation for more info.
func (u *BillingOperationUpsertBulk) Update(set func(*BillingOperationUpsert)) *BillingOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BillingOperationUpsert{UpdateSet: update})
	}))
	return u
}

// SetAwardID sets the "award_id" field.
func (u *BillingOperationUpsertBulk) SetAwardID(v string) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetAwardID(v)
	})
}

// UpdateAwardID sets the "award_id" field to the value that was provided on create.
func (u *BillingOperationUpsertBulk) UpdateAwardID() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateAwardID()
	})
}

// SetAgreementID sets the "agreement_id" field.
func (u *BillingOperationUpsertBulk) SetAgreementID(v string) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetAgreementID(v)
	})
}

// UpdateAgreementID sets the "agreement_id" field to the value that was provided on create.
func (u *BillingOperationUpsertBulk) UpdateAgreementID() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateAgreementID()
	})
}

// SetRecurringReference sets the "recurring_reference" field.
func (u *BillingOperationUpsertBulk) SetRecurringReference(v string) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetRecurringReference(v)
	})
}

// UpdateRecurringReference sets the "recurring_reference" field to the value that was provided on create.
func (u *BillingOperationUpsertBulk) UpdateRecurringReference() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateRecurringReference()
	})
}

// SetState sets the "state" field.
func (u *BillingOperationUpsertBulk) SetState(v string) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *BillingOperationUpsertBulk) UpdateState() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateState()
	})
}

// SetBeforeSnapshotJSON sets the "before_snapshot_json" field.
func (u *BillingOperationUpsertBulk) SetBeforeSnapshotJSON(v string) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetBeforeSnapshotJSON(v)
	})
}

// UpdateBeforeSnapshotJSON sets the "before_snapshot_json" field to the value that was provided on create.
func (u *BillingOperationUpsertBulk) UpdateBeforeSnapshotJSON() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateBeforeSnapshotJSON()
	})
}

// ClearBeforeSnapshotJSON clears the value of the "before_snapshot_json" field.
func (u *BillingOperationUpsertBulk) ClearBeforeSnapshotJSON() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.ClearBeforeSnapshotJSON()
	})
}

// SetAfterSnapshotJSON sets the "after_snapshot_json" field.
func (u *BillingOperationUpsertBulk) SetAfterSnapshotJSON(v string) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetAfterSnapshotJSON(v)
	})
}

// UpdateAfterSnapshotJSON sets the "after_snapshot_json" field to the value that was provided on create.
func (u *BillingOperationUpsertBulk) UpdateAfterSnapshotJSON() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateAfterSnapshotJSON()
	})
}

// ClearAfterSnapshotJSON clears the value of the "after_snapshot_json" field.
func (u *BillingOperationUpsertBulk) ClearAfterSnapshotJSON() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.ClearAfterSnapshotJSON()
	})
}

// SetAttempts sets the "attempts" field.
func (u *BillingOperationUpsertBulk) SetAttempts(v uint64) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *BillingOperationUpsertBulk) AddAttempts(v uint64) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *BillingOperationUpsertBulk) UpdateAttempts() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *BillingOperationUpsertBulk) SetLastError(v string) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *BillingOperationUpsertBulk) UpdateLastError() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *BillingOperationUpsertBulk) ClearLastError() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.ClearLastError()
	})
}

// SetLeaseUntil sets the "lease_until" field.
func (u *BillingOperationUpsertBulk) SetLeaseUntil(v time.Time) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetLeaseUntil(v)
	})
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *BillingOperationUpsertBulk) UpdateLeaseUntil() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateLeaseUntil()
	})
}

// ClearLeaseUntil clears the value of the "lease_until" field.
func (u *BillingOperationUpsertBulk) ClearLeaseUntil() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.ClearLeaseUntil()
	})
}

// SetVersion sets the "version" field.
func (u *BillingOperationUpsertBulk) SetVersion(v uint64) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *BillingOperationUpsertBulk) AddVersion(v uint64) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *BillingOperationUpsertBulk) UpdateVersion() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateVersion()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *BillingOperationUpsertBulk) SetVerifiedAt(v time.Time) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *BillingOperationUpsertBulk) UpdateVerifiedAt() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *BillingOperationUpsertBulk) ClearVerifiedAt() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.ClearVerifiedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BillingOperationUpsertBulk) SetUpdatedAt(v time.Time) *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BillingOperationUpsertBulk) UpdateUpdatedAt() *BillingOperationUpsertBulk {
	return u.Update(func(s *BillingOperationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BillingOperationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BillingOperationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BillingOperationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BillingOperationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
